### ISSUE TITLE
stats.csv can't be edited

### ISSUE THREAD

**Issue by leefnmajors** [cadon/ARKStatsExtractor#1]
Any attempts I've made to edit the csv file results in an unusuable csv file. The movement speed on Ankylos and Gigantos is wrong (should be 0.5 and .06, respectively), the base stamina on Mesopithecus is wrong (should be 100, not 10), and Giganotos are flat out wrong on melee/health (likely outdated numbers before the 40% nerf). Only wrong numbers I've caught so far.

**Comment by cadon** [comment]
Hi, thanks for the feedback.

How did you edit the file stats.csv, what application did you use? How was the file unusuable after the edit (any error message etc)? I can edit the file with windows-notepad without problems.

The next version will have the stat-corrections, thanks for pointing them out. I can't see what do you mean by the 0.06 for the speed of the giganoto, though, can you explain this in more detail? The giganotosaur has another specialty that I makes it hard to extract the values, because it has no bonus on torpor which is used by the tool. I will implement it different for the giganoto, until then it will probably not work for it. Besided this, the giganoto has very few increases when leveling up, so it's not that important what level you have for this species.

**Comment by leefnmajors** [comment]
It's not the Giganoto that has the speed issue; it's the Gigantopithecus : p. I was using Open Office at first, then various CVS editors, but every time I saved it depending on what I did it produced weird errors. It would either make the parser read it incorrectly (first creature became "each line with only one value..."), or occasionally, I got an unhandled exception (usually when using commas as the delimiter). I can try it again with Notepad.

**Comment by leefnmajors** [comment]
I found a few other minor stat corrections.
Pulminoscorpius should have a base HP of 280; I think this is wrong in the devkit as well since the wiki had it wrong too. Sarcos also have a TameBonusMult of .65 instead of .5 on their health, and Kairukus were all kinds of borked. Here's the corrected table.

Kairuku
95,0.2,0.27,0.5,0
200,0.1,0.1,0,0
0,0.1,0.1,0,0
900,0.1,0.1,0,.15
70,0.02,0.04,0,0
8,0.05,0.1,.5,0.4
1,0,0.025,2,0
300,0.06,0,0.5,0

I didn't catalog any of my aquatic creatures, so they might have a few minor incorrect stats. Overall though, pretty good considering that's a few thousand numbers... great work on the tool BTW. Been dying for something like this to improve my ability to selectively breed.

**Comment by cadon** [comment]
Thanks again! I'll include your numbers in the new version. I also renamed the stats.csv to stats.txt, it will cause less trouble with the opening.

It seems the devs changed some numbers of the creatures and the devkit is not yet updated. If you find any other updated stats, you're welcome to post them here or to change the stats-table in the wiki.

**Comment by cadon** [comment]
A new version has just been released that has fixed all the mentioned bugs and errors.
