### ISSUE TITLE
Breeding plan

### ISSUE THREAD

**Issue by Aije85** [cadon/ARKStatsExtractor#1001]
Hello!
Working on my Deino¤#"%¤ line and it deosn't make any sense to me. Maybe I'm missing something?
But why would I want to breed two dinos with the same stats? Becuse I haven't reach the max level/stats of the dinos yet.

Do I have to use top stats on these?

Thankful for awnser!
Aije
![ARK Smart Breeding Deino](https://user-images.githubusercontent.com/58341326/69884534-32efc900-12d9-11ea-830f-745e9f467e50.png)

**Comment by VolatilePulse** [comment]
You have filtered out all creatures that have at least 1 mutation. On the left side, you can change the maximum allowed. 0 is ideal for starting a breeding line, but I'm not sure exactly what you're looking for.

In the library view, you can see the mutation counter for each creature to see what the planner can recommend to you.

**Comment by Aije85** [comment]
Yes thats correct. I also have the ones with mutation set to "unavaible" so it wont count. Because I want a clean line.
Here's a image of the library. As you see I have clean ones that have better level/stats.

Thanks!
![ARK Smart Breeding Deino 2](https://user-images.githubusercontent.com/58341326/69891104-51b28780-12fa-11ea-9f29-c5d5a2eb4234.png)
![ARK Smart Breeding Deino 3](https://user-images.githubusercontent.com/58341326/69891103-51b28780-12fa-11ea-8233-14557e8b0f1a.png)

**Comment by cadon** [comment]
Your current breeding mode ist set to `High Stats`, which looks for the best overall level of the offspring. If you want to combine all your top stats in a creature you need to use the `Top Stats Cn` mode.

**Comment by Aije85** [comment]
Ahh so high stats is just to breed for the highest level dino in your inventory?
In what case would I want to use that option?

Thanks allot mate!

**Comment by cadon** [comment]
High Stats just looks for the highest levels for the offspring. This option should be used if you already have a top creature pair (i.e. parents with only top stats).
Top Stats on the other hand suggests pairings so that you get a top creature.

For example if you have a creature with a single top stat that no other creature has, e.g. a HP level of 50, but all other stats of that creture are at 20. To get a top creature, you need to breed in this level 50 HP at some point. The High Stat algorithm will rank this creature very low, because the probability of the offspring to have low levels is very high. The Top Stat algorithm on the other hand will prefer this creature because it has a top stat that is needed for a top creature.

**Comment by Aije85** [comment]
Ah okey, I think I got it. Thanks for the explaining!

And thanks for a great program!
