### ISSUE TITLE
Breeding plan mutation count setting not working

### ISSUE THREAD

**Issue by darthmelak** [cadon/ARKStatsExtractor#1052]
Got a mutation before consolidating my stock, and I want to exclude it from the breeding plan for the moment. Noticed the mutation setting, but it doesn't seem to work.

![image](https://user-images.githubusercontent.com/3816699/77739015-1eb2a300-7011-11ea-882c-e2cfcaf985f6.png)

**Comment by cadon** [comment]
Hi, recently I changed it so that only pairs are filtered out where both creatures exceed the mutation-limit. It's useful to keep the pairs in where only one creature has more mutations than the limit, because one creature with less than 20 mutations can still create a mutation in the offspring (the probability is less for these pairs, though).
For better controlling which pairs are displayed, I'll add an option if both or only one partner has to fulfill the mutation limit.
