### ISSUE TITLE
Aberrant Dire Bear not extracting correctly

### ISSUE THREAD

**Issue by harry323** [cadon/ARKStatsExtractor#1064]
Hello, I'm trying to enter my Aberrant Dire Bears in ASB but the program isn't extracting the correct values. I typically use the "Last Export" button which usually works great but I've even manually entered the values and ASB still isn't calculating correctly.
![image](https://user-images.githubusercontent.com/46381622/79088446-43dd2c00-7d08-11ea-9e3e-7eca1ce368f0.png)
![image](https://user-images.githubusercontent.com/46381622/79088496-68390880-7d08-11ea-9e26-0d57f7fa4071.png)

**Comment by VolatilePulse** [comment]
It appears as thought it is extracting properly. Unfortunately, there are times that multiple stat combinations are possible and ASB requires you to tell it which stats you have leveled and what level the creature was before taming. You can do this by clicking on any of the yellow stat boxes. On the right hand side, all possible combinations for that stat are shown for you. Just select the correct one from there.

Once you made all of the correct choices, ASB will let you add the creature to your library.

**Comment by cadon** [comment]
Do you have adjusted stat-multipliers? When using the default values and the singleplayer setting, it looks fine for me.

**Comment by harry323** [comment]
@VolatilePulse Yes, even when I adjust the taming effectiveness for multiple combinations it still wouldn't calculate correctly.

@cadon No, I only have the default singleplayer values.

This bear was an existing bear in my library and I was just trying to update him in my library. In order to get the import to work I had to delete the existing entry in my library and then redo the export/import.

I tested again this morning with another existing bear and when I clicked the "Last Export" button, ASB didn't recognize the existing entry for the bear and offered to create new creature instead of update existing creature. The ID numbers matched. The weird thing is that after I checked out the existing bear entry in my Library and then reattempted the Last Export, ASB recognized the existing entry and offered to update the existing creature.

**Comment by VolatilePulse** [comment]
This combination works for me. I assumed a wild level of 130 and potential domestic level distributions. Unfortunately I don't know what level it was when you tamed it and I don't know where you applied the domestic levels. 
![Screenshot_20200413-113045](https://user-images.githubusercontent.com/6995232/79133800-a0792f00-7d7a-11ea-9352-837e2e572a56.png)

**Comment by harry323** [comment]
@VolatilePulse Another example:

![image](https://user-images.githubusercontent.com/46381622/79134929-2cd42380-7d74-11ea-8f86-b80b9e7cb78b.png)

The issue appears when I try to import stats for an Aberrant Dire Bear that already exists in my library. When I adjust the TE the exported data loses the ID numbers that were in the export and then it wants to add the creature as new instead of updating. 

The behavior is very odd and only happens with Aberrant Dire Bears as far as I can tell. I've been using ASB for a couple years now (and LOVE it) so it's not likely to be a simple that I'm missing.

**Comment by VolatilePulse** [comment]
It is actually a simple thing you're missing. By default, all creature imports have a taming effectiveness range of 0-100% as it's easier to rule out false positives than to get back the positive results the program removed. To restrict the taming effectiveness range, open settings, navigate to the Import Exported section, and in the lower left, adjust the lower range bounds to something more to your liking, like 80%. 

As far as why it doesn't update your existing creature, the program is designed to only accept the data in the export file. Any tweaks you make to the extractor after importing a creature will remove the ARK-ID and ID in-game fields as the data can no longer be trusted as accurate (typically because you're just trying to extract a different creature).

Adjusting the TE range by itself doesn't cause this issue, but clicking on the Extract button a second time does. We've discussed this behavior a few times in the past and believe this is the best way to address it. We are always open to suggestions on how to improve the behavior, though.

**Comment by harry323** [comment]
I tried again using your suggestion of adjusting the default taming effectiveness range. I'm still getting errant results. I've also cleared out my export .ini files and created new ones. It's still happening:

![image](https://user-images.githubusercontent.com/46381622/79407571-0b835b00-7f5f-11ea-9588-460dadbaf379.png)

**Comment by VolatilePulse** [comment]
This isn't a failed extraction, none of the ones you posted are. This is expected behavior. ASB can not know precisely how you distributed the domestic stats or what level the creature is, you have to tell it that.
