### ISSUE TITLE
Pelagornis Invalid Stats

### ISSUE THREAD

**Issue by ajerbajah** [cadon/ARKStatsExtractor#108]
Love this tool, it has been so helpful keeping breeding stock organized. However, ran into an issue with a Pelagornis having seemingly invalid stats. I've double and triple checked that I input them correctly, the stats are before imprinting, and all multipliers are set to official. The tool says it has invalid Health, Stamina, and Weight.

Thanks for taking a look!

![20160930143811_1](https://cloud.githubusercontent.com/assets/22550184/19015676/4cbcabee-87ce-11e6-8832-6ccbe6f8e65b.jpg)

**Comment by cadon** [comment]
Hi, the Pelagornis' stats were changed after its release, the game is known for not applying these changes immediately to all creatures. Probably that's the case here. This issue is often solved by level up the affected stats, so they're recalculated with the current values. In this case you could, after imprinting and level a stat up, go to the Tester-tab and try to match the values by increasing the wild-levels one by one. The Taming effectiveness is 100% for bred creatures, and the imprinting bonus can be set for testing. Not optimal, but can't think of a better solution.

**Comment by ajerbajah** [comment]
Sorry for the long response, busy week. The tester didn't work at first, but after a server reset it suddenly had stats that made sense. Thanks!
