### ISSUE TITLE
Some Dinos just dont work

### ISSUE THREAD

**Issue by JM4nG** [cadon/ARKStatsExtractor#1103]
Hi,

First of all I love your work and ive used smart breeder for quite some time now, almost always on official severs.

currently playing on  CamperCrew Island Server with better dinos mod, ive loaded the extra json files but some dinos just dont wrk.

Ive checked vs stat testing to see what numbers are out sometimes I can massage the numbers ie. change 1079.5 to 1079.1 small changes to agree with calc and it works fine other times I cat get the dino to add i either get message its possible but level higher than 150 or just flat out no I cant get one box to change to green.

At the moment my issue is with an Agrentavis I cant get to add, ive added other just fine but not this one, any suggestions?

I dont think i can enjoy the game without your smartbreeder tool .... please help!

if you need any more info please let me know

**Comment by VolatilePulse** [comment]
I think this issue is actually two separate ones but are perceived as one single issue. We'll start with the easiest to rule out. Kraken's Better Dinos is a unique mod as not only does it add replacement species to Ark, it also provides vanilla species creatures buffs. This poses an issue to ASB as buffs can modify an almost unlimited number of things about a creature, including it's stat values. ASB can not support creatures with buffs that alter stat values.

This specific issue only affects species listed [here](https://steamcommunity.com/workshop/filedetails/discussion/1565015734/1738848358535779586/) and their vanilla counterparts. The Argentavis, per your issue, doesn't specifically have any modifications to stats like the Deino and other species does so it's not immediate relevant in this case but could cause issues with other species.

The second issue, and most likely what you're experiencing with this Argentavis, is that I believe your stat multipliers aren't correct. If you're using the Dino Export feature for ASB, that should be the only possible issue (aside from things like imprint bugs).

Some screenshots could aid is in figuring out the specific issues though.

**Comment by JM4nG** [comment]
Thank you so much for your speedy reply!

These are all wild dinos as I am hesitant to breed if I can't use smart
breeder hahah so it's not imprint.

I've gone through the dinos i've wanted to breed,  rex, argie,
beelzebufo and they don't have any stat modifier just things like can walk
backwards or frog can attack in water if i was to breed lets say a trike
then yes id expect issues as its very different stat wise from a regular
trike. What gets me is some argies work fine and others don't, the server I
play on I've found wild tech dinos up to level 204 abs wild regular dinos
up to 180 can I adjust for this?

Yes i always export dinos then use last export i rarely get a creature that
works straight away i usually have to massage some numbers.

I will get you some screenshots when I go on a lunch break, the server has
an option to switch between vanilla and better dino as desired. I switched
a dino to vanilla and it made no difference.

Thanks again for getting back to me. I will come back with a screen shot in
3 hrs.

**Comment by JM4nG** [comment]
um got this warning

[image: image.png]

**Comment by VolatilePulse** [comment]
I believe you meant to send me an image, however, no image was uploaded. Could you try to upload it again through GitHub instead of your email?

**Comment by JM4nG** [comment]
I'm back at work now.

Was sever warning .. Trojan virus from smartbreeder

In sys 32 folder something email was file name

**Comment by VolatilePulse** [comment]
Same issue as #1102. The Trojan is listed as `Win32/Emali.a!cl`, however, I can't reproduce this issue, per my response to that issue.

If you have access to the export files, they will work as well, however, GitHub prevents uploading `.ini` files so you would need to change the file extension to something like `.txt` or similar.

**Comment by JM4nG** [comment]
Yes i believe so this is what i rec

**Comment by JM4nG** [comment]
Uploaded pic to github.

Any other information you need please let me know

**Comment by JM4nG** [comment]
i will get some dino exports for you tonight.

Cheers

**Comment by JM4nG** [comment]
Here is the megatherium i cant get to work.

[megatherium.txt](https://github.com/cadon/ARKStatsExtractor/files/5027973/megatherium.txt)

**Comment by VolatilePulse** [comment]
Yeah, I looked at that quickly and it appears the stat multipliers aren't quite right. I was wondering if you could send over a few more before I share the multipliers that I think would work for you. Preferably a few different species. I think you can zip the INI files and GitHub will allow you to upload them.

**Comment by JM4nG** [comment]
Hi,

Here you go.

[DinoExport_302070725176846704.zip](https://github.com/cadon/ARKStatsExtractor/files/5031345/DinoExport_302070725176846704.zip)

**Comment by VolatilePulse** [comment]
So all of the creatures that you sent me work with these settings. This frog was the only one that had a domestic level applied to it so I can't be confident about the `TameLevel` multipliers, however, it works for what you sent me.
![image](https://user-images.githubusercontent.com/6995232/89483500-3ee63180-d76a-11ea-802b-584d27309eb0.png)
If you find any other creatures that don't work, you can reply here.

**Comment by JM4nG** [comment]
All dinos wrking great without issue!

I never thought I'd get a reply to my issue but you were very speedy in
reply and resolution!
Excellent work I could be happier, I can breed again with accuracy and
efficiency
