### ISSUE TITLE
New Wyvern stats

### ISSUE THREAD

**Issue by Flamatter** [cadon/ARKStatsExtractor#1142]
New Wyvern stats got changed to be the same as crystal wyverns, which means when importing normal wyverns the programm shows an Error.

**Comment by VolatilePulse** [comment]
As the update is only a couple of hours old, our data has not yet been updated. It is done so automatically and the new values should be available in a few hours, pending any unforeseen issues.

Please be patient while we make sure everything is continuing to work as expected. To know when they're available, you can check for updates in the program and it will prompt you if a newer version is available. Thank you for your understanding.

**Comment by VolatilePulse** [comment]
I have just been informed by another developer that I was incorrect, the new Wyvern data, and other species data, is currently live and available for all users. Please check for updates in the program to retrieve the latest data.

There is a potential issue with the earlier version release of ASB limiting the automated check for another 24 hours. This is unlikely to change due to the infrequency at which this issue can occur and to help reduce bandwidth usage.
