### ISSUE TITLE
Zomdodo missing in creatue database

### ISSUE THREAD

**Issue by gbusoni** [cadon/ARKStatsExtractor#1150]
Since I got zomdodo in the last halloween event I get error when trying to import a save with zomdodo in crioopods. Can you add zomdodo to creature list_ Thanks

**Comment by coldino** [comment]
Since Zomdodo was removed from the base game it has been removed from our data automatically as it is no longer a valid species - your creature would also poof if you tried to unpod it. ASB is just telling you it found a species in the savegame that it cannot support.

One solution for you would be to add the mod `Event Assets` in ASB's mod selector. You don't even need it on the server (although it would allow you unpod it safely).
