### ISSUE TITLE
-CI_Dinos - unka / upload bug

### ISSUE THREAD

**Issue by TigerPugz** [cadon/ARKStatsExtractor#1185]
After they added the Unka and Crystal Golem I tried to export/import an unka and ever since then I get a pop up error message any time I try to use the import function (although I can click OK and continue, without the Unka uploading). 

Unknown species - ARK Smart Breeding v0.45.0.0
Some of the creatures to be imported have an unknown species, most likely because a mod is used. 
To import these creatures, this application needs additional information about these mods.

The values for species for the following mods are unknown even though an according mod file was already loaded, i.e. the species blueprint path is not in the mod file. If it is a manual mod file, make sure the blueprint path is correct.

-CI_Dinos

The following blueprint paths were not found in the mod file:

/Game/Mods/CI_Dinos/Crystal_Dragons/Crystal_Unka-BP.Crystal_Unka_BP

I have asked the mod developer and he/ISPEZZ says the problem/fix needs to be on your side.

**Comment by cadon** [comment]
Sorry for the long delay. The issue seems to be a typo in the classname in the mod that would need to be fixed by the dev of the mod. Specifically `/Game/Mods/CI_Dinos/Crystal_Dragons/Crystal_Unka_BP.Crystal_Unka_BP_C` inherits from the class `/Game/Mods/CI_Dinos/Crystal_Dragons/Unka/Unka_BP_Base.Unka_BP_Base_C`, but this class is stored as `/Game/Mods/CI_Dinos/Crystal_Dragons/unka/Unka_BP_Base.Unka_BP_Base_C` (i.e. there's a `u` instead of a `U` in `unka`). The game seems to work with that difference. We're not sure yet if it is save to assume casing can be ignored in general or if we create an exception just for this case when reading the data.

**Comment by coldino** [comment]
Just to confirm this **is** actually a bug in the mod. The case mismatch causes the base class to not be found so the species cannot be loaded. The details @cadon proved are exactly correct.

To make it absolutely clear: This species cannot be loaded on a Linux client or even a Windows client connected to a Linux server. In fact the only configurations this species works in are a single-player world on Windows or a Windows client connected to a Windows server.

That said, we are attempting to work around the issue in Purlovia (our data extractor) simply because we do not want a difference in our extraction results based on the case sensitivity of the filesystem it is currently on.

The result will be support for Crystal_Unka once again in ASB.

**Comment by coldino** [comment]
Update is out: <https://github.com/arkutils/Obelisk/commit/2a269fa683f6160f0645e3d7ba8048e796e7ba19>
