### ISSUE TITLE
Windows Defender halting download + VirusTotal Trojan detection?

### ISSUE THREAD

**Issue by DDYTL** [cadon/ARKStatsExtractor#1212]
Hey there everyone,

I haven't been able to locate anything concrete on this issue/its mention so I'll keep it simple. I recently got back into Ark, have the old version of this Smart Breeder (0.29.1.0) and want to redownload the newer build, however Windows halts me running the app, both from zip and exe (due to unknown publisher) and Virus Total detects a trojan within the .exe (Trojan.Malware.300983.susgen).

Has anyone come across a similar issue? Is this just normal due to some false-positive or is there actually something potentially unsafe? 

If it is unsafe, can I just continue using the 0.29.1.0 version or has there been some major changes to calculations etc since then that'd cause issues for my breeding tracking?

Please let me know, thanks in advance!

![image](https://user-images.githubusercontent.com/83468359/120930474-460d0180-c6e5-11eb-9e99-421b5f5deacb.png)

![image](https://user-images.githubusercontent.com/83468359/120930509-6ccb3800-c6e5-11eb-8378-29067c4a9c98.png)

**Comment by cadon** [comment]
New versions are often flagged as false positives by heuristic anti virus software. If you downloaded the file from this site, it should be safe. For more info about this issue see #1135, #1102, #724, #572, #461, #460, #458, #453.

Since version 0.29 some major changes were done, most notably a new format for the library file that supports all stats (e.g. in 0.29 the Gacha's crafting stat is not supported), also all new species won't be available in the old version.
