### ISSUE TITLE
Save File Import Error v0.50.3.0

### ISSUE THREAD

**Issue by Mulligrub** [cadon/ARKStatsExtractor#1284]
Save file import error - ARK Smart Breeding v0.50.3.0

An error occurred while importing the file C:\...\Fjordur.ark.

capacity was less than the current size.
Parameter name: value

System.ArgumentOutOfRangeException in mscorlib

Method throwing the error: System.ThrowHelper.ThrowArgumentOutOfRangeException

StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at SavegameToolkit.ArkSavegame.readBinaryHibernation(ArkArchive archive, ReadingOptions options)
   at SavegameToolkit.ArkSavegame.ReadBinary(ArkArchive archive, ReadingOptions options)
   at ARKBreedingStats.ImportSavegame.ReadSavegameFile(String fileName)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.ImportSavegame.<ImportCollectionFromSavegame>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.Form1.<RunSavegameImport>d__648.MoveNext()

**Comment by cadon** [comment]
Hi, thanks for the report.
The issue is most likely a negative number where the length of the hibernation entries should be defined in https://github.com/cadon/ArkSavegameToolkit/blob/08e06920690269e4af4e83be4de6fd70804a0d5c/SavegameToolkit/ArkSavegame.cs#L349 or L364 or L373.
This could be due to a corrupt save file or a change in the save file structure.
Try to save the file in Ark again (most servers save every couple of hours) or use the command `saveworld` if you have admin rights. Does this error then happens again? If yes, you could send me the file for further analysis if you want. Be sure to compress the file first (e.g. zip, rar, etc.), then e.g. upload it to a cloud service and send me the link, you can also send it via a discord pm (`cadaei#4308`).

**Comment by Mulligrub** [comment]
Hi Cadon, Just did a manual world save and still have the same issue. Noticed there was an ARK update earlier today so checked the backups either side of the update and can confirm all save files after the update have the issue and all prior are fine. This has occurred on all 6 of my servers (all different maps). Happy to send through a copy of the save, would you also like me to send through a copy of the working save for comparison?

**Comment by ListinO** [comment]
Hello,
I also have the same issue. In attachment you should find my zip file.
[TheIsland.zip](https://github.com/cadon/ARKStatsExtractor/files/9482910/TheIsland.zip)

**Comment by Chunks801** [comment]
Hi! I have the same issue. From what I can see it is the same exact error.
[Fjordur.zip](https://github.com/cadon/ARKStatsExtractor/files/9483160/Fjordur.zip)

**Comment by paulbrodersen** [comment]
Hi @cadon, I am also experiencing this problem, only that I am on the Island. Since several users have experienced this issue in the last few days, and there has been an update in that time frame, maybe there was a change in the save file structure that is the root cause (as you suggested above)? Admittedly I am quite biased because I would really, really like to use your incredibly useful software again), but I do think the issue is worth re-opening.

**Comment by cadon** [comment]
Hi @paulbrodersen , I closed the issue because the issue was fixed in Smart Breeding v0.50.4. The cause was a change in the save file format. Did you already update Smart Breeding to the latest version?

**Comment by paulbrodersen** [comment]
My bad. I didn't see a commit referencing this issue. After updating, I can confirm that everything works as expected. Thank you for getting back to me, and thanks for a great tool.

**Comment by cadon** [comment]
Yes, forgot to link it to this issue. The actual commit was done to the savegame toolkit at https://github.com/cadon/ArkSavegameToolkit/commit/62b3ea9f9eceb943aff5c5e80cdd15afa164bce9, and the commit on this repository just updated the version of the submodule at https://github.com/cadon/ARKStatsExtractor/commit/72ac3827466cf442f2870a7853942824cb76b1f1.
