### ISSUE TITLE
own mod definition files get overridden on a daily basis

### ISSUE THREAD

**Issue by Alatun-Rom** [cadon/ARKStatsExtractor#1307]
I've installed the mod "improved Lystrosaurus" (Mod id: 923689156), which changes some aspects of the vanilla Lystro regarding XP buff range and duration, but otherwise keeps the Dino stats (as far as I can see). 
Because this mod is not supported by this tool, I created the necessary file myself, using this help: https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values

Then I added an entry to the _manifest.json and got this thing working. 

But this tool does a daily check, if a new version is available and seems to override the _manifest.json every day. 

To prevent this, I changed the write permissions for the _manifest.json, so the file cannot be overridden any more and my changes will be kept. But this results in two error messages upon start, because the write protected files cannot be updated. Annoying, but better than adding my changes every day.

I already looked for a way to disable the daily download of the manifest.json, but did not find anything. An option to disable this daily download and the overwriting of manually changed files would be helpful.

**Comment by coldino** [comment]
Yes,  the problem is that this manifest file is exactly what must be downloaded by ASB in order to check which files are updated on the server.  Changes to it will always be overwritten. 

There is a simple solution! ASB will also load a file called `_customManifest.json` where you can put your local mod entries. 

Note, I'm on my phone right now and may have misremembered the exact filename as I can't easily look it up. 

We've also covered this topic a number of times in our Discord server, which you can join to get faster help on this sort of thing.

**Comment by cadon** [comment]
The file needs to be named `_manifestCustom.json`.

**Comment by Alatun-Rom** [comment]
Thx for the help. I moved my info into the custom file and it works like a charm.
