### ISSUE TITLE
Multipliers drag & drop issue

### ISSUE THREAD

**Issue by lucasrbarboza** [cadon/ARKStatsExtractor#1318]
Can't drag & drop multipliers from a downloaded server ini due to Windows 11 drag & drop restrictions (dunno why Microsoft made that restriction but it is there and it is horrible). Any tips on how to solve this? Maybe a import button on the application itself besides the drag & drop text?

**Comment by coldino** [comment]
A button to import isn't a bad idea because we often have issues with admin, etc.

You might be able to work around your issue by "unblocking" the file. Windows adds a flag to files downloaded from the internet if they're of a type that could potentially harm your PC (exe, dll, ini, etc). If you trust the file you can right click on the file, go into properties and remove the block.
