### ISSUE TITLE
ExportGun import list empty (ASA)

### ISSUE THREAD

**Issue by zokradonh** [cadon/ARKStatsExtractor#1326]
As far as it looks this project will support the Export Gun for ASA.

Looking at the source code I can see supporting code but not yet fully implemented, am I right?

I have made "ExportGun (ASA)" the default import path.
Path is at `ShooterGame\Saved\DinoExports\ASB`

Then
"File" -> "import exported Creatures" -> "ExportGun (ASA)"
the UI list is empty, since ARKStatsExtractor is only looking for .ini files not .json files that I have a lot of in this directory.

So how to import exported creatures of the ExportGun in ASA?

**Comment by zokradonh** [comment]
Ah, this works, thank you.

**Comment by cadon** [comment]
This window to import exported files is not really needed for the export gun, at least it's not planned to support that as well. The export gun files don't need to be extracted, the creatures can just be added to the library, so that extra step where the import window is used for is not needed. If you have multiple files, you can just drag & drop them in the ASB window to add the creatures.

**Comment by zokradonh** [comment]
> If you have multiple files, you can just drag & drop them in the ASB window to add the creatures.

This is nice to know, thank you
