### ISSUE TITLE
Online-Server-Stats-Import

### ISSUE THREAD

**Issue by Dwza** [cadon/ARKStatsExtractor#1334]
Can you implement an option were hoster can provide an url where the settings file can get downloaded from and get imported.. and on every start it checks if there is a different version so the hoster can provide new stats an ASB imports it automaticly?

**Comment by cadon** [comment]
That's a good idea! Due to the holidays I probably only can start on this in around 2 weeks.

**Comment by coldino** [comment]
This might be useful for some, but note the ASB Export Gun already does this for you. It might be easier for your admin to simply include the mod.

**Comment by Dwza** [comment]
> This might be useful for some, but note the ASB Export Gun already does this for you. It might be easier for your admin to simply include the mod.

Guess you did not understood my request. Ark supports Export by default. So there is no need for some gun. What i was asking for is the possability to choose a url in ASB from where config information can be pulled. So that an admin provider can place a file on his server and provide the url. The ASB user can than add this url to ASB and as soon as the server changes his stats... eg. Harvest X 3 or whatever, ASB either recognize a new file or ASB-User can hit a button to refresh current ASB-Configs.
The gun you tlaking about is to get dino stats and has none to do with the config it self.

**Comment by coldino** [comment]
Just for clarification, the export gun does indeed export all relevant multipliers, and it does so every time it detects they have changed. It solves your issue immediately without any more work, and has done since it's creation.

That's said, I could possibly see a use for this feature, although I expect the number of server owners abe to set it up in an automated fashion being in the single digits. It's not a simple task to combine just the relevant ini entries with the currently active dynamic config.

So I still recommend the export gun to admins as it would solve all of these issues without additional work.

**Comment by Dwza** [comment]
Oh, i was not aware of this. But lets say i want to tame some creatures and
all my creatures are exported. I dont know that the server stats were
changed (worst scenario 😅) i may would get the wrong times... But like i
sayed... Worst case that probably never happens ☺️
How ever, i will consider to check out this mod. I hope this is available
for ASA.


coldino ***@***.***> schrieb am Mi., 27. Dez. 2023, 14:33:
