### ISSUE TITLE
UI changes size as soon as you import

### ISSUE THREAD

**Issue by WitchyMods** [cadon/ARKStatsExtractor#1350]
A weird behavior started happening with the last update.
As soon as I click "Last Export", the window becomes smaller and the UI's size changes.

Before I click (put as fullscreen)
<img width="1920" alt="image" src="https://github.com/cadon/ARKStatsExtractor/assets/43689925/8650b0bb-683a-4f38-b14b-9f4d193f8d29">

After (no longer fullscreen and pretty much unreadable):
<img width="1282" alt="image" src="https://github.com/cadon/ARKStatsExtractor/assets/43689925/d78bb096-2bce-43a5-9992-c221237eba45">

**Comment by WitchyMods** [comment]
The 2nd screenshot is a bad example.
Here's what it looks like with my whole screen (so same size/ratio as the first one):

<img width="1920" alt="image" src="https://github.com/cadon/ARKStatsExtractor/assets/43689925/c8d19778-7f35-42a3-9ed4-79b272b76f8d">

**Comment by cadon** [comment]
This issue occurs on screens where the UI scaling of windows is not set to 100 %, usually on screens with a high resolution (high DPI).
Unfortunately it's tricky to resolve that with the (kinda outdated used framework WinForms) and I don't know exactly why it happens on some actions like pressing specific buttons while other button clicks don't trigger the rescaling.
I think the scaling is done differently on different windows versions, currently I can only test for Win 11. The following works fine for me.

On Win 11 the app is not rescaled (and all controls look fine) when using
* right click on application file `ARK Smart Breeding.exe`
* `Properties`
* `Compatibility`
* `Change high DPI settings`
* uncheck the upper checkbox `Use this setting to fix scaling porblems for this program instead of the one in Settings`
* check the bottom checkbox `Override high DPI sclaing behaviour`
* select `System` in the combobox

**Comment by WitchyMods** [comment]
Thanks :) Worked like a charm.
