### ISSUE TITLE
Sometimes Extract Calcs are wrong

### ISSUE THREAD

**Issue by FireCulex** [cadon/ARKStatsExtractor#139]
http://i.imgur.com/Xisirua.png
says 58 instead of 68 on a stego

**Comment by FireCulex** [comment]
woops, set the taming effectiveness down till i reached the correct level at the time of the tame and found them.

**Comment by cadon** [comment]
Hi, did you mean the number that is shown as "sum"? That might be a bit confusing, as this number only shows the sum of all the stats, except Speed and Torpor. The reason is, that the speed stat cannot be extracted, and is calculated by taking the Torpor-level and subtracting the sum of all the other stats. The number is shown there for ruling out combinations that would make the speed-level negative or that would be higher than the torpor-level. The "sum" shouldn't be used for other purposes as it probably only would be confusing.

**Comment by FireCulex** [comment]
Ah, what I had taken away from that was sum was used more of an "error" check
