### ISSUE TITLE
Best breeding partner for a neutered creature results in empty breeding plan view

### ISSUE THREAD

**Issue by tsebring** [cadon/ARKStatsExtractor#146]
This is happening in the latest version 0.20.9.2, previously in 0.20.7 the view would show best breeding partners irregardless of the creatures neutered status. This came in handy as you could set creatures you did not want included in the full breeding plan as neutered (even though it was not the intended function).

For unavailable creatures a popup is shown to alert that the creature is unavailable and an option to set it as available. This is not true for neutered creatures currently.

Not sure what the intended function is so I will hold off on debugging it.

**Comment by cadon** [comment]
Hi, thanks for the report. I added that because neutered/spayed creatures obviously cannot be used for breeding anymore. Never thought about that, but why not show the best breeding-partners for any creature (neutered/unavailable/dead), just with an extra note about the status of that creature. I'll add this in the next release. The partners would be only from the pool of available, alive, and non-neutered creatures, though. Would that solve the issue?

**Comment by tsebring** [comment]
I think that would work nicely as a solution. It makes more sense than an empty view and still enables this "quirk" feature. It is mostly useful if you want to exclude a newly tamed creature with a +1 top stat or similar from interfering with breeding suggestions in top stat mode.

**Comment by cadon** [comment]
Feature is added and released, thanks again for the suggestion.

Do you think it'd be worth to add an exlusion-list in the breeding-planner, so that creatures in that list are completely removed by the planner? Or another status like "Available, but ignore by the planner"?
