### ISSUE TITLE
Bred Argy Extraction Issue

### ISSUE THREAD

**Issue by pfar1** [cadon/ARKStatsExtractor#147]
Hi,

I appear to have an issue extracting the stats for a freshly bred argentavis.  I actually left it until i had applied an imprint due to the new version supporting imprinting, normally i extract before imprinting and all is ok.

I am also using v 020.9.2, although i have tried the previous version also, not bothered with the version before that due to the imprinting.

![screenshot](https://cloud.githubusercontent.com/assets/25183710/22036406/4c5081ea-dceb-11e6-802b-03a93ae4e3db.png)

![20170117_193128](https://cloud.githubusercontent.com/assets/25183710/22036535/d8068a22-dceb-11e6-8f8e-f7998971a243.jpg)

Thanks
Paul

**Comment by cadon** [comment]
Hi, thanks for trusting the tool so much to wait until a creature is imprinted :D It's still better to extract the levels before you imprint creature, because the game has a bug that not every stat is increased immediately after a cuddle. You can still change the imprinting the creature got later. That's the recommend way.

But back to the issue: Are you playing on an unofficial server with modified multipliers? It could be the BabyImprintingStatScaleMultiplier is different (the one that changes how much imprinting influences a stat.

Hm, I just tried to extract that bird, and it worked without issue. Maybe you changed the BabyImprintingStatScaleMultiplier by accident? Try setting it to 1 if it's not.

**Comment by pfar1** [comment]
Hi,

Its a fresh download of the latest release, i didnt modify any settings.  I did import my saved library from the previous version, not sure if it carries settings over?

Im on an official server.

Ill give it a go again and check that setting.  It will be tomorrow now.

Thanks for your hepp and great tool btw.

Paul

**Comment by cadon** [comment]
Hi, the multipliers are saved with the library, could be that they were different then.

**Comment by pfar1** [comment]
Hi,

Turns out you are absolutely correct...  The BabyImprintingStatScaleMultiplier was set higher than the default, looks like ive imported the setting with the library import.

I have set it back to default and can now extract the stats.

Thanks for your help and time!

Paul
