### ISSUE TITLE
Filesync Pingpong

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#149]
Me and two friends use the same database with Autosave and Auto Update Collection File enabled in the settings (backup disabled with 0 minutes). We use a program called Seafile (seafile.com) for synching (its like dropbox/google drive but with private server). When someone edits something and the database gets saved i can see in the seafile logs that it uploads and then downloads the file over and over. I made a copy of the database and checked that its the exact same file after every up/download. Only the date of the file changes.
It seems to me that your app saves the database even when there is no change?

**Comment by cadon** [comment]
Hi, thanks for the report!

I haven't really used this feature myself, so there might be bugs, glad you found that one. It seems that the fileWatcher (rightfully) recognizes a change in the file when the tool itself saved the file. The fileWatcher then triggers a loading of that changed file, which causes a save of the new file (from the autosave). This save again is recognized as too close to the last loading, so the fileWatcher ignores that one.

This will be fixed in the next release (should be online soon). I'd be happy to know if that fixes the issue.

**Comment by cadon** [comment]
Fix is released in 0.20.9.3. If you see strange things happen with the syncing or if it doesn't work at all, please let me know!

**Comment by noheals** [comment]
Everything seems to work except removing a creature (didnt work with .2 and doesnt work with .3) It just comes back after a sync. But no more ping pong 👍 and still updating in real time if you change or add something.

**Comment by cadon** [comment]
Good to hear it works. For the removing a creature, that might be a bit trickier. I have to think of a secure way to differentiate between a removed creature and a creature that was just added. In both cases the local and the remote version differ, and it has to be decided which creatures to take. The first can be removed, the second might just have been added when another user just has changed something as well. May be an improbable case, but if a creature gets lost this way, it'd be bad.

**Comment by cadon** [comment]
I guess removing a creature doesn't happen so often. It will work, if only one user has the library opened, and only open it after the library-file with the removed creature has been synchronized.
