### ISSUE TITLE
Pulmonoscorpius health issue

### ISSUE THREAD

**Issue by joebywan** [cadon/ARKStatsExtractor#16]
Just tamed a 120 pulmonoscorpius resulting in 162 level.

Health was 1636.1, and the software is flagging it as a red value.

https://dl.dropboxusercontent.com/u/231935/Screenshot%202016-03-26%2014.15.55.png

Unofficial, 4x taming multiplier, that's all that's changed.

Same with a this pteranodon.  https://dl.dropboxusercontent.com/u/231935/Screenshot%202016-03-26%2015.16.11.png Issues with the food, damage & speed.

**Comment by cadon** [comment]
Hi, thanks for the feedback!
The Ptera works fine for me. What version of the tool do you have? The current is 0.17.7.
For the Scorpion I have to investigate further.

**Comment by joebywan** [comment]
I thought it could've been the version, so I updated to the latest one 0.17.7 and it's still doing it.

**Comment by joebywan** [comment]
Ok, so another dino 158 carno freshly tamed.  Issues with food & damage.  https://dl.dropboxusercontent.com/u/231935/Screenshot%202016-03-27%2000.10.12.png

**Comment by cadon** [comment]
Just donwloaded a fresh copy of 0.17.7, it's working fine. Maybe you changed the multipliers in your library? You can try to select File -> Load Multipliers-File... and then choose the original multipliers.txt in the tool's folder.

**Comment by joebywan** [comment]
How would I change the multipliers in my library?

Is there something I have to change to reflect the 4x taming multiplier on the server?

If you're saying it's something I've modified, I just downloaded the zip, extracted & ran the executable.  Only changes I've made are entering dinosaur data.

**Comment by cadon** [comment]
Hm, strange. Can you send a screenshot of the unsuccessful extraction?
The taming-multiplier is independant from the tool, that shouldn't be an issue.

**Comment by joebywan** [comment]
Scorpion: https://dl.dropboxusercontent.com/u/231935/Screenshot%202016-03-27%2001.53.44.png  (Small note: The 'possible levels' section shouldn't think that the TE can be 87% as scorpions can't get that high on spoiled meat)

For some reason the pteranadon is working now which is confusing, but good atleast :)   https://dl.dropboxusercontent.com/u/231935/Screenshot%202016-03-27%2001.56.22.png

Also the carno seems to be sorted... I'm not sure why.  https://dl.dropboxusercontent.com/u/231935/Screenshot%202016-03-27%2001.58.06.png

It's super late here, so I'll have a go at my other dinos tomorrow if I get time.  Either way, hope this helps :)

**Comment by EchoAlien** [comment]
If its no trouble, I would like to contribute to this, as I too am having problems with the scorpion health.

[I screenied the stats and calculator together so you can get a good look too to make sure i'm not missing anything or typoing somewhere.](http://i.imgur.com/3p0bbWL.png) The Scorpion was found at level 100, tamed to 145 with ~91% TE.

The only multiplier i have changed is taming speed x8, but i never modified stat values. I checked what the health is supposed to be based on the amount of  points your calculator puts in and it says the health stat should be either 1548.1, or 1600.1, but ingame is actually 1568.1 as seen in the screenie. When i checked the other two stats mentioned above however, your calculator was green on both cases, and if i remember correctly, the number of points put in was 21 and 22 for those two numbers.

Good job on the tool by the way, was looking for something to keep track of breeding stats for me :)

**Comment by cadon** [comment]
Hi, sorry for the late reply, that post got burried.
The issue with the scorpion is more complicated as it seems. The stats were changed in a patch, not the big nerf-patch, only the values of the scorpion were adjusted, and only the health for the scorpion. Normally the creatures gain 20% of their base-value per wild-level, that was 60 with a base-health-value of 300. The adjustment decreased the base-health to 280, but strangely the increase per wild-level stayed at 60, making the increase 21.4285714285714% instead of 20% of the base-value. This alone would be no problem, a computer calculates both numbers unnoticeable fast, but the shown values ingame of the health didn't update, unless the health was leveled up, triggering a recalculation of the shown value.
So the issue you have could come from a wrongly displayed value. The solution for this could be to levelup health, to trigger a recalculation of the value.
If that doesn't help, there's maybe something else. If you happen to figure it out, I'd be happy to know.

**Comment by EchoAlien** [comment]
It seems to still be having this issue despite updates. i put some levels into the stats, and decided to unlock the stats to see where it put the points, if not in health.

It put 3 into damage (I know i put at least a couple into damage), which means it thinks the other two were something else (health), but that doesn't seem right either. Honestly i'm not sure what could be wrong...
![scorpstats2](https://cloud.githubusercontent.com/assets/18097148/14367740/9c0f13fc-fcce-11e5-908f-b1b8f52a20b6.png)

**Comment by EchoAlien** [comment]
I decided to go ahead and do it just so you'd have something to look at that _might_ help us figure out this issue.

I spawned a level 1 scorpion, and tamed it with no bonus levels, the health stat changed to 180.1. The image below includes its other stats for convenience, and below that is the health values at each level.

![level2scorphp](https://cloud.githubusercontent.com/assets/18097148/14371501/36247252-fced-11e5-9169-88d81b582a04.png)

![scorpionhealth](https://cloud.githubusercontent.com/assets/18097148/14371504/3a3cfa1c-fced-11e5-81c6-767ea283f7ad.png)

**Comment by cadon** [comment]
The problem is, newly spawned in scorpions work well, so they can't be used for figuring out the numbers the old ones use. I hope the old ones will adapt to the new numbers eventually.

IIRC the old values of the scorpion for the health were

    300,0.2,0.27,0.5,0

but they don't work either on the one you posted earlier. Maybe it's some kind of mix of these two.

**Comment by EchoAlien** [comment]
Thats really odd, because on my server i make a habit of admin destroying the dinos to refresh it to get stuff to spawn, and it wasn't long before my first post here that i had refreshed the spawns... i'm gonna chalk it up to the scorpion just being bugged in an odd way, and if i find anything worth noting, i'll let you know.

**Comment by cadon** [comment]
In the meantime, a restart of the server seems to solve the wrong display of the stat-values. If you have issues with Scorpions (or Procoptodons), wait for a server restart and the extraction should work.
