### ISSUE TITLE
Health and Melee Stats are not working

### ISSUE THREAD

**Issue by DSavant** [cadon/ARKStatsExtractor#177]
I have checked with the admin and the settings are correct, but the health and melee stats are not adding in.  Any idea why this is happening?
![rex](https://cloud.githubusercontent.com/assets/22563884/22856109/c27b34dc-f050-11e6-8b9d-673ef30b6d5a.jpg)

**Comment by cadon** [comment]
Hi, most probably some multipliers are not set correctly. Can you post the ones you set in the tool? Did you import the settings from the server with the .ini-files? That's the best way to ensure the values are all correct.

**Comment by DSavant** [comment]
I did import them from the .ini file
![settings](https://cloud.githubusercontent.com/assets/22563884/22857795/fff39932-f071-11e6-89eb-c7bce6115911.jpg)

**Comment by cadon** [comment]
Hi, probably the TameAdd-values for HP and damage are not explicitely changed, so they've the default-values which is 0.14 for both. With this setting the extraction works. Probably the TameAff is 0.44 for the two stats as well (it works both with this creature, but might not with other species).

I'll change it, so that all non-explicitely values are set to the official values and not left as they were before. Until then I recommend to click on the "Set to official" button and reimport the user.ini-file.

**Comment by DSavant** [comment]
One more thing, why does the imprint amount change, when i enter the amount, like 10% reverts to 8.6 and 82 reverts to 77.76 instead of staying where i put it.

**Comment by Dessa** [comment]
make sure the all of the Breeding Multipliers are set correctly. it can still be "wrong" by up to one % due to the fact the ark client not displaying fractions; it just rounds up.

**Comment by cadon** [comment]
As Dessa said it's related to the BabyMatureSpeedMultiplier and the BabyCuddleInvervallMultiplier when the baby was born / hatched. The tool changes the values to the closest valid number depending on these multipliers.

**Comment by DSavant** [comment]
Yeah i checked that, and verified it, it is correct, not sure what is causing it.

**Comment by cadon** [comment]
Make sure the multiplier in the tool have the value when the baby hatched, which is not necessarily the current value on the server.

**Comment by DSavant** [comment]
that might be what it is, because they adjusted the timers about a week ago
. Thanks
