### ISSUE TITLE
Procoptodon stats error, official server

### ISSUE THREAD

**Issue by TheKolega** [cadon/ARKStatsExtractor#19]
![procop bug](https://cloud.githubusercontent.com/assets/16735721/14316921/f90cf8cc-fc05-11e5-9535-38e198df61c8.JPG)

**Comment by cadon** [comment]
Hi, thanks for the feedback.
The Procoptodon got some small adjustments with a recent patch, which screwed up the stat-calculation (a similar thing occured to the scorpion). If the stat-multipliers of a species are changed, the values don't get recalculated, so the value you can see is not the correct value you would expect for the multipliers. To correct this, just level up a stat and the new shown value should be correct. The bad thing is, the procoptodon got its Torpor-multiplier changed, and this value cannot be leveled up, so the value you can see there (2513.5) is not the value you would expect with the new multpliers and you cannot make the game correct it. You can change the wild-level-torpor-multiplier of the Procoptodon to the original value (0.06) in the stats.txt, then it should work, or just use 1586.5 instead of the 2513.5, which is the correct value.
For the Health the value is also not correct, so the tool will not find a valid combination. I suggest to levelup Healt once so the value will be shown correctly. Alternatively you also can change the values to the old ones (IIRC the base value was 440, wild-levelup 0.1 and dom-levelup 0.27). The other values should work.

**Comment by TheKolega** [comment]
Hello, Cadon, thanks for the reply.
Just to notify you, with the old multipliers torpor gets a good calculation, but the health still has an issue, tested after leveling up, using the new multipliers.

**Comment by noheals** [comment]
Procoptodon still wont work with freshly tamed ones. We tamed a couple over the last 3 days and they all give red fields. Couple Examples:
![desktop 02 20 2017 - 16 35 33 03](https://cloud.githubusercontent.com/assets/8257956/23131560/bfd91136-f78a-11e6-9875-e06829135cb7.png)
![desktop 02 20 2017 - 16 37 50 04](https://cloud.githubusercontent.com/assets/8257956/23131616/ef87376e-f78a-11e6-8c67-b8f69a3cd144.png)

Tell me if you need more.

**Comment by noheals** [comment]
Same with bred ones:
![desktop 02 21 2017 - 09 06 27 05](https://cloud.githubusercontent.com/assets/8257956/23155945/1f56554e-f815-11e6-96b1-885da8e4d830.png)

**Comment by noheals** [comment]
working now with the new values file!
