### ISSUE TITLE
Taming Calculator is wrong in some dinos

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#200]
I have been comparing this to the like of DodoDex and the Wikipedia and in most cases it seems right,

The ones where I see it wrong are Achatina compared to DodoDex is wrong, but right with the Wikipedia so I assume DodoDex is wrong here.

However with the Giga, it appears to be wrong with both the DodoDex and Wikipedia.

DodoDex states 962 Narcotics and Wikipedia states 763 Narcotics and this program is suggesting 1526 Narcotics. I have no real experience taming a Giga, but this is a huge discrepancy between the calculators out there,

Castoroids is another one where there is a huge difference between the 3 calculators as well. There are a few more I noticed, but feel it would take longer to type them all in here.

These are all trying for a level 150 in each one.

**Comment by cadon** [comment]
Hi, thanks for reporting this, I'll have a look at it.

**Comment by cyberangel67** [comment]
If it helps, there are some observations.

1) I looked at a number of the raw stats for the likes of Achitina, Castoroids and a couple of others, against the values in the Ark Dev kit and notice some small differences in a few of the values. I doubt it would be enough to make a huge difference.

2) When it comes to taming, the code you use for Narcotics assumes that the Narcotic is over 5secs, yet all the information I am looking at assumes it is 8secs. The other thing I noticed with the code is that there is no allowance for torpor going back up either in larger stacks. For example, as a test I loaded up my private server and spawned in a Giga and DodoDex said it would need 188 Narcotics and your code said 290 or something. At 5x taming. When I actually tamed it I had used roughly around 150-160 Narcotics.

I realise that this is not ever going to be exact, but need some way to figure out best method of calculating the torpor going up. For example on the Giga, stacks of 100 Narcotics if you let it drop by 50K, then stack 100 Narcotics on the Giga, raises it by 40K and takes a good while to reach that.

I also didn't know you had added this feature and I like it, doesn't tell me how much darts, arrows etc I would need. But I guess in time.

**Comment by cadon** [comment]
Hi, the wiki had all the numbers wrong by the factor 2 (when the x2-taming was introduced, that was somehow used twice). And both the wiki and ASB had 5s for the rising-duration. Thank you very much for pointing that out! It's fixed on the wiki and will be fixed in the tool in the next release.

What do you mean with "the torpor going up in larger stacks"? As you probably know, if a torpor-inducing food is force-fed there are two effects that increase the torpor: first the induced torpor, and second the torpor that doesn't decrease during the time the torpor increases. The second effect makes torpor-inducing food with a larger duration/torpor-quotient more usefull for creatures with a fast torpor-decrease (Narcoberries are more effective for the Giganotosaurus).

If I understand you correctly you suggest there might be an error if torpor-inducing food (TIF) is force-fed in large quantities. If the offset is not large, I'd make rounding-errors responsible for that, but if there's another factor that changes the induced torpor depending on the speed the TIF is force-fed, that would explain the differences.

I just realised something. As the second effect plays a major role for fast torpor-decreasing creatures (e.g. Giganotosaurus), the exact amount is important for that. The bad news is, the exact formula for calculating this value is unknown (afaik). Probably all taming-calculators use an approximation that was published by crumplecorn in the old days of ARK (see [here](http://crumplecorn.com/content/taming-calculator) under the section Torpor Calculation), and that approximation probably will get more and more offset if the creature-level increases, resulting in larger errors for the TIF-amount. I'll put it on the todo list to dig deeper to find a better approximation or maybe even the exact formula to calculate the torpor-decrease.

**Comment by cadon** [comment]
On a second look, crumplecorn did always use the more precise approach with an exponential-function in his code. I'll include this in the next release. The difference will be less needed TIF for high-level creatures, so it seems to be a right step according your experience with the Giganoto needing less narcotics than dododex suggested (though I don't know if dododex uses the linear approach or the exponential one). At least the large error-inducing bugs you mentioned will be removed in the next release.

**Comment by cyberangel67** [comment]
Sounds good, but to go by what I was trying to say, as you mentioned the reference I had been reading. I was going by the Narcotic Calculation section there.

In other words, the calculation is assuming torpor is always going down and not taking in affect of it being raised. As explained on that site.

Like I said it is never going to be an exact number, but having it closer would be great.

**Comment by cyberangel67** [comment]
Any update when the tame/food values are going to get an update.

This is way wrong, others are only slightly.
![capture](https://cloud.githubusercontent.com/assets/1366816/24065126/f0de4698-0bbc-11e7-8bb2-baf1b584e385.PNG)

**Comment by cadon** [comment]
I haven't found the reason for that yet. I'm currently working on a bigger update, so I get back to the taming issues after that.

**Comment by VolatilePulse** [comment]
Even to this day, the taming calculator desperately needs some love. It's something that has been discussed numerous times before and creating a better interface will naturally include some of the key complaints mentioned in this issue. We have access to more data from Ark now than when this issue was originally raised, but properly presenting it in the program as well as culling most of the foods (have you seen the current lists?) and adding proper support for "special" tame methods is challenging.

This is still on the to-do list, but is currently a lower priority. We will continue to look at other applications like DodoDex for inspiration moving forward, but no one has entered the territory of modded creatures like we have and need to ensure ASB is able to support as many scenarios as possible.
