### ISSUE TITLE
Adding New Dino Issue - Max stat input 9999

### ISSUE THREAD

**Issue by Radioboy1987** [cadon/ARKStatsExtractor#205]
Hey everyone,

I need some help. I came across an issues while uploading my dino's stats. I have a 150 Wild dino that tamed out at level 224. No level ups yet.  I cant enter all the stats as the max input ends at 9999 and my dino have for example a food stat sitting at 17570. No multipliers applicable on server.

Did i miss something ?

Thanks for the read.
Rb

**Comment by cadon** [comment]
Hi, that limit is only in the Tester-Tab for the level-input, so if you have a dino with more than 9999 levels in a stat it'll be an issue. The upper limit for stat-values in the extractor is at 10M, so that should be no problem.

The tester-tab can be used to see how the stat-values will develop, depending on the the spend domesticated levels or the imprinting etc. For extracting use only the Extraction-tab.

**Comment by Radioboy1987** [comment]
Many Thanks :)
