### ISSUE TITLE
Pulminoscorpius red health stat

### ISSUE THREAD

**Issue by rev087** [cadon/ARKStatsExtractor#207]
The inventory during taming: https://cdn.discordapp.com/attachments/193496471541121024/290168765797367808/unknown.png

The app window: https://cdn.discordapp.com/attachments/193496471541121024/290168821271101440/unknown.png

**Comment by rev087** [comment]
Inventory after taming:
https://cdn.discordapp.com/attachments/193496471541121024/290172852194246657/unknown.png

App window:
https://cdn.discordapp.com/attachments/193496471541121024/290173000106508299/unknown.png

**Comment by cadon** [comment]
I'll reinvestigate that issue. See also #2 and #16.

**Comment by Taiine** [comment]
Same issue. Just tamed a 150 on a 9x server. Tamed out to lv223.
http://i.imgur.com/tun3FZ2.jpg
Can't you add away to override this error? "These stats are correct add to library anyway"?

**Comment by cadon** [comment]
Hi, that's not possible. How would the tool add a creature to the library whose levels are unknown? The whole point of the library is to have the levels of a creature. If the HP-levels cannot be extracted, what number should be used for it? You can try to approach the ingame value in the Tester in the tool and add it from there if the numbers are close enough for you to think it could be the correct level.

**Comment by MerlinQ** [comment]
Just chiming in on this issue since it is still present.
I am on Official The Center, if that matters.

I do have screenshots of two Scorps (both post-tame, pre leveling).
![20170408200507_1](https://cloud.githubusercontent.com/assets/20783841/24930546/563a5200-1eb6-11e7-9648-c08e87d12cd1.jpg)
![20170408205648_1](https://cloud.githubusercontent.com/assets/20783841/24930548/59ee4258-1eb6-11e7-84b8-fe16f061d44e.jpg)

No shots of the Smart Breeding app, but all values are correctly entered by hand with decimals, and double checked (and triple checked when I found I was a version behind and updated.)
Only health is red.
Currently using 0.22.4

**Comment by cadon** [comment]
The stats are now corrected after a server restart (still wrong after taming). I added an extra info in the extractor for this case. After a restart scorpions should be extractable.
