### ISSUE TITLE
Red Boxes

### ISSUE THREAD

**Issue by oOWarFireOo** [cadon/ARKStatsExtractor#264]
Keep getting red boxes, no matter what I do it does not work it has only been recently. Been using the app for along time and it just now not working I tried to update it - still didnt work. I play on the PS4, tried to add my pteranodon and a turtle, neither worked.

**Comment by oOWarFireOo** [comment]
![notworking1](https://cloud.githubusercontent.com/assets/27876068/25300652/d13e91d4-26d9-11e7-8419-b91fa3c7b655.PNG)

**Comment by cyberangel67** [comment]
I am guessing that you have the latest values file, as the Flyer Nerf hasn't hit the console as yet the program will have an issue if you try to add any Bird with this nerf into the program.

I would suggest in the future, as it is too late for it now. That you try to not upgrade this file until the console gets the update, otherwise you will end up with this issue again in the future.

I made a note about this with the author sometime ago and he has added text to try to explain this when it detects an update to this file is needed.

**Comment by oOWarFireOo** [comment]
The thing is that I did not update the app.
... unless it automatically updated itself. After realizing that it was not
working I updated it but it still did not work and it wasn't only flyers
that were not working it was all dinos. I tried to put in a turtle, a
ptera, allo, argy, the, and a rex. (I was very busy breeding lol)

**Comment by cadon** [comment]
Hi, for using an older values.json-file you can browse in the [releases list](https://github.com/cadon/ARKStatsExtractor/releases) and download an older one.

**Comment by cadon** [comment]
I'm closing this for now, I hope the issue was resolved. If not, feel free to respond / reopen.
