### ISSUE TITLE
Suggestion: Capture2Text

### ISSUE THREAD

**Issue by darthginger** [cadon/ARKStatsExtractor#269]
Hi if you need help with the OCR maybe [ this ](http://capture2text.sourceforge.net)is an option? It also has command line options for automation and currently works pretty good with ark.
"Capture2Text is free and licensed under the terms of the GNU General Public License."

**Comment by darthginger** [comment]
After some testing i can say that the stat number recognition is very good (99%+ on the first try). Other parts of the inventory are good too but not as good as the stats.

**Comment by cadon** [comment]
Hi, thanks for posting this, I had already looked at that, the library is pretty large though. I just released a new version that has an improved OCR-algorithm that also can be adjusted. If you have ideas on how to improve that further, let me know. An issue currently is the kerning, e.g. "22" is recognized as one character instead of two.

**Comment by VolatilePulse** [comment]
If the OCR library is going to be replaced, it needs something that is closer to 100% accurate than 99%. With 8 stats, roughly 4.5 numbers each, and 99% accuracy, that results in about 1 out of ever 2 or 3 screenshots having something wrong in them. We have seen libraries that support an almost 100% accuracy rating (I've never seen it fail), but they are only available commercially or under a paid license. We are still waiting for a comparable open source solution.
