### ISSUE TITLE
OCR: Level Label require words LEVEL in area but does not allow them to be read as letters

### ISSUE THREAD

**Issue by marianowinska89** [cadon/ARKStatsExtractor#284]
Hi!

I've tried playing around with the OCR calibration on the newest version. When I go to Labels Tab I can see that the Level label does require whole LEVEL: XXX is that correct?

I've tried narrowing it down to just the number but it seems to give error immediately after trying.
Now if I leave the label size as it is (so it takes whole word + number) - it always seems to try to read the letters LEVEL as numbers - even after modifying the template on the Output tab.

Besides that - it seems to work great on all other stats and numbers.

**Comment by cadon** [comment]
Hi, the level-label needs at least the colon (and the number). Labels that have only numbers, are only checked for numbers (that increases the precision, as a '4' cannot be mistaken for an 'A' etc.), so the levels-label usually is recognized as "13731: 123" or similar for a level 123. There has to be a way to know where the level starts, though, so the colon is also recognized. Later, everything before the colon is dismissed, so only the level is left. The output just shows everything that was recognized, before the cleanup.
So if you set the label for reading the level, make sure, that the colon is read as well, the word "LEVEL" doesn't have to be captured.
You might ask why the level is read at all, the reason is, the text is centered, so the level-number for a one digit level starts further to the right than a three-digit number.
