### ISSUE TITLE
Extraction fail Bred Rex

### ISSUE THREAD

**Issue by odelmalv** [cadon/ARKStatsExtractor#296]
Hello guys

I don't know what i'm doing wrong. Can you give me a hand?
![test](https://cloud.githubusercontent.com/assets/27784465/26026980/89952c78-37cb-11e7-9f48-cef5ee031be7.jpg)

**Comment by cadon** [comment]
If you're on an unofficial server, I need to know all the multipliers that are changed.

**Comment by odelmalv** [comment]
I'm on official server. I just updated to 0.23.2.
Same result. It's remarkable your interest on your project, thanks for helping.
![test](https://cloud.githubusercontent.com/assets/27784465/26027103/35d32ade-37cd-11e7-8e94-9341518ce712.jpg)

**Comment by cadon** [comment]
Strange. Was the rex imprinted during an event with increased breeding-multipliers, e.g. the valentines-event?

**Comment by odelmalv** [comment]
I don't know. I hard another similar case, but i guess it happens. I saved around 40 dinos and i just had trouble with those 2. Thanks you

**Comment by cadon** [comment]
The issue is, 15% imprinting is not possible for a rex with the default multipliers. So it was most probably changed multipliers during an event. The imprinting doesn't decreases over time as it did at the beginning when this feature was introduced, does it? And are the rexes already grown or is there a chance to imprint them another time?

**Comment by cadon** [comment]
The Rex can be extracted with matureSpeed = 1 and cuddleInterval = 0.5. It was probably hatched during an event.
