### ISSUE TITLE
Read Values of Window

### ISSUE THREAD

**Issue by Snap05** [cadon/ARKStatsExtractor#301]
Hello,

is there some Problem with the Option read values from the ark window?

It doesnt matter which dino i choose i doesn read the stats correct and everything is marked red.

When i type them in it works fine. The Dinos are all breed and i have the normal offical Rates as i am on offical.

Please Help

**Comment by cadon** [comment]
Hi, what problem do you mean exactly? It the recognition not always correct? The OCR is not perfect, some characters are not recognized correctly, mostly because of the changing background-pattern.

If you don't have a resolution of 1920x1080 in windows, then the current OCR-config-file is not the correct one. Currently there's only a config file for this resolution. Also, if you have scaled your UI, it might not work.

You can give adjusting the OCR to your settings a try in the OCR-tab in the tool. See here for more infos: https://github.com/cadon/ARKStatsExtractor/wiki/OCR

**Comment by VolatilePulse** [comment]
Closing for lack of information and activity.
