### ISSUE TITLE
Wild-level-steps can be independant from the max wild level with mods. Need new setting.

### ISSUE THREAD

**Issue by worsin** [cadon/ARKStatsExtractor#303]
Ive been using this for a while now, but since the last update i have many issues saving dinos.  Even though everything is filled out correctly something is always flagged red and prevents being able to save it.

You can see this Rex was a 242 Tamed with Mutton so its 97% ish taming ef making it 360.  All the info is correct and no levels have been put into any stats but the Damage shows red (even though its correct).

https://www.screencast.com/t/iQp3Yph2v

This has been happening quite often so i think i may revert back to the previous version till its fixed.

**Comment by worsin** [comment]
Reverting to the previous version allowed this rex to be saved with all green stats.

**Comment by cadon** [comment]
Hi, the reason is the sorting out of impossible wild levels. You can disable this sorting out in the settings by unchecking "Consider Wild Level steps", then it also works with the latest version.

To have a wild rex with level 242, your max-wild-level has to be e.g. 330, making the possible wild-levels multiplies of 11, or 660, making the wild levels multiplies of 22. If you've set the max-wild-level to a different number than 330 or 660, the level 242 is not possible. Usually a lot more options are displayed for yellow stats, so sorting out these impossible ones makes the extraction easier. If you've changed the max-wild-level recently, there still may be creatures with the old settings, which are not possible with the new ones.

**Comment by soepie7** [comment]
With Annunaki Genesis the max level is 600, yet the levels are in steps of 5, instead of the expected 20. Do I now set the max to 600, making levels like 245 impossible, or Do I set the max to 150, making levels like 155 impossible?

**Comment by cadon** [comment]
@soepie7, thanks for pointing that out. I'll add a new input to set the level-steps independantly from the max-wild-level-steps.

Until then just disable the "Consider wild level steps"-setting.
