### ISSUE TITLE
Daedon Food stat calculation different in Extractor and Tester

### ISSUE THREAD

**Issue by BorealManager5** [cadon/ARKStatsExtractor#319]
There seems to be a slight difference between Tester and Extractor. The value in the Extractor is correct.

![daedonextractor](https://cloud.githubusercontent.com/assets/29091526/26624904/ad56de6a-45f2-11e7-8b29-f91d3b8ce34e.PNG)
![daedontester](https://cloud.githubusercontent.com/assets/29091526/26624903/ad3f5c9a-45f2-11e7-87e5-eaf1fd778c62.PNG)

**Comment by cadon** [comment]
Hi, the reason is probably a (not shown, because smaller than 0.1) difference in the taming effectiveness (TE). The extractor cannot determine the TE exactly, there can be a rounding error which causes an offset of up to 0.1 % of the TE. In your case, the extractor calculated a TE of 99.828 %, which is shown as 99.9%. The level is correctly, it's just the value of the TE (and therefore the stat-values that are dependant on that), that are a bit off, but that doesn't change anything regarding the levels or the breeding-values.

It seems a bit strange, and only happens because that value is unusual high, usually that kind of error wouldn't be visible. I'll put it on the todo-list.

**Comment by cadon** [comment]
It's handled better now, though not perfectly. I guess it's not possible. The important thing: the extracted levels are correct.
