### ISSUE TITLE
Dimorphodon reporting torpor at incorrect level

### ISSUE THREAD

**Issue by joebywan** [cadon/ARKStatsExtractor#33]
Tamed this girl last night, the ingame shot shows she's 174, the software is saying 203 based on its torpor.

https://imgur.com/a/Exy27

**Comment by cadon** [comment]
Hi, did you check the "Since Taming no Server-Restart"-checkbox? The torpor after taming is shown too high (a bug), you have to tell the tool to recalculate the true torpor by checking that.
If that does not help, maybe you're not using the current version of the tool (0.18.6). I tried these values and it showed me that the wild level was 120 before taming.

**Comment by joebywan** [comment]
Apparently I did not, thanks!
