### ISSUE TITLE
[Extractor] Gigas Speed 'Wasted point' no longer calculated as of v.0.23.6

### ISSUE THREAD

**Issue by EsCanavi** [cadon/ARKStatsExtractor#338]
I need to manualy adds up level then substrat that to total level run the edit button and add the wasted points.
Seems like this started from the updated between June 3rd-> June 5th
![image](https://user-images.githubusercontent.com/29311595/26988155-3817306a-4d1c-11e7-99ff-4f77a4d99769.png)

**Comment by cadon** [comment]
Thanks for the report. It's related to the torpor-bug. This behaviour will be fixed in the next release. Note, that the speed can only be determined, if the taming effectiveness is known (which is not possible for the giganotosaur automatically) or the creature has not been just tamed (i.e. the torpor-bug is relevant). If the giganotosaur is tamed some time ago, it should be possible again in the next release.

**Comment by cadon** [comment]
Fix is released in 0.23.7.
