### ISSUE TITLE
New version not working for me

### ISSUE THREAD

**Issue by CroMatt** [cadon/ARKStatsExtractor#343]
So i downloaded your program to make things easier for me while breeding.
The thing is eaven when i make a new library, load OCR config (ocr.json) , manage the multipliers , the program wont Extract the dino stats. I tryed like 15 dinos (wild/tamed/bred) with bouth resolutions (window-full/fullscreen). So my question is am i missing something?

**Comment by cadon** [comment]
Hi, can you describe more precisely what is not working?
Is the OCR (read the values automatically) not putting valid values in the extractor, or does the extraction process not resulting in valid levels, even if you have put the values manually in there?

**Comment by CroMatt** [comment]
OCR puts nothing,as in it doesnt read the stats at all. When i put em manualy its gets bugged out as hell. Tribe name was never right. Dino lvl stays at 1, and when i extract it puts it automaticly on Bred each time i use it.

**Comment by cadon** [comment]
It sounds as if your monitor does not have a resolution of 1920x1080. The file that is included with the tool is calibrated to that resolution. Other resolutions have to be created manually, I haven't had time to make them yet, but it's doable from the tool, see https://github.com/cadon/ARKStatsExtractor/wiki/OCR

What do you mean "gets bugged out as hell"? Are the stats marked red instead of green or yellow? Then you're probably on an unofficial server that uses modified multiplier. Make sure to set them all correctly in the settings of the extractor.

**Comment by CroMatt** [comment]
https://prntscr.com/fjuiw2
When i extract em the stats are still white but, the Bred/lvl/taming eff boxes are orange,  im one of the admins so iw put all the modifiers in as they are on the ini files.

**Comment by CroMatt** [comment]
Oh yea, when i do try to create the new OCR file i cant pull the SS into the program

**Comment by cadon** [comment]
Can you post a screenshot of an inventory of a creature and also the multipliers of your server?

**Comment by CroMatt** [comment]
https://prntscr.com/fjuqym
https://prntscr.com/fjusp8

**Comment by cadon** [comment]
I see the issue: your UI is scaled down. The OCR has fixed locations where it tries to read the numbers, with the scaling the numbers are not there, and also they've not the expected size. If you set the UI-scaling to 100% it should work again. Or you change the OCR-config to your scale (see the link above for more infos).

The extraction itself seems to work fine if the numbers are entered manually.

**Comment by CroMatt** [comment]
That was it! Ty a lot, tc and hf , CM.
