### ISSUE TITLE
Cannot calibrate OCR

### ISSUE THREAD

**Issue by ToeiRei** [cadon/ARKStatsExtractor#346]
I got a small issue with the OCR vs the new interface - it doesn't work; So I wanted to create a ocr config file.

1. Did a screenshot (Steam)
2. Drag & Drop the File into the large empty area to start the ocr
3. Nothing happens

Expected result: The image would show up in the empty area

Resolution: 1920x1080
ASE Version: 0.23.6

**Comment by cadon** [comment]
Hi, make sure that in the tab "Output" the checkbox "Enable logging and editing" is checked.
If you have created a config file, you can send it to me for inclusion in the release for other users if you want.

**Comment by ToeiRei** [comment]
Hi @cadon,
Looks like the whole UI redesign pretty much broke the OCR functionality. Guess we'd have to wait until their GUI dancing is fixed. Here's the actual screenshot for testing
![20170615162012_1](https://user-images.githubusercontent.com/5990591/27198502-bb2a207a-5212-11e7-8d58-5e077b168d19.jpg)

**Comment by cadon** [comment]
Hi, that works nearly good for me with the default ocr-config-file. There seems to be an issue with the oxygen-stat missing, though. I'll look into that.

**Comment by ToeiRei** [comment]
That's what I get from the OCR shifting the labels a bit:

> Health: 3550.9/3680.1
> Stamina: 1530.0/1530.0
> Oxygen: 2869.6/3000.0
> Food: 2869.6/3000.0
> Weight: 0.0/792.0
> MeleeDamage: 257.7%
> MovementSpeed: 260.0%
> Torpor: 0.0/5456.5
> Imprinting: 100%
> Level: :.51/5:.:98
> NameSpecies: ♂AqqIyycqn_SqrcqM2LSq_cqI
> Tribe: Etatgacem
> Owner: >(_r

Level, Species, Tribe and Owner seem to be completely broken by (UI-Re-)design.

**Comment by cadon** [comment]
Yes, everything with text is harder to read, so there may be errors. The level is fine, though, it just is read a bit gibberishy, in the end only the last numbers are used, which is correct.
For the creature's name and species, the issue is the long name. The UI scales this text down if the name is long, and scaled-down characters are most probably read wrong.
The tribe and owner should be better, there seems to be a moving of these fields. You can try to adjust the labels a bit for these, I'll do it also in the next release. Thanks for letting me know that.

**Comment by Elvarion** [comment]
Creatures that has no Oxygen will not have the UI for oxygen, so this will shift the entire UI..
Here is a Creature that has Oxygen and no Imprint
https://gyazo.com/24505b346e8751c588a6d2e4669eaeb4
Here is a Creature without Oxygen but has Imprint
https://gyazo.com/195e3bd887ac9cf95d8c943767dd7ed7

**Comment by cadon** [comment]
The oxygen-fix was unintentionally defixed, it'll be refixed in the next release.

**Comment by Elvarion** [comment]
Ill hook into this issue since there is not really a point in making a new since the Issue is pretty much the same.

Cant get OCR to work on 1680x1050
I setup all the Labels (Is this correct, or should they be done in another way??)
https://gyazo.com/fe13acd06806e8ad529e0980a1386c4c

This is the OCR Output I get
https://gyazo.com/4fe2515cee7e2d13bb7f917eca5378af

Not sure how to really go around and changing the Templates and such so it can detect better..

**Comment by cadon** [comment]
Hi @Elvarion , that's a different issue. The default ocr is made for 1920x1080, using a lower resolution will not work with that ocr-config, because all letters are smaller. You've to decrease the height for the labels and reset all the letter-templates. See https://github.com/cadon/ARKStatsExtractor/wiki/OCR for more infos.

**Comment by Elvarion** [comment]
Hmm, still having issues getting it to work
Renamed a dino to a couple of |||||, found out that the font size on 1680x1050 is 14
Adjusted the size of the boxes. It throws error about most stats except Health and Imprint. Yet I cant extract those values. After several attempts to fix the letter templates I managed to extract the Tribe and Owner, But everything else just wont work. For example the Letter K is strange in the Recognized, it cuts of the first line of pixels (a "|" of the K, so it pretty much wanna see that as a C and not K)
Not really sure how to fix that :p

**Comment by cadon** [comment]
For now import exported is recommended over using OCR, currently there are no plans to improve the OCR.
