### ISSUE TITLE
Procoptodon

### ISSUE THREAD

**Issue by LupaPup** [cadon/ARKStatsExtractor#349]
![roo](https://user-images.githubusercontent.com/6458365/27257609-a83de5ca-53aa-11e7-9e8f-21fad3201c52.PNG)

I put one point into speed, to see if the stats would update -- it should be 100.0% as I've put in the stat calculator. Max level is 200, so with max eff its 299. Server hasn't restarted since taming, and all stats are default -- its an unofficial server.

**Comment by timegrinder** [comment]
Hey there,

Just to double check - did you also update the max wild / max tame levels in the mulitpliers page of settings (top right corner)?
As I understand ( been a while since I checked TBH ) the default setting is 150, so level 299 is outside of the range for a max tame + max tamed levels (150+74/5+71) so it may be assuming it's out of range and may be bred.

One way or the other it appears to be clamping the extraction at 156 wild + 11 tamed levels.
If you haven't already did you also click on the yellow stats and correct them in the right panel? ( I assume you'd be correcting them all to 0 tame (or dom) levels if possible )

**Comment by cadon** [comment]
Hi, some species have screwed up stats, probably after they got nerfed (over a year ago), and still don't work. I haven't found the reason for their deviation in some stat-values yet. Affected are the scorpion and the roo. For now there's nothing you can do. Sorry.

**Comment by LupaPup** [comment]
Thanks Cadon, luckily I'm not actually looking to breed the Roo -- its more of a "I can't pass up a max level" syndrome. 

Hope someday it gets sorted out --- but super thankful that is less commonly used critters. :)
