### ISSUE TITLE
Rex Reds (New Speed Values)

### ISSUE THREAD

**Issue by asoldier** [cadon/ARKStatsExtractor#357]
Here you go: 

![image](https://user-images.githubusercontent.com/4536972/27460989-8edf2eb6-5785-11e7-9b6d-053eadeae2d1.png)

(90%) Rex stat breaks everything, including my brain.

**Comment by lnewlfe** [comment]
Its happening to my server as well. Running the rex seems to be unaffected tho, I am wondering if its just a display bug with 259. You find the speed has dropped?

**Comment by Uvarx** [comment]
Am having the same issue on my server. Is there anyway to manually input animal stats into the library as a temporary work around till its fixed? as I can't add any new re's to my library atm

**Comment by KJTau** [comment]
I am also having this issue on my server with two rex I just tamed, as well as two sabertooth (posted an issue on the sabertooth).

**Comment by lnewlfe** [comment]
I feel they are nerfing the rex but boosting the carno. Mine is inputted correct stat wise, but its actually 15% higher now in game. Anyone else getting this?

**Comment by asoldier** [comment]
Well, at least I know I'm not insane.

**Comment by timegrinder** [comment]
Hey everyone,

While I'm not the developer, the answer to the issue is just in that the ARK dev's changed the base stats / wild level amounts of a bunch of dinosaurs in the 259 patch and cadon hasn't managed to update the JSON records for the program to match yet, so my answer to these temporarily is to take screenshots of any dinosaurs (or just write a list of which ones you can't add yet) and then once the program is updated, either go through and add the list of dinosaurs or just extract the stats from the screenshots you've taken.

Even if you were able to manually input the stats into the library it still wouldn't have the extracted levels, so you'd need to re-edit them and extract anyway at a later time in order to get the proper breeding data.

**Comment by cadon** [comment]
Hi everyone, the new update with the new stat-values is released (0.23.8), the extraction should work again. Keep in mind the Rex is now called Tyrannosaurus.

**Comment by KJTau** [comment]
@cadon Did you mean to update Rex to Tyrannosaurus in the app? It still reads as Rex and I'm not seeing a separate option of Tyrannosaurus.

**Comment by cadon** [comment]
Did you download 0.23.8 yet? "Rex" should be replaced by "Tyrannosaurus".

**Comment by KJTau** [comment]
Ahh, yes. I'm sorry for the hasty reply! It seems the problem was on my end. Downloaded and extracted the new version but it was failing to replace the older files on my system. Problem solved, thanks!
