### ISSUE TITLE
Keeps selecting Bred dino...

### ISSUE THREAD

**Issue by DeOrthodox** [cadon/ARKStatsExtractor#364]
Ok no matter what dino it is when i try to extract the stats from the dino it just keep selecting the bred option.... 

no matter if i press wild or tamed it reverts back to bred... no idea why so pls help!

**Comment by cadon** [comment]
Hi, can you describe more precisely when the bred-option is selected? Is it after you clicked on the button "Extract Level Distribution" or after you clicked on "Read Values from ARK". Also please attach a screenshot of the inventory of the creature you try to extract.

**Comment by DeOrthodox** [comment]
![adsdsasd](https://user-images.githubusercontent.com/20668976/27519413-f0755c7a-59f3-11e7-99df-a4a8b867c946.png)

Everytime i click read values from ark it goes to bred everytime. i dont know why it does this... ive tried getting a new file from github but still does the same thing. if i have wild selected and press read values from ark. it reads them and select bred, same with tamed

**Comment by cadon** [comment]
In this case the issue is, that the total level is not put in.
The application assumes a creature is bred if it can recognize a value for imprinting. In this case a number for the imprinting was recognized falsely, I'll increase the threshold a bit, so that should happen only rarely. Also the reader has issues with long dino-names, which causes the font to get smaller.

**Comment by DeOrthodox** [comment]
is there anything i can do on my end to get it to work?

**Comment by cadon** [comment]
Just enter the level manually before extracting.
