### ISSUE TITLE
Setup multipliers with Enabled Single player settings (patch 259)

### ISSUE THREAD

**Issue by rangerrambo** [cadon/ARKStatsExtractor#367]
Hello!

First of all great app.

I was wondering if I could get some guidance on how to set up the multipliers in the app with the new SIngle player settings.

I was able to find some info that I ll post below, but not sure how to add these or multiply. Any insight would be extremely helpful!

**Is this pretty much just putting 0.55 instead of 0.14 for  dinotamed add? for health and damage and similarly for other factors?**  

From: https://survivetheark.com/index.php?/forums/topic/203535-patch-259-hibernation-single-player-settings/

and 
https://steamcommunity.com/app/346110/discussions/0/1368380934243880256/#c1368380934245343160
```
[ServerSettings]
DifficultyOffset=0.200000
XPMultiplier=2.000000
TamingSpeedMultiplier=2.50000
ServerCrosshair=True
ShowMapPlayerLocation=True
EnablePvPGamma=True
AllowFlyerCarryPvE=True

[/script/shootergame.shootergamemode]
PerLevelStatsMultiplier_DinoTamed[0]=0.450000
PerLevelStatsMultiplier_DinoTamed[8]=0.415000
PerLevelStatsMultiplier_DinoTamed_Add[0]=0.550000
PerLevelStatsMultiplier_DinoTamed_Add[8]=0.550000
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=1.000000
MatingIntervalMultiplier=0.125000
EggHatchSpeedMultiplier=10.000000
BabyMatureSpeedMultiplier=36.799000
BabyCuddleIntervalMultiplier=0.167000
bFlyerPlatformAllowUnalignedDinoBasing=False
bAllowCustomRecipes=True
bPassiveDefensesDamageRiderlessDinos=True
MaxDifficulty=False
bUseSingleplayerSettings=True
```

**Comment by cadon** [comment]
Hi, thanks for posting this, I already wondered why the singleplayer changed. Yes, just change the appropriate settings. Even easier is to drag&drop the settings-file on the settings-window, then all values are entered automatically from that file.

**Comment by LordWex** [comment]
Problem with that is the 3 decimal point placement on PerLevelStatsMultiplier_DinoTamed[8] - unfortunately the multiplier page of the program keeps rounding the value up to 0.42 instead of 0.415 and has been leading to errors in the calculations.

**Comment by rangerrambo** [comment]
Changed the settings accordingly, but as LordWex pointed out not having 3 decimals seems to be the problem now. Looking forward to the update!

**Comment by cadon** [comment]
0.23.9 is released with support for 3 decimal places for the multipliers, also a button to automatically set the multipliers to the default SP-values. In my tests it seemed the HP-tamedLevel is 0.425 instead of the posted 0.45. If you see other discrepancies of the default-values, let me know.

**Comment by BillyHalley** [comment]
Hi, I think I'm having the same issue in single player, I adjusted the settings accordingly ( I dragged GameUserSettings.ini on the settings window )
But I can't manage to extract dino stats
![screenshot 8](https://user-images.githubusercontent.com/6708704/27709596-fcc6cdde-5d1c-11e7-8c0a-79e9dde79d4e.png)
![screenshot 7](https://user-images.githubusercontent.com/6708704/27709605-07f0c278-5d1d-11e7-89a5-6bd8fef08dfc.png)
![wild](https://user-images.githubusercontent.com/6708704/27709619-123a42f4-5d1d-11e7-8313-1bbb0350bfb4.PNG)![aff](https://user-images.githubusercontent.com/6708704/27709616-122fc57c-5d1d-11e7-8335-e1ca2d263867.PNG)
![tame](https://user-images.githubusercontent.com/6708704/27709617-12359e5c-5d1d-11e7-9ad1-6f3d927561b5.PNG)![add](https://user-images.githubusercontent.com/6708704/27709618-123743e2-5d1d-11e7-9aff-f422f3ae21cd.PNG)



I actually already extracted that argy while it was unconscious and it worked, i'll post a screenshot, maybe it can help figure out what values are wrong

![argy](https://user-images.githubusercontent.com/6708704/27709658-361dde42-5d1d-11e7-9902-5b25a5ceffb5.PNG)

Sorry for the long post due to screenshots

**Comment by cadon** [comment]
Hi @BillyHalley, it seems these values are outdated, they are not possible with your multipliers. The game sometimes needs some time (up to a day) to recalculate the values, sometimes only a levelup forces a refresh of the values. You can try to level up HP once, maybe it solves the issue.

**Comment by BillyHalley** [comment]
Thanks, I'll try it when I get home.
Pretty weird bug if they can't update stats properly

**Comment by cadon** [comment]
Option with default-SP-setting is added to the options.

**Comment by rangerrambo** [comment]
Thanks! Wasn't able to get much Ark time, but from some limited testing everything works fine!
