### ISSUE TITLE
Can't put Stats dinos in it

### ISSUE THREAD

**Issue by golfmostique** [cadon/ARKStatsExtractor#371]
My Quetz
lv 321 Male
HP : 13708.9
stamina : 2560
Oxy : 885
Food : 7286.4
Weight : 6748.8
DMG : 390.4
Spd : 136.5
Trop : 37651.7
100% imprint

after put stats and double check all still red tab

**Comment by cadon** [comment]
100% imprinted creatures sometimes fail because the tool adjusts the imprinting to the next possible value. This is necessary for all imprinting-values, except with 100%, where sometimes it is really 100%. To disable the adjusting, go to the settings and uncheck "Ajdust to possible imprinting" for this extraction. For creatures with imprinting lower than 100% you have to enable this again. It's planned to make this easier in a future release.
