### ISSUE TITLE
Saber & Rex red speed since 260(.1)

### ISSUE THREAD

**Issue by KJTau** [cadon/ARKStatsExtractor#373]
Since either 260 or 260.1, whenever I attempt to enter new Sabers and Rexes, their speed comes up red. So far, only seen this with wild tames (haven't added any new babies this week).

I do have "Classic Flyers" on my server, and I do have the .json for it loaded into my breeding app.

I am not sure if my rexes having 100.0 base speed again is Classic Flyers, or the latest patch - I have not leveled speed in them whatsoever. 

![rex_red_260](https://user-images.githubusercontent.com/29648686/27758666-f5e663f0-5dce-11e7-9d39-3dc6cf10ca59.png)
![rex_red_260_ingame](https://user-images.githubusercontent.com/29648686/27758665-f5e0d138-5dce-11e7-9ff2-4e88dcd4e618.png)

**Comment by dcuoperv** [comment]
Babies also birth at 100% on rex's now. I don't have classic flyers on my server so it's definitely a 260 patch change. Wish they'd just leave the speeds alone for once.

**Comment by KJTau** [comment]
Alright, I thought I was losing my mind looking at a rex and seeing their speed go back up to 100.0% from 90%. The rex posted here is a wild tame, if that matters to the bug report.

I poured through patch 260's notes and didn't see a thing about them changing speeds - I agree they should either back off or document it better.

**Comment by dcuoperv** [comment]
Yes. An example of the change would be this. A birthed rex from just before the patch:

![asb-stats](https://user-images.githubusercontent.com/29808722/27760816-bf233792-5e93-11e7-9ff9-359fff583048.JPG)

Stats on that rex are now
![rexstats](https://user-images.githubusercontent.com/29808722/27760818-c9529c30-5e93-11e7-8880-ee8189fc8935.JPG)

So when you do a new rex (like I tried to an hour or 2 ago, you put in 120% and it gives a red readout, because the values for non-imprint and imprint are now 100 and 120, rather than 90 and 110.

**Comment by KJTau** [comment]
Awesome, thanks for explaining! That makes sense.

**Comment by cadon** [comment]
New version with the new speed-values is released.
