### ISSUE TITLE
Not sure why this is wrong

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#378]
The stats extracted right, yet they create was a level 203 wild and not a 204.
![capture](https://user-images.githubusercontent.com/1366816/27934329-8cbf4544-62e8-11e7-96d9-051f50761e13.PNG)

**Comment by cadon** [comment]
Hi, that's a rounding error, in this case the calcultated wild-level is just a fraction too high and displays as 204, when the true wild level is indeed 203. It's caused by the extracted taming effectiveness, which is calculated as 98.52%, when in reality it's rather around 98.54%, both being displayed as 98.5%.

You can adjust the taming-effectiveness by right-clicking on the creature in the library, choose edit and set the taming-effectiveness to 98.54%, this will fix the wild-level. You can enter this value even if the input will only accept one decimal place, internally the more precise value is used.

I'll add it as a feature-request to handle these cases more easily.

**Comment by cyberangel67** [comment]
IS it a rounding error just for this Dino then?

**Comment by cadon** [comment]
This rounding error can happen to all dinos, it's not specifically only the hyaenodons. This case is probably very rare, I guess at most 1 in 40 extraction does this happen, and it's only one level off the true wild-level.

**Comment by cyberangel67** [comment]
Ok, that explains why it is only happening with the 203 hyaenodons then, as 210 and 196 all worked good, but all 203's where 204's

**Comment by VolatilePulse** [comment]
Previous fixes to the extractor and enhancements have made the TE and Wild Level calculations slightly more accurate. While it may not be 100% accurate still, most users will not encounter the edge cases.
