### ISSUE TITLE
2 Red bars for Pteranodon

### ISSUE THREAD

**Issue by PachytheDino** [cadon/ARKStatsExtractor#379]
![help 1](https://user-images.githubusercontent.com/29826092/27986967-8835ef90-63d4-11e7-970a-cea24a785e7a.jpg)
![help 2](https://user-images.githubusercontent.com/29826092/27986968-89f91de8-63d4-11e7-8311-196c73d5e3f2.jpg)

**Comment by cadon** [comment]
Hi, it seems the multipliers are not correct. Do other species / creatures work? If not, make sure all stat-multipliers are correct.

**Comment by PachytheDino** [comment]
Yes they do.

**Comment by PachytheDino** [comment]
and they are correct. Im playing with 4 taming speed

**Comment by cadon** [comment]
Is the total level correct? Are you sure the TE is above 80%? Try to lower the lower limit, 71.3% seems to yield some better values. Did you level oxygen or weight? Are you using the classic-flyers-mod? Did you change the stat-multipliers since this ptera was tamed? You can try to level up a stat that is not working, that might trigger a recalculation ingame.

**Comment by PachytheDino** [comment]
Well it died. But I got other creatures with red so let me test your suggestions

**Comment by PachytheDino** [comment]
Got a new one and it red bars only on damage and I have checked everything and done everything. No change.

**Comment by cadon** [comment]
Hi, found the reason for the errors: the single-player default stat-multipliers changed. Set HP tameAdd to 0.5, HP tameLevel to 0.425, Dmg tameAdd to 0.5 and Dmg tameLevel to 0.4
I'll update these new default multipliers in the next release, until then you can just adjust them manually.
