### ISSUE TITLE
Extractor not working for any creatures

### ISSUE THREAD

**Issue by zoidbirk** [cadon/ARKStatsExtractor#399]
Every creature that I use the extractor on has at least 1 problem extracting, as well as problems with the taming effectiveness range.
E.g
![image](https://user-images.githubusercontent.com/30318916/28419128-054ee1d2-6d56-11e7-9cab-02e123eb19e6.png)

**Comment by Simpleskill** [comment]
i also have problems with this app
you are on a official?

**Comment by cadon** [comment]
Hi @zoidbirk, the reason are some changed stat-multipliers for the singleplayer-settings. It'll be fixed in the next release, until then you can adjust it manually in the settings, set HP tameAdd to 0.5, HP tameLevel to 0.425, Dmg tameAdd to 0.5 and Dmg tameLevel to 0.4.

Hi @Simpleskill, better open an own thread with your issue, along with the stat-multipliers you're using and a screenshot of the inventory of the creature that doesn't work.
