### ISSUE TITLE
Parasaur Baby

### ISSUE THREAD

**Issue by smeezer** [cadon/ARKStatsExtractor#4]
Hi, all of the stats except damage seem to calculate correctly.  My base percentage is 138.6 and based on the wiki, base damage is 10 so I entered 13.86 which got rounded up to 13.9.  Both 14 and 13.8 don't work either.  Shows up red no matter how I figure what the number should be.
![weird](https://cloud.githubusercontent.com/assets/16647156/12232506/f5f0b8b2-b813-11e5-839a-fc12380aad3e.jpg)

**Comment by smeezer** [comment]
Also, attempting to enter the damage as the percent number aka 138.6 also registers TE differs

**Comment by cadon** [comment]
Hi,
you don't have to convert the damage to its absolute value, the percent-value that you can see ingame is the value you have to enter. I make this clearer in the next version.

Right now the game gets heavy balancing, and the numbers change nearly every patch, so the tool might not work right now.

**Comment by smeezer** [comment]
Is there somewhere I can find the numbers to help you out? Will the parents stats help?

**Comment by smeezer** [comment]
I think the easiest way of denoting how to enter the stats would be for the percentage based stats, to put (%) beside the row name. Simple and elegant.

**Comment by cadon** [comment]
The numbers can be found in the dev-kit, which is not yet updated to the current version of the game. Extracting the numbers from the game is theoretically possible but probably not exact and would take a long time. Thanks for your help, but the best at the moment is to just wait for the devkit update.

I've added a %-sign to the damage and speed row, will be included in the next version of the tool.

**Comment by smeezer** [comment]
Cool, Thanks for getting back to me right away, that's awesome.

**Comment by smeezer** [comment]
![weird2](https://cloud.githubusercontent.com/assets/16647156/12233076/e2e279cc-b818-11e5-9155-9512c1f54efc.jpg)
This is interesting, if I uncheck Bred Creature the checksum seems to add up fine, is there a reason for that or am I missing something or both?

**Comment by smeezer** [comment]
![2016-01-11_00004](https://cloud.githubusercontent.com/assets/16647156/12233237/550cc902-b81a-11e5-8975-54cf7ad6acb9.jpg)

**Comment by smeezer** [comment]
![2016-01-11_00005](https://cloud.githubusercontent.com/assets/16647156/12233631/434796e0-b81d-11e5-8ce0-5aab7f86c2b2.jpg)
Juvenile stats - No change

**Comment by cadon** [comment]
Despite all fields are green, these are probably not the correct stats, because the multipliers have changed. The tool tries to find a combination that fits for all given values and it happens to exist such a combination, despite the multipliers are off. It could be by chance that the levelups are the correct ones, but don't expect them to be correct.

The stats of a growing creature will not change until it's grown-up and you spend a levelup in a stat. An exception is the amount the creature can carry and the health points it can have, but the final value can be always seen in the stat-list on the right.

Right now the tool is useless. You can try to figure the exact values after the last [patches](http://steamcommunity.com/app/346110/discussions/0/594820656447032287/) and change the according values in the files stats.txt and settings.txt, but as said before, this will probably not exact enough without knowing the values from the devkit.

**Comment by smeezer** [comment]
Ok cool,

**Comment by cadon** [comment]
new version with %-sign is released.
