### ISSUE TITLE
Name Generation Pattern

### ISSUE THREAD

**Issue by nlappet** [cadon/ARKStatsExtractor#417]
Hey,

I was wondering if we could get more options than just the 3 currently, like one for each stats wild level.

Thanks :)

**Comment by Worldgate** [comment]
Is there a way to change what the name generation will be?  We have taken to naming dinos based on their colors since we just breed them and sell them, no need to have a name for them all since their going out the door at some point.

**Comment by nlappet** [comment]
Yes, its in the options in General section. Currently you can only use {sex} (gives species gender)  {sex_short} (give species sex with 1 letter, e.g F for female) {species} (gives the dino species) and {n} (gives a number to the dino so you can't have the same name on two)

So, lets say you have two female rexes and have a name generation pattern of {sex} {n} {species} you'd get Female 1 Rex and Female 2 Rex names.

What I was hoping for is having options such as the wild levels of a dino (because these are what matter for breeding) so that I could have it auto generate names with the gender and stats directly in the name. Like F1 40/40/45/37/49/27/48. 

I tried to do it myself but just couldn't get the reference right (or didn't find the right place), gotta re-learn coding >_<

**Comment by cadon** [comment]
This feature will be extended in the next release (thanks to @DNAofDeath), here's a preview what keywords will be available: https://github.com/cadon/ARKStatsExtractor/wiki/Name-Generator

**Comment by Worldgate** [comment]
Thats going to help a lot with managing huge herds of dinos.  We got some we use for colors only, but then there is the new batch im taming because i want to get my own colors and not have 120k mutations.  (I can screenshot it, its for realz).

However, is there an option for text thats already there to be appended to?  For example, I have say 2 rexs that are Red F1 and Red F2, if I put just Red could it put F3 automatically when i hit the name generator?  It just be quality of life really.

**Comment by cadon** [comment]
New version with more key-words is released.
@Worldgate, you can use the pattern `Red F{n}` for this. The `{n}` is replaced by the smallest number that makes the name unique.
