### ISSUE TITLE
Dom-Lvl? What is that?

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#418]
So one thing that has been confusion me to no end. What is a Dom-Lev? 
I got myself two whales that came with a few levels into them and I have a Dom-Lev value added. I'm assuming this is to tell me how many levels got put into the stat? So, should I set these to zero to get the base stats for the breeding lines or? No idea how much these level ups would be effecting the stats shown.

http://i.imgur.com/5H6COSe.png
one of the two

http://i.imgur.com/dtYVDig.png
both of them, the other it can't seem to assume its taming lv?

How well can these stats be trusted?

**Comment by cadon** [comment]
Hi, the tester is not made to test stat-values with given levels, if you don't know the levels, you should use the extractor. A dom-lvl, or domesticated level, is a level applied by a player. The breeding-planner only considers the wild-levels, because the dom-levels are not used in breeding.

You can trust the extracted levels if all stats are showing green after the extraction. If a stat is yelloe, there are multiple possibilities for that stat.

**Comment by Taiine** [comment]
Well I used the extractor first, the tester is what comes up when I go to edit something, like the dino name. I wasn't sure what a dom level was as there's nothing on it in any video or documentation, it also feels to be off with how many levels really were put into it.

**Comment by cadon** [comment]
If the creature was extracted like this, the domesticated levels are correct, it wouldn't be a successful extraction else. Also the XP tells that the creature has 43 levelups, so it's probably correct.

**Comment by cadon** [comment]
I added a tooltip in the newest version, it should make it clearer what these abbreviations stand for.
