### ISSUE TITLE
Unable to add Wyvern to library, Dmg in Red.

### ISSUE THREAD

**Issue by MutantRex2** [cadon/ARKStatsExtractor#429]
Server settings are loaded in correctly. Server has had a restart. Numbers in the app have been entered manually. Imprint is at 100%.
I checked the online-help section.

How can I fix this?

Thanks,
Rex

![capture](https://user-images.githubusercontent.com/29512875/29092589-b5e686f0-7c3b-11e7-9dc7-8cfe1150d4cf.PNG)
![capture](https://user-images.githubusercontent.com/29512875/29092605-c49ea754-7c3b-11e7-9054-a8f68037217d.PNG)

**Comment by cadon** [comment]
Hi, what are your multipliers?

**Comment by MutantRex2** [comment]
![capture](https://user-images.githubusercontent.com/29512875/29095044-6ba3281a-7c44-11e7-94ec-8aeed017b4ba.PNG)

**Comment by gmmedia** [comment]
I have the same problem since today. Same with the Giga.
The Melee Damage is always red.

I add the settings for the Giga:
![giga-server](https://user-images.githubusercontent.com/7474702/29172208-881d401a-7ddf-11e7-9f99-47d5fa2d10cc.jpg)
![giga-smart](https://user-images.githubusercontent.com/7474702/29172210-8823699a-7ddf-11e7-9707-84ce4713b00b.jpg)
![giga-stat](https://user-images.githubusercontent.com/7474702/29172209-881fe9b4-7ddf-11e7-9793-22fab1be5a34.jpg)

**Comment by cadon** [comment]
I finally found the issue, the fix is in the newest release (v0.23.14). Thanks for the reports.
