### ISSUE TITLE
Problems - I may be a pleb

### ISSUE THREAD

**Issue by anorth-uk** [cadon/ARKStatsExtractor#43]
Recently found your software and been having a play with it.

I don't seem to be able to get any Sabretooth to resolve with red entries, I've checked the settings and taming is at x50 which is correct.

I've attached the xml file rather than countless screen shots

Regards

Andrew
[TW Season 8 Breeding.zip](https://github.com/cadon/ARKStatsExtractor/files/257577/TW.Season.8.Breeding.zip)

**Comment by cadon** [comment]
Hi, I couldn't understand the file you sent me. Are the domesticated levels the stat-numbers of the creatures you tried to extract?
Do you have issues only with the sabertooths or also with other species?

**Comment by anorth-uk** [comment]
not sure now to your first question as I've been playing with so many dino's

Having problems with Terror Birds at the moment, just tamed a low level and getting red for a Health of 594.5

I may have to start from scratch with all new tames

**Comment by anorth-uk** [comment]
Here's a pdf of my Terror Birds, I'll have another play tomorrow on an Official Server and see if that works for me

[Dino Breeding Data - Terror Bird.pdf](https://github.com/cadon/ARKStatsExtractor/files/257937/Dino.Breeding.Data.-.Terror.Bird.pdf)

**Comment by anorth-uk** [comment]
Tried an Ank off the Official Server I play on, 120 perfect tame, original tamed stat's in the note (except Torpor)

![ank stats](https://cloud.githubusercontent.com/assets/19289799/15160317/ff9474f8-16f0-11e6-96f9-e2af4b4e7c5f.jpg)

**Comment by cadon** [comment]
Hi, the data of the terror birds in the pdf seems to have no decimal-numbers, the tool needs them to get the precise levels. I guess you have to reenter in the tool from the ingame values.

The Ankylo works fine for me. The numbers you put in the tool in the screenshot are the pre-tame-values, so the level has to be set to 120 and the radiobutton "wild" has to be checked instead the "tamed" one. Or you enter the current numbers (level 244, HP 4480.1 etc., which I recommend).

The Terror Bird with the HP of 594.5 seems to be from a server with non-official multipliers (e.g. the Tame-Add-multiplier is 1 instead of 0.14 which is set in the settings).

**Comment by anorth-uk** [comment]
looks like I was a pleb lol, I'll give it a go later

thanks for the help
