### ISSUE TITLE
Something has changed and reporting wrong values for taming

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#440]
I think I was about 2 or maybe 3 versions behind, but not 100% sure and when I looked at the taming on my settings the taming of a trike was sort of spot on. The issue was is said I would get a TE of 100% with Mejo but I got 95.5.

So a Level 250 trike was reported to come out as 374, in actual fact it came out at 368.

Now comes the major issue, the latest version update 5 minutes ago, as you can see by the screen shot the amount of Mejo's needed is way out by 800% or something and the TE is also way out at 50%, the trike was tamed at 95.5 with a 6 stat point loss and final tame of 368.

![capture](https://user-images.githubusercontent.com/1366816/29328701-d07318fc-8236-11e7-95da-d5208a8bd16c.PNG)

**Comment by cadon** [comment]
Thanks for the report. There was an issue that the event-multiplier (in your case 1.5 instead of the 30) was used. It's fixed in 0.23.14.

For the small error on the TE (95.5% instead of 100%), it could be the application has a rounding error, or the trike was hurt during the taming. If you see an error like this again, let me know

**Comment by cyberangel67** [comment]
Yeah I am not worried about the TE error as that was an older version of Smart Breeder.

But for the issue at hand, this is V0.23.14.1, so you're saying it is fixed? Doesn't look like it.

**Comment by cadon** [comment]
I made a typo, I meant it's fixed in 0.23.15.

**Comment by cyberangel67** [comment]
cheers
