### ISSUE TITLE
Mutation Count no longer working via extractor

### ISSUE THREAD

**Issue by defyreality** [cadon/ARKStatsExtractor#445]
previously, when adding a dino to the library via extractor, the mutation field would auto-populate with the mutation count from the parents. this is no longer happening.

**Comment by cadon** [comment]
After a parent is selected, the mutation-counter usually displays the sum of both parents. The counter will not be updated, if the mutation-counter was changed manually. This is because if the user inputs a value they want, it shouldn't change it. I'll change it in the next release, so after a manual change and a new extraction, the counter will be automatic again.
Until then, just save your library and restart the program / reload the library to make it automatic again.

**Comment by defyreality** [comment]
ah, that makes sense. i was adding 15-20 new dinos, and the first or second was a new color we picked up, so it had no parents in my library. so entered the mutations manually, and that probably started the whole thing.

**Comment by cadon** [comment]
Fix is released.
