### ISSUE TITLE
Maybe bug - advice?

### ISSUE THREAD

**Issue by valarhan** [cadon/ARKStatsExtractor#446]
Got a new 'corn.. app won't let me input it.
![image](https://user-images.githubusercontent.com/27072415/29567258-76a9d2b4-8701-11e7-881b-6834a9e34993.png)
A bit of background, I've tried entering it as 'not in event' and 'in event' with no success. I've also tried 'exact imprint percent' and 'not exact imprint percent (which bumps up the 52% to 55%)' also without success.
![image](https://user-images.githubusercontent.com/27072415/29567330-b368fc0c-8701-11e7-8610-644885309076.png)

**Comment by Celoain** [comment]
have you tried giving it one of these levels or waiting a while for the server to update the stats?
A server restart could also fix the issue if possible for you. Imprint sometimes takes a while on the server to update all stats.

**Comment by valarhan** [comment]
Official server (and I _think_) there was a reset last night. -And what do you mean by 'giving it one of these levels'? Do you mean distribute the lvls for xp?

**Comment by cadon** [comment]
You still have the "Exactly, don't adjust"-checkbox checked. You should never enable it, the only exception is if the creature has exactly 100% imprinting.

**Comment by valarhan** [comment]
In that screenshot I did, yes, but as I've said, I've tried to enter the info without having it checked and it won't go it. =)

**Comment by Celoain** [comment]
@valarhan I'll try to check the problem later tonight when i'm home as well. Maybe it's reproduceable.
@cadon Is that really the only use for the Checkbox? If so, wouldn't it help to reduce errors to handle the 100% being exact in the code and not showing it to the user at all?

**Comment by cadon** [comment]
Hi @valarhan, it's exactly the same issue you had in #375. There the solution was to set the cuddleInterval to 0.5. It works fine here as well. Either there was an event going on like @Celoain said, or the multipliers on your server are different in generell.

Hi @Celoain, this checkbox is indeed for most people only needed in the case of exactly 100% imprinting. The game does only show rounded values, so if the game shows 52% like in this example, the true value is 51.84% (if this number is entered, the checkbox can be enabled to make it work, too). The exact number depends on the cuddleInterval and the matureSpeed. If a creature gains 7% per cuddle, and it has 98% imprinting after 14 cuddles, and the last cuddle is applied, it has 100% (it's capped). In other cases it could be, that the imprinting shows 100%, but the true number is 99.6%. In the first case (true 100%), the checkbox has to be checked, in the second case (true 99.6%), the checkbox must not be checked.

At first this setting was hidden in the settings-window, but users asked to make that checkbox easier accessible, e.g. if an admin sets the imprinting to an otherwise not possible number of e.g. exactly 50%. The tooltip also says it should be checked only if the imprinting is exactly 100%, as this is the only scenario that checkbox is relevant, for most of the users.

**Comment by valarhan** [comment]
Well, I don't know what's changed, but I tried entering it again - after confirming the settings (which I had not changed since the last time I struggled to enter a dino) took a screenshot of them, ticked off the "Event" option (as I'd done in the past) and entered the values, and IN it went.. So I'm at a loss, I'm glad though, that I only said it MIGHT be a bug - cause either this was a bug on user side, or ARK side, and not on your app. -shrugs- Whatever, it's in now, and away I go -- thanks for the help, again. =)
