### ISSUE TITLE
So, I found a Broken Castoroides

### ISSUE THREAD

**Issue by iPoisnCake** [cadon/ARKStatsExtractor#451]
Just found this wild 150 male Casteroides and it has spent too many points in Oxy.
The server I'm on doesn't have any mod install that affects stats, just a few building mods.
Needless to say the extractor is throwing a fit. Is there anything I can do to fix it?
I can't add him to my library.

Before taming:
![shootergame_2017-08-31_08-39-50](https://user-images.githubusercontent.com/12545910/29912817-e976ea86-8e2a-11e7-9c90-09cef29becd5.png)

After taming:
![shootergame_2017-08-31_09-00-22](https://user-images.githubusercontent.com/12545910/29912819-eb30862a-8e2a-11e7-9cf4-c682cb158b78.png)

**Comment by TomZandt** [comment]
I am also having this issue:
![image](https://user-images.githubusercontent.com/22413477/29924717-c821a774-8e55-11e7-9aba-97a40f227600.png)

Any Ideas, really want it added :)

**Comment by thor79** [comment]
Just tamed a new Beaver, Male 150, 99% taming efficiency with a Kibble Tame. The extractor is rejecting O2, but also has put no points into Speed. The actual values, as provided by Super Spyglass (I don't know if they are totally accurate) are also posted here. Being able to manually enter a dino, adjust wild levels if we know them, would be really useful. Obviously basic checks like if the point values add up, should still be done, but otherwise we shouldn't have to be stopped because the program can't interpret the numbers correctly.
![image](https://user-images.githubusercontent.com/299155/29927485-1f0fad62-8e2c-11e7-9e9f-eca9342f253b.png)
![image](https://user-images.githubusercontent.com/299155/29927493-25236d10-8e2c-11e7-825e-4140a9887f1b.png)
![image](https://user-images.githubusercontent.com/299155/29927505-2c2a62c6-8e2c-11e7-9210-8e03068ff743.png)
![image](https://user-images.githubusercontent.com/299155/29927512-3202a924-8e2c-11e7-9d8d-c7f02027e744.png)

**Comment by cadon** [comment]
Hi @iPoisnCake, @TomZandt, and @thor79, thanks for the reports. The oxygen for the beaver was changed, I uploaded the new values. You can get them by clicking on ? -> Check for Updates in the menu-bar. Also, the otter was added.
