### ISSUE TITLE
OCR for 3440x1440

### ISSUE THREAD

**Issue by WarBird25** [cadon/ARKStatsExtractor#467]
Thanks for this program. I now use it for breeding a few creatures, but always switched my resolution to 1920x1080 for reading the stats, which was annoying. After a short research I found the help to setup OCR for my 3440x1440 resolution and worked on it.
Unfortunately the OCR wiki page (https://github.com/cadon/ARKStatsExtractor/wiki/OCR) is not clear on some things. I was able to config the OCR to read all my stat values (numbers) correct, but I have a problem reading letters. 
@cadon can you please anwer to following questions and maybe add some of those to the wiki page:
1) I setup the OCR fields, so the field lines up on the top with the highest character. Is that correct/a good way?
2) As soon as I set the OCR fields to line up with the characters at the bottom, OCR was not able to read anything. I added about 2 to 3 pixel and it worked. Did I do someting wrong or is it the way to go?
3) What need to be read by the OCR fields? For stats the current/max (eg: 3210/3410)? For level only the level numbers or including "LEVEL"?
4) Reading the "LEVEL" always ends up as "15"and other numbers, also when setting templates for the characters. Is reading "LEVEL" important or only the number? If it is, any tips to improve reading letters?
5) The imprinting stat is not always present, so I guess it doesn't matter if there is a read error?
6) Should the sex symbol be included in the name field and recognised by the OCR?

I appreciate any help and will provide my OCR file if I am able to finish it.

**Comment by cadon** [comment]
Hi, thanks for the feedback! I updated the wiki-page. In short

1. That's a good start. After the first OCR, check some characters and see if the template has the same vertical-location and adjust the labels accordingly.
2. Sounds good. Just repeat adjusting until you get good results.
3. Capture all of the "1234/5678". Only the last number will be considered later. Capture all of "LEVEL: 123", everything preceding the colon and the colon will be ignored. This text is centered, so the horizontal position of "LEVEL:" will change dependant on the number of digits of the level.
4. The letters will be ignored, also see 3.
5. If not present, it's ignored.
6. Yes. You have to define the character for the sexsymbol. See https://github.com/cadon/ARKStatsExtractor/wiki/OCR for more infos (I added it there).

Thanks for sharing the file once finished, I'll be happy to include it in the next releases then.

**Comment by WarBird25** [comment]
Thank you for the answers and thanks for updateing the wiki page!

Importing stat values works for about 98%, but recognition of letters is a pain. Sometimes OCR cuts where no space is, eg "K" is read as I and C, or level "255" gets "25.5", is there a way to prevent that?
What makes it hard is that Ark scales NameSpecies by the name length.
The sex symbol is also recognised as many symbols. I set the one most recognisable as ♀ to read ♀, which works. For "♀|ABCDE" OCR reads " I♀|ABCDE" but the application does not detect the sex. Is it required to have the ♀ at the beginning of the string?

**Comment by jwvanderbeck** [comment]
[ocr_2560x1440.json.txt](https://github.com/cadon/ARKStatsExtractor/files/1301697/ocr_2560x1440.json.txt)
Getting the "Level" field right is definitely a real challenge.  For the longest time it would just throw the "can't read" error, which sucks because when it does that you can't even see what it thought it got so you can tweak it.

Anyway I finally did manage to get it to work in my case.  I found that it actually *doesn't* matter if it ever sees the word "LEVEL".  I couldn't get it to read that, it would always show up as some form of 15 like @WarBird25 says.  But it turns out it doesn't matter **as long as the colon is seen**.

The other issue I kept having was it confusing the comma with the decimal point.  Again turns out it doesn't matter, since it looks like the software is smart enough to deal with that.

I guess what I'm trying to say here for others as a suggestion is don't get hung up on perfect recognition in the Output tab.  If you got it close, with at least the right letters and numbers showing up where it matters, then try it in the actual app and you might find you are good.

To show an example here is what my output tab looks like.  Pretty messy in some cases.  But it works.

    Health: 2255.4/2255.4
    Stamina: 2040,0/2040,0
    Oxygen: 555,0/555,0
    Food: 4410,7/4412,8
    Weight: 45,2/472,3
    MeleeDamage: 359,9%,
    MovementSpeed: 150.0%,
    Torpor: 0,0/1402,1
    Level: 1:,51/5:::228
    NameSpecies: ♀|FLYER|(Pteranodon)
    Tribe: Avengers


After about an hour playing with this I seem to have decent accuracy with my monitor resolution of 2560x1440, so I will attach the file here (assuming I saved it properly).

**note** I added the ".txt" extension onto the json file so Github would let me attach it.  You need to remove that.

**Comment by cadon** [comment]
Hi @jwvanderbeck , thanks a lot for that file, I'll add it to the next release.
You're right, the output only shows the data the OCR has recognized, but this data is further processed (e.g. commas are converted to dots etc.). Regarding the level, if the output tells "can't read", that means it literally couldn't read anything. The "LEVEL" part should be included in the reading-label, because dependant on the digits of the level, the position changes. Everything before the colon and the colon itself is ignored anyway (but as said, everything the OCR reads is displayed in the output, but later this data is processed and cleaned up).

**Comment by WarBird25** [comment]
@jwvanderbeck Thank you for sharing the file. I used your file and adjusted the fields x-positions. 
Your OCR works much better than my try and you are correct, the result in the application is better than the output of OCR. Some numbers (and letters) need to be relearned.
@jwvanderbeck, if you don't mind I will use your OCR file with my adjustments.

Will do the adjustments this weekend and hope to provide my file at the start of next week.

**Comment by WarBird25** [comment]
@jwvanderbeck I just want to give you a few recommandations to improve on your file:
- The level field is a little bit small. It has the length of a 3 digit level, but some might also have dinos with higher level than 999
- I would cover the whole length of the middle info-screen for Tribe and Owner
- Adjusting your fields the MovementSpeed field included the "ed" of the stat name, which is mostly recognised as 80. I would suggest to decrease the length of the stat fields (or at least the one for movement speed)


@cadon: While testing a few dinos I scanned a Dire Bear. OCR Read it without a problem as "DireBear", but the application selected Dire Polar Bear. Reapeating the scann serveral times (OCR always reading "DireBear") lets the selected Dino jump between Dire Bear and Dire Polar Bear. The same happend when scanning a Dire Polar Bear (OCR reading "DirePoiarBear").

**Comment by cadon** [comment]
@WarBird25 thanks for this note, I realised the Dire Polar Bear cannot be tamed anyway, so I'll remove it from the values.json with the next update, that should fix it.

**Comment by WarBird25** [comment]
@cadon the Dire Polar Bear can be tamed, I tamed two myself. It's just a Dire Bear with different name (same stats). Please don't remove the Dire Polar Bear ;-)

**Comment by cadon** [comment]
Oh, good you say it. I misunderstood the wiki regarding the taming, they are only untamable in the ice-cave. I'll keep them and solve the issue in another way.

**Comment by WarBird25** [comment]
[ocr_3440x1440_100.json.txt](https://github.com/cadon/ARKStatsExtractor/files/1315919/ocr_3440x1440_100.json.txt)
Here is my OCR file. If I change anything I will send you the updated version

**Comment by cadon** [comment]
The file was included in the latest release. Thanks for creating it!
