### ISSUE TITLE
Difficulty with Imprinted Equus

### ISSUE THREAD

**Issue by DJtheParasaur** [cadon/ARKStatsExtractor#471]
I know this is definitely something I'm doing wrong, but I cannot get this to extract imprinted Equus to save my life (or imprinted anything else). When I add in the imprinting percentage it changes to something WAY off and then I get this result. Any ideas?

Unofficial 
![smart breeder imprinting png](https://user-images.githubusercontent.com/32028564/30518180-25b34460-9b44-11e7-9200-15cd4c211aa0.jpg)

**Comment by cadon** [comment]
Hi, this issue could be related to the cuddleGracePeriod and cuddleLoseImprintQualitySpeed multipliers. If your server has this imprinting-loss, it can be very difficult to extract the levels. It's recommend to extract the creatures before you start the imprinting (i.e. right after hatching). You can try to extract it with the checkbox "Exactly, don't adjust" right under the imprinting-quality-input. You may have to try a lot of numbers in the range of 27.5 to 28.4999999 (i.e. all numbers that are rounded to 28, which is what is shown ingame). The bad news is, in your case it seems that won't work, because some stats don't yet have got the imprinting-bonus four times, e.g. I think food has only gotten it twice. This resolves itself after a restart or some time. My advice for this particular horse is, imprint it until it's fully grown, then wait for a day or two, enter the numbers again and test with some imprinting-bonus-numbers. You can use the Tester for this, just increase the wild-level until you are close, then adjust the imprinting-bonus until you match the exact number.

**Comment by DJtheParasaur** [comment]
You are beautiful. Thank you for the response. I'll share it with my fellow breeders from my server and start trying to implement your possible fixes for the existing dinos.
