### ISSUE TITLE
Rex input error

### ISSUE THREAD

**Issue by Leika199** [cadon/ARKStatsExtractor#484]
Hi,
I seem to have alot of trouble inputing stat data if I don't input straight away after hatching.  Attached is a screenshot of a rex baby at 13% imprint, couldn't input stats until now, and I can't seem to input this whole batch of rexes.  Can you see anything that I'm doing wrong?  I've selected the exact imprint checkbox, because having it unchecked seems to make things worse.  Cheers :)

![rexapperror](https://user-images.githubusercontent.com/32389568/31014202-0d4dfd84-a55d-11e7-8f0e-3d22277e0a49.jpg)

**Comment by cadon** [comment]
Hi, you have to uncheck the exactly-checkbox, check it only if you have exactly 100% imprinting or if you use mods. In all other cases checking it will prevent a valid extraction.

The issue is probably that you're using a version that was released nearly 3 months ago, and some of the values have changed since then ingame. There should have been a notice that a new version was released, if not, you can click on ? -> Check for Updates to get the latest version.

**Comment by Leika199** [comment]
Thanks.  I've updated the app and it's now working for a few more rexes.  Not all, but I can definitely live with that :)
