### ISSUE TITLE
Issues when breading (imprinting) an Argentavis

### ISSUE THREAD

**Issue by belpmx** [cadon/ARKStatsExtractor#493]
Bassically:
1. Breed and Argentavis and save the initial stats and it was success to be added to the library
2. When Argentavis  grow up and gain some skills via imprented value, it was two times for affection each one of 44%.
3. I had already check up the config file of the game and verify that Extractor has the same values.

Issue: I am not able to save the Argentavis  once that is full grow up.

You can see the full details on the attached PDF.

[Explain issues.pdf](https://github.com/cadon/ARKStatsExtractor/files/1354404/Explain.issues.pdf)

**Comment by LupaPup** [comment]
Imprinting stats do not count for breeding, you need to use the original stats as far as I am aware.

**Comment by cadon** [comment]
Hi, you didn't post your stat-multipliers, so I can't help you with the extraction issue.

The OCR-issue (that more than the necessary number is read) is caused by a too large label. You can adjust that if you go to the "Experimental OCR"-tab. There you have to enable the "Enable Logging and Editing"-checkbox in the Output-tab and perform a Read Values from ARK. Then the read screenshot should apear. Then go to the Labels-tab and select the MeleeDamage-entry. Decrease the "Width-L"-value until the description "... A Cuerpo" isn't included anymore in the label.

**Comment by belpmx** [comment]
Thanks LupaPup.

cadon, I alredy check the stat-multipliers set up on the extractor against the files in my computer, later I will upload the config files itself and a screenshoot of game configuration.

For the OCR issue, I will be checking later when I arrive to home.

Thanks.

**Comment by belpmx** [comment]
Sorry for the delay,

I am attaching a zip archive with both config files (ini.files.zip)
Also attaching my current configuration on multiplier.

Please let me know if more information is required.

[ini files.zip](https://github.com/cadon/ARKStatsExtractor/files/1361497/ini.files.zip)
![multipliers](https://user-images.githubusercontent.com/6753919/31262484-e65b00aa-aa20-11e7-86f7-65ca45040e46.png)

**Comment by cadon** [comment]
Hi, does the imprinting decay on your server after some time if you don't cuddle a creature? If yes, the extraction is probably not possible. In this case, extract creatures after hatching and before the first imprinting.

**Comment by cadon** [comment]
It works in the latest version if you use "Partly Event".
