### ISSUE TITLE
Giga stats coming up Red

### ISSUE THREAD

**Issue by PE01998** [cadon/ARKStatsExtractor#497]
I am currently playing singleplayer on console, When i type in the stats into the extractor with the singleplayer settings box checked the health and damage stats go red, however, when i uncheck the singleplayer settings the stats go green, is there a reason why this happens or could this perhaps be a bug of some sort?
![image](https://user-images.githubusercontent.com/32595759/31308617-af8919d4-ab71-11e7-9776-9271e4337686.png)

**Comment by cadon** [comment]
Hi, that's a bug, thanks for the report. The negative taming-bonus isn't applied correctly with the singleplayer-settings. It'll be fixed in the next release. Until then it's not possible to add Giganotosaurs and Griffins in the singleplayer-settings. A workaround is to temporarily disable the singleplayer-settings and add the Giga manually with these levels via the tester:  (Giganotosaurus, Lvl 224): HP: 28; St: 29; Ox: 24; Fo: 38; We: 36; Dm: 134; Sp: 34; To: 223; After that you can re-enable the singleplayer-settings again.

**Comment by PE01998** [comment]
Thank you Buddy, Feedback was helpful.

**Comment by cadon** [comment]
Fix is released
