### ISSUE TITLE
Couple of Bugs

### ISSUE THREAD

**Issue by 6yXJI0** [cadon/ARKStatsExtractor#509]
1) Can't remove cooldown/growing status in the library. Need to restart App, Check/Uncheck "Include Cratures with Cooldown" for those dinos to show on Breeding Plan.
2) Whole Incubation/Gestation timer stops after reaching 0 on Incubation/Gestation
![overwolf_2017-10-16_05-00-35](https://user-images.githubusercontent.com/32490288/31592169-01e469fe-b22f-11e7-80d2-09d5df3dcfba.png)
3) What can Overlay button do? The only thing i can use is adding a Timer, but can't remove it. Sometimes it shows me strange number on +stats buttons.

**Comment by thefinalwolf** [comment]
I just wanted to state I have the same issues with line items 2 and 3.

As for line item 2, I'm seeing the timer fail to continue right after the Incubation/Gestation timer finishes. Baby Time left and Growing Time left never begin decreasing.
I generally start the timers by clicking the "These Parents just mated button" under Breeding Plan.

Great work with the program by the way.

**Comment by cadon** [comment]
Hi, sorry for the late reply.
1. will be fixed in the next release.
2. is intentional, as this timer is only concerned about the egg / pregnancy. Once a creature is hatched / born, its values have to be extracted, so a creautre-entry is created for it. You can do this by right-clicking on the incubation-timer and choose "Extract values of hatched/born baby", which has the advantage that both parents are already selected. Once the baby is extracted and saved to the library, a new timer automatically appears in the Raising-tab, this time in the "Babies"-section and shows the remaining time for the baby-time and the total-maturation-time.
3. The overlay should display the stats of a creature automatically once you open its inventory. Currently this doesn't work for wild creatures. The overlay can also display taming-infos if you have enabled the speech-recognition. E.g. you could say "Rex level 100" and the overlay would display the taming-details for a level 100 rex.
