### ISSUE TITLE
Imprinted Ovis won't Extract

### ISSUE THREAD

**Issue by jwvanderbeck** [cadon/ARKStatsExtractor#510]
I raised an Ovis and gave it one imprint, which left it at an in game value of 49% imprint.

However when I try to add this creature, the extraction always fails and errors out on the Imprint levels stating ti can't find anything.

I tried restarting the game (Single Player) in response to the notice about it sometimes needing a server restart, but this made no difference.

If I enter 49% and click extract it says "Imprinting-Value or Multipliers probably wrong" and sets the imprinting to 50.44200%

![Errors](https://i.imgur.com/PsD26Xl.jpg)
![Multipliers](https://i.imgur.com/N1oCZb3.jpg)

![In Game](https://steamuserimages-a.akamaihd.net/ugc/868491890541349096/D7C0E1644DAF5D78FCF27517F1F976EED561623E/)

**Comment by jwvanderbeck** [comment]
After a lot of trial and error and some math, I managed to back out the imprinting bonuses to get the originally bred stats.  I then added this as a new creature to the library, here it is:

![Base Stats](https://i.imgur.com/iAibHO0.jpg)

I then went into Edit Mode and entered in the imprinting bonus of 49%.  The resulting stats were interesting.  The Health was very close to actual (just a decimal point off) but other stats like Food and Weight were farther off.  I played with the exact percentage a bit, and there is no value that will satisfy all the stats against what I see in game.  I imprint value of 48.8% will match the Health exactly but be off on everything else.

**Comment by cadon** [comment]
Hi, are you sure all the multipliers are set correctly? I'll do some tests with the singleplayer-settings, maybe they have adjusted them slightly. I hope I can test this in the next days, sorry if it takes a bit longer.

**Comment by jwvanderbeck** [comment]
The multipliers should all be correct given they were set by dragging in the game ini, and they've proved to be correct for all other extraction until this.

As for testing, don't worry if it takes longer!  This is a game, not life or death :)  I can live without it working.

**Comment by cadon** [comment]
Hi, I played with the values as well, with an imprinting-bonus of 48.84 % all the stats seem to fit. Internally the game calculates with a double-precision decimal number, but only shows a rounded value (i.e. here 49 %).

So the issue here is, the actual imprinting-bonus of 48.48 % is not a valid number for the mature- and cuddle-multiplier. One reason could be that on the server you're playing there is a decaying of the imprinting, if you miss a cuddle. So the possible value of 50.442 % (which the tool corrects the value to) could have decreased slowly to 48.84 %, resulting in this situation.

The imprinting-decay was introduced with the imprinting, but removed from the official servers. I have no experience with it other than I know it can be enabled on unofficials.

To extract the ovis, set the imprinting-quality to 48.84 % and check the checkbox "don't adjust". For future creatures, it's best to extract them right after hatching/birth to avoid the issue with the decaying imprinting-bonus and adjust the imprinting later manually (in the library: right-click -> edit -> adjust the imprinting -> save).

**Comment by cadon** [comment]
The extraction is now also possible with the "Partly Event"-checkbox.
