### ISSUE TITLE
Crashing when used with Google Drive.

### ISSUE THREAD

**Issue by mrsimicsak** [cadon/ARKStatsExtractor#518]
My and friend and I are using Ark Smart Breeding and sharing a database. We started having problems with it crashing with an error something like "file in use by another process Google Drive" (I'll post a screen shot when it happens again) when we are both using it. I unchecked the "autosave" option and left the "autoload" option checked and just manually saved, which prevents it from crashing, but I still get the error message. I started saving to a temp file to prevent losing work, but I've had it crash even when I'm saving to the temp file that I know I'm the only one using.

I've noticed that once it errors/crashes it doesn't ever seem to want save to the same file again until the program is either restarted (losing work) or saved to a different file.

I took a look at the code and I think there is a problem with the [saveCollectionToFileName() metthod in Form1.cs](https://github.com/cadon/ARKStatsExtractor/blob/9e763325b70b9e2597554d733e4ef963798330ff/ARKBreedingStats/Form1.cs#L1295) I believe the call to .Create() is throwing an error which is caught by the try statement, which immediately goes to the catch statement, skipping the file close statement and leaving the file open.

**Comment by thFrgttn** [comment]
My friends and I are also having a crash issue when syncing via google drive. 
I tracked it down to an unhandled IOException caused by the File.OpenRead(fileName) line in loadCollectionFile, looks like open/read permissions aren't always available the moment the file watcher triggers.
I've copied the retry logic from saveCollectionToFileName and that seems to have fixed it, although maybe there is a better way as the delay can make to program appear to freeze.
