### ISSUE TITLE
Problem with extraction

### ISSUE THREAD

**Issue by Paket236** [cadon/ARKStatsExtractor#522]
Sorry for my English. I translated into google translate.

1. ARK Smart Breeding incorrectly extracts the characteristics of the tamed Pteranadon on the official (!) Server.
![20171029193429_1](https://user-images.githubusercontent.com/9355368/32147061-cff26770-bcf1-11e7-8625-1fa7211362a1.jpg)
![2017-10-29_21-15-14](https://user-images.githubusercontent.com/9355368/32147063-d80e8fe2-bcf1-11e7-84a8-656ef1855097.png)

2. The program also calculated 151 wild levels of the mammoth, although it was 150 (the official server).
![20171029210102_1](https://user-images.githubusercontent.com/9355368/32147064-e15fed5c-bcf1-11e7-81f6-aa8a7ddc6e9e.jpg)
![2017-10-29_21-16-59](https://user-images.githubusercontent.com/9355368/32147067-e5fa510e-bcf1-11e7-8f67-1f734a8fac3c.png)

3. Is it normal that the speed of the rex = 1 (the official server)?
![20171029210138_1](https://user-images.githubusercontent.com/9355368/32147068-ec867d9a-bcf1-11e7-85b3-4b4696d41895.jpg)
![2017-10-29_21-17-36](https://user-images.githubusercontent.com/9355368/32147070-f0b04cca-bcf1-11e7-8f39-8f6a95a6881f.png)

**Comment by cadon** [comment]
Hi,

1. sometimes the extractor cannot determine the exact levels and you have to choose the correct ones. This is the case if the stats are yellow. For the pteranodon, this combination would be possible, for example:
Pteranodon (Lvl 244, TE: 94.8%): HP: 1674.2 (38, 1); St: 734.4 (31, 23); Ox: 630 (32, 0); Fo: 7401.5 (44, 0); We: 223.6 (31, 5); Dm: 307.8% (22, 16); Sp: 135% (0, 0); To: 1546.1 (198);

2. The same with the mammoth: if stats are yellow, try the possible combinations until you find a valid one. This for example:
Mammoth (Lvl 280, TE: 99.8%): HP: 5100.1 (25, 0); St: 1023 (21, 0); Ox: 585 (29, 0); Fo: 23500 (37, 0); We: 1044 (40, 4); Dm: 591.4% (32, 52); Sp: 200% (39, 0); To: 7909.5 (223);

3. The speed cannot be calculated directly, so if the speed-level is wrong, it's because other stats are not correct also. For this rex, the imprinting is not yet finished yet and the values seem not to be possible. This is a common issue during imprinting, because the game sometimes "forgets" to increase some stats after a cuddle. I recommend to extract this rex again if the maturation has finished, or, if it is already an adult, try to go out of render distance and back again, this might solve it.

**Comment by Paket236** [comment]
Thanks for answers! I rechecked, and here are the results.
1. Pteranodon: I increased by 1 level, the number of yellow characteristics became 2. I tried all combinations (in Stat Testing) [St: (29,26), (31,24); We: (27,7), (29,6), (31,5)], but the wild level is obtained incorrect (not a multiple of 5).
![20171030191944_1](https://user-images.githubusercontent.com/9355368/32183268-e5dee910-bda9-11e7-9bdf-045e3b049c15.jpg)
![2017-10-30_19-21-07](https://user-images.githubusercontent.com/9355368/32183280-ef0a9d22-bda9-11e7-82bc-d56f460a9690.png)

3. Rex: Rex has grown, and the speed characteristic is still = 1 (I restarted the game). Is it still not normal?
![20171030183940_1](https://user-images.githubusercontent.com/9355368/32183307-08631290-bdaa-11e7-977a-8511fd8bebf1.jpg)
![2017-10-30_18-42-49](https://user-images.githubusercontent.com/9355368/32183318-0faf5c70-bdaa-11e7-9fb7-57d72a603400.png)

**Comment by cadon** [comment]
There can be rounding errors in a few cases, this might be one of them, so the tool shows 136 instead of 135. As long as the extracted levels are correct, the wild level doesn't really matter.

It seems the speed-level is only 1. You can check both parents, one of them should have also a speed-level of 1.
