### ISSUE TITLE
REQ: Stat Mutation Specific

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#534]
It be really useful if instead of it saying '5 mutations' you could plug in exactly which stat and show it on the breeding list.  For example, i might have an argent with 4 mutations, but its 2 hp, 1 stam, 1 food.  So maybe next to each stat it has the option to add a mutation, so its reads like '28 Food' then a +1 next to it.

**Comment by cadon** [comment]
Hi, it doesn't matter which stat is mutated, the only thing that counts is the stat-level and the mutation-counter. You can't distinguish between a creature that has 20 non-mutated levels in damage and one mutation in damage and a creature that has 21 non-mutated levels in damage.

**Comment by Wardjp** [comment]
How I understand it though, if you carefully track it, you can pinpoint where the mutations go. The incentive for doing this is that if you already have a particular mutation, if another offspring gets the same mutation, it basically becomes wasted.

**Comment by Wardjp** [comment]
For example, in this snippet, I bred Rex- from M18 and F15, you can tell that the mutation came out in Stamina. It would be great if there was a way, even manually, for us to mark and identify this in the app so as to track mutations and how much they're for. The mutation system is still so vague, it'd be great to be able to use our favorite app to map out its functionality and be able to learn how it works and what not, as our dinos picked up different mutations.

**Comment by cadon** [comment]
I understand the urge to know what stat exactly got a mutation. But if you think through it, what's really the benefit to know that? In you library you now have the "Rex-" that has a top stat in stamina. Where the mutation went exactly doesn't matter. Regarding your first post, if another offspring gets a mutation so that it has the same levels in a stat like another is always wasted, no matter if the stat of that other creature was itself mutated or not.

**Comment by Wardjp** [comment]
One way I see it benefiting is ensuring that each mutation increment is beneficial, and calculating the breeding plan to avoid inbreeding mutations. For example:
![image](https://user-images.githubusercontent.com/19726338/32876826-30566cc2-ca64-11e7-97e9-23dff11cb31f.png)
Those 3 unavailable rexes are the product of rexes are the product of F16 and M20. F16 inherited that stat mutation from M20, then when I turned around and bred the two of them together, partially for testing, partially to continue to try to breed out stats and increase the number of dinos with high stats, my offspring now have 2 mutations, but yet they have gained no stat increase, because they are simply being incremented by the fact that dad gave daughter the mutation, daughter mated with dad and incremented that mutation number without providing any benefit.

**Comment by cadon** [comment]
Does it matter now that the mutation was in stamina? Surely the unavailable offsprings are worse than their parents because their mutation-counter is higher, but stats-wise their as good as them.

To see, if a mutation was in a useful stat, let's compare two offsprings with the same stats, except one of them got a mutation in melee (good), the other in oxygen (wasted). If you compare them in the library, both have a mutation-counter of one, but one has a higher melee, so this is automatically prefered over the other, because you want a high melee-stat. Now imagine you tame a creature that has the same stats like the one with the higher melee, so this one is better, because is has no mutation-counter. In retrospect, it now doesn't matter where the mutation exactly happened, the only thing that counts are the stat-levels and the mutation-counter.

If I would add a stat-wise mutation-marker, do you have an idea how it would look useful? An extra column that contains e.g. "H2D1" to mark two mutations in HP and one mutation in damage?

**Comment by Wardjp** [comment]
Yea, I agree with you, I'm just trying to figure out a way for the tool, not so much to track where mutations go, but track mutations to ensure that it aims to deter inbreeding of mutations. Although, I mean, that is a pretty advanced aspect and would likely be easier and better to leave for players to learn and advanced breeders to benefit from if they've put in the effort to understand breeding to that level.
