### ISSUE TITLE
Screenshot not Taking Entire Screen in 2560x1440 Resolution

### ISSUE THREAD

**Issue by Xeavior** [cadon/ARKStatsExtractor#585]
The screenshot taken by the OCR seems to be cutting off what my display is showing. I was going to try to set up a custom format but realized I was unable to since some information is cut off from OCR's sight.

I have:
two 2560x1440 monitors
NVIDIA GTX 1080
i7-7700k

![image](https://user-images.githubusercontent.com/9309655/34861435-62cb058a-f72a-11e7-88f8-9eef24cd62d4.png)

**Comment by audiopathik** [comment]
That very last rectangle down there is where the Imprinting stat is shown for bred creatures, does the "Read Values from ARK Window" feature read this stat correctly for creatures that have it?

If so it's not an issue as there is no more stat below it.

When you load the ocr_2560x1440_100 preset config in ARK: Smart Breeding>Experimental OCR>OCR Info the screenshot is cut off as well?

You can try configuring ARK: Smart Breeding>Experimental OCR to use a higher resolution and reposition the rectangles accordingly.

**Comment by Xeavior** [comment]
When using the ocr_2560x1440_100 it states in the output:
Error while calibrating: probably game-resolution is not supported by this OCR-configuration.
The tested image has a resolution of 2048×1152 px.

Once I set the resolution to the cut resolution size it gives me this output:
Health: 8,/70,38,3/.10/8827
Stamina: ,,/2670,5067%/
Oxygen: 0/86:97856,9
Food: 891842,3,/3854,9.
Weight: 13,57748,8
MeleeDamage: 1.,,,2,2,9.,034.41%/,
MovementSpeed: %,,%6/30,/351/,
Torpor: 13,137452,9
Imprinting: 66
Level: ::,51/5::,:135
NameSpecies: \AUL=2ege|EuIbdog)/
Tribe: AvengersgftheArk

However, this bulbdog does not have any imprinting stat.

**Comment by audiopathik** [comment]
ARK: Smart Breeding crops off some parts of the screenshots since they are not necessary, that's okay as long as the Read Values from ARK Window works.

When the creature doesn't have the Imprinting stat because it's tamed, not bred, there will always be any random letters or digits in the OCR output instead.

Just make sure the rectangle boxes in your first screenshot don't overlap with the text, so Charge Capacity must not be within the rectangle box - you can decrease the rectangle width with the "Width-L" Selector to the right" - otherwise the text letters will falsely be recognized for digits and be considered stat values.

**Comment by Xeavior** [comment]
If it is always random, won't that mean the extractor would always think it is bred and therefore not pull correct stats from the dino? Also, the logging for the values read look like it is not read properly.

![image](https://user-images.githubusercontent.com/9309655/34908632-80256e70-f858-11e7-8ae9-7f897719164f.png)

**Comment by audiopathik** [comment]
No, when you use the "Read Values from ARK Window" feature on a creature that's either wild or tamed (doesn't have an Imprinting), ARK: Smart Breeding will try to recognize digit characters from the area on the screen the imprinting stat is in for creature that do have imprinting.

The feature does work correctly, I'm using it frequently.

**Comment by Xeavior** [comment]
However, the feature is returning a value for a non-existent stat and applying it to the extractor. Am I missing something or doing something wrong?

**Comment by audiopathik** [comment]
No, it's not applied to the extractor if the creature doesn't have the Imprinting stat.

However, as to the OP, all I was trying to say is I don't think this is an issue, the Imprinting stat is not cut off, so all stats are on the screenshot.

**Comment by Xeavior** [comment]
What about all the interference in my statistics, is there a way to minimize that?
the level/name/sex/tribe are the worst ones, I managed to get the other stats to collect better.

**Comment by audiopathik** [comment]
Well, OCR was actually designed to recognize human hand-written letters and digits, so it scans the rectangle areas on the screenshot of the ARK window for symbols it can recognize for digits or letters, but this is rather fragile, it highly depends on the image quality and contrast between letters and their background.

So basically anything that helps improve the image quality, contrast and letter size improves OCR's performance.

Make sure the Gamma level in ARK is set to the default while you use the "Read Values from ARK Window" feature (a lot of people make use of the 'gamma' command since it is enabled on offcial PVP & PVE servers).

I wasn't able to improve that recognition any further as well so far.
It's why it's called "Experimental" anyway...

**Comment by Xeavior** [comment]
Looks like this is something that will be worked on more as OCR moves through the experimental stage. I'll close this issue.

**Comment by cadon** [comment]
Hi @Xeavior, I tested the OCR with a resolution of 2560x1440, the screenshot looks fine for me. Is the resolution in windows also 2560x1440 or different? The OCR only considers the windows-resolution.
