### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by class101** [cadon/ARKStatsExtractor#613]
Auto update check is great but old school, today I want Smart Breeder to automatically update itself I'm pretty sure you can do it, I was able to do that once upon a time at googlecode.

Imagine Steam asking you to unzip Steam.zip to each new update and telling you there is a new update.

**Comment by cadon** [comment]
It would need another executable for that, something like an updater.exe. I'm sure that's possible. Steam is a multimillion dollar company, that basically lives from updating your software, compared to me as one guy programming a bit after work in my free time. I'll put it on my todo-list.

**Comment by coldino** [comment]
One option is ClickOnce, the publish system built into VS, direct from GitHub. I used it in my mapping app recently because it was quick and easy to do solo, plus I could host the releases directly on GitHub (in a separate repo). See [here](https://refactorsaurusrex.com/post/2015/how-to-host-a-clickonce-installer-on-github/) for instructions on setting it up via GitHub.

ClickOnce can be a bit meh, especially if you don't sign your releases (multiple "are you sure" during install). The upgrade process is very smooth. Try [Larkator](https://github.com/coldino/Larkator) for a demo.

I noticed [Squirrel](https://github.com/Squirrel/Squirrel.Windows) tries to do the same thing as ClickOnce but better. Haven't tried it yet but it looks nicer for the user but more work for the dev than pressing the magic Publish button as in ClickOnce.
