### ISSUE TITLE
Mutation Count wrong

### ISSUE THREAD

**Issue by defyreality** [cadon/ARKStatsExtractor#654]
i believe it happened in the latest update 2days ago. mutation counter on dinos is now broken into mother/father, but in the stats column in the library for mutations, only the mothers count is showing, not the combined of the two.  however, when adding a new dino and using parents that exist in the library, it is still combining both mother and fathers mutation count into the mothers mutation field.

**Comment by cadon** [comment]
Sorry, that's still WIP. For now you can ignore the paternal mutations, I'll implement this fully in one of the next releases.

**Comment by defyreality** [comment]
will do. thanks

**Comment by Zhinjio** [comment]
I did notice that when you import multiple dinos (from an export), it will normally correctly find the number of mutations. HOWEVER, if that last dino you imported had a HIGHER paternal mutation count than the current import, it will still show that higher mutation counter, instead of the correct value from the dino you're importing. Maternal mutation count updates correctly.

Maybe this is worth listing as a separate bug?
