### ISSUE TITLE
Allow manual adding of points

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#692]
There are some mods out there now that shows you just what points a dino has. 
https://i.imgur.com/0ckkpH0.jpg
Like such. 
If we know the points from this, can we have an option to manually add them in? 
Because even after getting both the game.ini and gameusersettings.ini from the server I'm playing on and importing those settings, I STILL can not add in any dino that has any level up's added to it, when before I could no issue. 
https://i.imgur.com/xaKdFz6.png
They add in fine if added right after there tamed/born but the moment a lv up is added it throws errors. Sadly my tribe doesn't always add them in before lving tames up. We have had to go back to our excel sheet to keep tabs on things. 

7x Tame
15x Breeding/Maturation
100 lv ups after tame. The rest is all 1.0

**Comment by kohonac** [comment]
set the level in ASB to 245 to match what is in the ingame screenshot should help

**Comment by cadon** [comment]
Hi @Taiine , there's some discrepancy between the two screenshots, did you level the creature between taking them or are these different creatures? Can you post a screenshot of the actual inventory with the exact numbers the game shows (the mod only shows integer values without the first decimal after the dot). An additional screenshot with the mod-overlay and the level-numbers would again help.
It seems you're using (mostly) the default-stat multipliers (i.e. not everything is 1, you can click on the button "Set to official values" in the stat-multiplier-settings).

Also, if you know the levels via the mod, you can just enter them in the Tester-tab and add the creatures with that.

**Comment by Taiine** [comment]
Yeah sorry, the screeny I took from ASB was before I pumped in the levels, but it was still used the extracted dino stats so changing it would do squat. 

and yes, I set all to default before changing the server settings.  I can still only add dino's so long as no levels have been added to them.

**Comment by Taiine** [comment]
Okay here you go.
https://i.imgur.com/ZXpxNAb.jpg
https://i.imgur.com/Yd3wyYK.jpg
https://i.imgur.com/rxiS6xo.jpg

(note the mod shows wild lv's, but the values change and include the points for tamed, the lv it tamed out at is the bottom number) 
I JUST exported this dino's stats, You can see that in the first shot. 2nd shows what the points are, 3rd shows the dinos inv stats, and ASB's stuff. The server setting's are proper from the INI setting's I was given, as well as placing them all in manually after re-setting it all back to 1.  

7x Tame
15x Breeding/Maturation
100 lv ups after tame. 

The ONLY creatures I can get to properly add is fresh tames with no LV's added, or new baby's. Once any lv get's added, it can't read that dino anymore. 
I also can't add it under test as I can't put anything for torp 
https://i.imgur.com/u8ZpPIt.jpg
Well I CAN add it, but all the values read 0.

**Comment by kohonac** [comment]
you added all the lvls to the domestic side and no wild levels so ASB thinks that you have leveled the dino 208 times. would you mind uploading the server INI's as well as that Dino's INI. I believe that will eliminate some of the confusion as well if you join the Discord Server you may get more help as there are more people there than check GitHub issues

**Comment by Taiine** [comment]
What do you mean I 'added all the levels'? I am importing the extracted data from ARK, (options>export dino) and IMPORTING it into ASB. What you see is that file's import. I literally showed the export, what stats get shown, and what ASB displays when I import that data.

**Comment by kohonac** [comment]
the highlight side is for wild/tamed stats and the the side that you enter the levels on is the domestic side so the levels that you add after taming.
![image](https://user-images.githubusercontent.com/3374605/40265171-1f11d3e2-5ae8-11e8-9623-13fbd954452c.png)

**Comment by Taiine** [comment]
@kohonac  Once again I am NOT USING THAT. I am Exporting the dino stats in-game and pressing that IMPORT EXPORTED DATA button at the top of the window and select it. I LITERALLY Show it STEP BY STEP in the screenshots I posted before. 
https://i.imgur.com/2FRQqke.png
Is that really that hard to understand?! 

@cadon I could not say but I only lved it in health, damage and a little weight. I'll be breeding my pack again in a little while and I'll set aside the worst of the bunch to do the lv up in each statto show the screenys. But thus far, what ASB shows, and what the mod shows are spot on for stat points. So you did good there. It's just not properly reading the values when lv's are added.

**Comment by kohonac** [comment]
so you edit your post then try and make it sound like im being a idiot, not cool. i responded to help you based on this https://i.imgur.com/u8ZpPIt.jpg image that you had posted. sorry that you are so angry i wont bother trying to help you any more.

**Comment by VolatilePulse** [comment]
Since you have the game.ini file, do you mind uploading that here? You can drag&drop the file in the new comment box, click on "selecting them" or copy/paste the actual file (not just it's contents) in the comment box. Similarly, drag&dropping the game.ini file on the ASB Settings -> Multipliers window will also automatically update the multipliers in ASB.

Based on the information you've provided as well as doing some number crunching, a value(s) is off somewhere. The only other concern, if all of that information is already correct, is that a mod on the server is affecting all creatures as you said you can no longer extract a creature once it has been leveled post tame or after raising it.

If you'd prefer to add creatures "manually", you can take the levels that the binocular mod gives you and use the stat testing tab to add the creature to your ASB library. This is part of the program for specific reasons, but we typically would prefer helping you figure out how to use the program to it's fullest. The only information that is ever relevant to ASB is the Wild Levels and if any parents are associated to a creature. The program displays stat values and Domestic Levels for convenience and added display purposes but the program doesn't rely upon them if you understand the values displayed for a leveled creature will never be accurate.

If you're unable to provide the game.ini file, we may still be able to help you figure all of that out. If your server doesn't have any creature mods, like Classic Flyers, the best creature to tame is a ptera. From here, level each stat up exactly once and take a screenshot with the binocular mod as well as it's inventory and we should be able to get you very close to the exact multipliers if no the exact.

**Comment by Taiine** [comment]
@ kohonac The fact is this whole time I've been having issues importing the data from the exported files. That is the whole center of this issue. Yes I put them in wrong on the test thing as shown as I never had to use that before and I messed up, I removed it once I realized that but the issue still stands that I can't Import from exported data. That is what this issue has been from the very start. 

@VolatilePulse This is the first time I have ever had extensive issues getting my dino information into ASB as I've been using this tool for two years and going. Yes I did drag and drop the game.ini file to ASB and it loaded the setting's fine. I even tried adding them in manually as suggested 'reset all to 1' and re-placed them in. The server I'm on has few mods and nothing that effects creature data, only the ini change for 100 level ups.

[Game.txt](https://github.com/cadon/ARKStatsExtractor/files/2020192/Game.txt)

**Comment by cadon** [comment]
A tamed, low-level dodo with 1 manual level-up in each stat would be enough, with a screenshot before and after you applied the levels. Or any other species.
Or, if you have the gameusersettings.ini, there the statmultipliers should be stored.

**Comment by cadon** [comment]
The multipliers of TameLevel of HP is maybe 0.33, and for Weight 0.45. It's still not working completely, though, so there might be other multiplies with custom values. If you still have issues with that, feel free to reopen.
