### ISSUE TITLE
Question About Wasted / Speed Points

### ISSUE THREAD

**Issue by DavidRexBreeder** [cadon/ARKStatsExtractor#707]
I see that there are points added to the speed of each dino but for each species the base speed is at a set level, so why are their points added to the speed? 

If as i suspect these are wasted points, can these points be useful at all for breeding?

If they are no use at all why does the breeding calculator add them into the calculation and suggest one with good points in speed over one that has less points over all but has useful stat points in HP, Stam, Weight and so on.

Thanks

**Comment by cadon** [comment]
> why are their points added to the speed?

Because the game is working like that, that would be a question for the developers of ARK
> can these points be useful at all for breeding?

Each stat-level also increases the total level and the torpor-value. Regarding speed there are no other advantages. Also you could hit the total-level-limit of 450 more easily, which would be a disadvantage.
>…why does the breeding calculator add them into the calculation…

The breeding-planner considers the stats according to the set stat-weighting. If you don't want the speed-levels to be considered in the calculations, set the stat-weight to 0. If you want the speed-level to be low, set it to a negative value.
