### ISSUE TITLE
Argentavis Health is always Red!

### ISSUE THREAD

**Issue by Jammiiboi23** [cadon/ARKStatsExtractor#711]
![img_20180608_213948120](https://user-images.githubusercontent.com/40075277/41183203-5037bcc2-6b71-11e8-8f69-467a604658af.jpg)

https://i.gyazo.com/87ce436f48827c54fecf4d6b7e3fa382.png

I am also playing on the new Small tribe server which have 3x taming etc.

Any help greatly appreciated :)

**Comment by cadon** [comment]
Hi, are you playing on an official server? The increase per domesticated level for your Argentavis seems to be 27%, whereas the official server recently changed that value to 30.375%. It also could be that this argentavis was tamed before the change and since then the HP wasn't leveledup, so the old value stuck. You can try to level up HP once to update the value. The levels for HP are probably 31 wild and 5 domesticated.
