### ISSUE TITLE
Last Export and color issues

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#730]
- [x] 1. First of all, the Last Export button only fills in the colors if you have the extractor already opened, otherwise, it leaves in the colors of the previous creature.

- [x] 2. Secondly, even with Tribe and Owner greyed out, it still fills in those fields.

- [x] 3. Thirdly, it fills in color regions the animal may not even have. For example, Ovis only have regions C0, C4 and C5, yet all 6 are filled in. Other tools show me that the creature does have those areas colored, but doesn't use those colors anyway. Perhaps a check to see if the color region is actually used.

- [x] 4. Fourthly, (a minor thing): there are 2 white colors: 18 and 36. Most creatures have 36 instead of 18 in their natural colors (like Tek Rex C5), but because they share the same hex value, the extractor turns it into 18.

- [x] 5. I also noticed that multiple creatures, like the Direbear, have regions named "unknown". These regions do not actually exist on the creature and should perhaps just be removed, even if the game has data for those regions.

Edit: added numbers and checkboxes

**Comment by VolatilePulse** [comment]
1) There is a known issue with using the "Last Export" button. The recommendation is to use the "Import Exported Data" button instead as it seems unaffected and is typically much more efficient.

2) They greyed out fields only currently prevent OCR from potentially writing jargon text it there. I'm sure it can be extended to prevent the import data as well, but is there a need for that feature?

3) It may be due to the same issue that plagues #1, but unsure at the moment. If you try the "Import Exported Data" button, does it do the same thing? By default, the extractor shouldn't be filling in color regions that aren't actually used by the creature.

4) The data extracted from the export files comes directly from within the game and as creatures can experience mutations, ASB would be unable to distinguish between natural and artifical coloring. That said, whatever color data ark provides in the export files is what is used. I'm not sure if there is an easy way around this one that wouldn't affect other creatures. 

5) All of ASB's data comes from a data dump from Ark. This provides the advantage of no longer having to get this information by hand, is deemed more than 99.99% accurate, and has information available that you just can't find in game. That said, the Dire bear recently underwent a remodel as part of the TLC updates. There is a good possibility that the developers/designers forgot to remove one of the color regions that is no longer available. Just because you can't see it doesn't mean that it doesn't exist. Like I stated at the beginning of this one, modifying this data by hand is no longer done and it's solely a quirk in Ark's code. Once they fix it, it will automatically be fixed in ASB as well.

Sorry if any of that came off as rude, just hard to explain everything and be to the point.

**Comment by kohonac** [comment]
for point 3 what version of ASB are you using as with the most recent that should not be happening anymore

**Comment by soepie7** [comment]
I use the most recent version according to the update checker.
