### ISSUE TITLE
Does ASB support ark mobile version?

### ISSUE THREAD

**Issue by Yaweeh** [cadon/ARKStatsExtractor#756]
Hi, I'm playing Ark mobile version. Does the ASB support it? As I can't input my dino stats.
Here the screenshot when I try to input the stats: https://ibb.co/iSibLz
Is there a way to bypass this error?
Thanks

**Comment by VolatilePulse** [comment]
Sorry, got a bit busy. I finally got a chance to look into this and a couple of things are concerning. I went back to the original release of the file and was still unable to correctly extract your Rex (not much has changed since then either for Rex's). I noticed the creature level was really high so I doubt you're playing on an official server, but I wasn't aware of custom servers being an option on mobile. Can you provide any other information like possibly an in game screenshot of the Rex as well what sort of server you're playing on (maybe single player)?

**Comment by Yaweeh** [comment]
Hi, thanks for your support. I just use the values.json from the v0.20.8 version and it worked. No other issue so far.

At the moment, there's only offical servers on ark mobile. The reason why my rex lvl is so high because there're 3 type of server difficulties: easy (max lvl wild dino 30), medium (max lvl 150) and hard (max lvl 300) and I play on hard server (multiple). I attached some in game screenshots. https://ibb.co/nyQniK
https://ibb.co/fhg4Vz

**Comment by VolatilePulse** [comment]
Appreciate the screenshots. First thing I noticed is how much lower the torpor is on those two Rex's as opposed to the screenshot you originally posted. Possible typo?

**Comment by Yaweeh** [comment]
Oh, here are 2 screenshots of the same rex: https://ibb.co/joXExe https://ibb.co/kYnKVz. One is right after tamed and one is after 1 days. You will see the torpor is fixed when server maintenance take place daily.

Another example is the wild Giganotosaurus with 80000 hp and if you tame it, after server maintenance, it will be fixed to 17000 hp only.

**Comment by Yaweeh** [comment]
I think this is the reason why I could not extract the stats at the beginning. So the solution is not about using the old version of values.json file, it's about waiting for server maintenance to fix the abnormal stats :)

**Comment by VolatilePulse** [comment]
Right, I forgot mobile suffers from the torpor bug. Steam (the original version) and consoles suffered from it for a while as well but eventually got fixed, roughly a year or so ago. That will make it harder to extract fresh tames. Bred creatures will be fine, however.

But if you don't have any other questions, could you please close this issue? I'm going to leave a link in this message so that other mobile users can get the correct values.json file quicker.

**Comment by VolatilePulse** [comment]
I still believe an older values file is needed, maybe not specifically for the Rexes, but many other creatures had different stat values since the version Wildcard is using for the mobile version.
