### ISSUE TITLE
Error Extracting 99% of dino's

### ISSUE THREAD

**Issue by sMeLLzoR** [cadon/ARKStatsExtractor#758]
Hi there, 
I have realized this issue comes up a lot. 

My issue: **For some reason the only dino's that work for extraction is the Giga. All the rest have errors while extracting. Sometimes it's HP and damage other times it's Stamina etc. It feels random and very frustrating. **

I have done a lot of digging and went through almost all the topics that I can find on this issue so I have tried a LOT of troubleshooting. And yes I am the server admin.

What I have tried:
- Checked all the multipliers like 100 times over
- Checked and unchecked the Singleplayer settings
- Removed the entire xml and started from scratch
- Restarted the server, updated the settings (again) and wiped all wild dino's
- Restarted again and again

**If anybody needs screenshots just let me know of what you need screenshots and then I shall post them **

Thanks in advance to all of you that at least attempt to help me!!!
-sMeLLzoRR

**Comment by sMeLLzoR** [comment]
It's a dedicated server cluster that we play on. I play on steam.
We have one mod installed ; Structures Plus (S+)

Here is the [game.ini](https://pastebin.com/KC4ELfvh) and here is the [screenshot](https://imgur.com/a/j2OcbmL) as I don't have the export file.

**Comment by VolatilePulse** [comment]
Both of them appear to work for me. I have a feeling that you haven't set the server multipliers yet in ASB. ~~I've generated the *game.ini* file for you.~~ *GitHub won't allow me to upload an INI file so I hope you have one.* Once you download it (or use the one you already have), just drag & drop the file directly onto the ASB Settings window. This will load all of the information from your server so you won't have to manually. If, for whatever reason, you can't get that working, I'll also include a picture of the corresponding settings for your server. I have also included both of the successful extraction screenshots so that you can see they do extract properly. The Yuty does require you double checking the stat the program checked to verify, or change, the possibility.

![image](https://user-images.githubusercontent.com/6995232/44448030-0d452180-a5b8-11e8-9772-e60ef98e0f0a.png)
![image](https://user-images.githubusercontent.com/6995232/44447674-e76b4d00-a5b6-11e8-8826-889ff111e72a.png)
![image](https://user-images.githubusercontent.com/6995232/44447823-66f91c00-a5b7-11e8-98aa-4ff65b38a916.png)
