### ISSUE TITLE
Mutation Info

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#767]
Perhaps you might consider adding data for what mutations a dino has.  So you can click by each stat and +1 it to show thats where it was.  It detects it automatically but it might be super useful to tell the breeding planner you want to breed only specific mutations in.  Not sure if im making sense i guess.

**Comment by VolatilePulse** [comment]
Tracking mutations really isn't that helpful. A creature with 25 base points and 10 mutation points is the same as a creature with 35 base points in all aspects to the game. Mutations aren't tracked in Ark which is why ASB doesn't track them.

However, the mutation counter, which is handled by a different system, is tracked by Ark and is tracked in ASB as well. This might be what you're looking for.

**Comment by Worldgate** [comment]
I suppose i'll just keep using excel to keep track. :)

**Comment by VolatilePulse** [comment]
Out of curiosity, is there any reason you're keeping track of mutations? I've been away from official for some time so I'm not sure if anything has changed. The last I checked it didn't make a difference.

I do recall many players selling creatures base on the number of health and damage mutations they had, but this didn't really tell you anything.for example, a level 280 Rex with 20 health levels and 10 health mutations (+20 levels) would have less health than a 273 Rex with 38 health levels and 4 health mutations (+8 levels).
