### ISSUE TITLE
Modded Server: Baryonyx speed stat?

### ISSUE THREAD

**Issue by kungfufishstick** [cadon/ARKStatsExtractor#775]
Is there a way to track the speed stat without it reflecting on the levels of bred baryonyx?

**Comment by VolatilePulse** [comment]
I believe what you're asking is if there is a way for ASB to calculate the speed level instead of just using a question mark. The answer is yes, but it's not possible using OCR (Read Values from Window) or manual entry of the stats. You would either need to use Ark-tools (only the server owner would be able to use this) or, as long as you're playing on Steam, you can use the creature export method.

To export a creature, open the creatures Ancestry Tab from it's inventory first, open the action wheel, and select Export Dino. The rest of the instructions can be found on the 4th tab in the settings of ASB. If you need more assistance, just let me know. 😄

**Comment by kungfufishstick** [comment]
The calculator pulls the stats just fine but does what it is originally meant to do for the oxygen/movement speed stat. For my breeding I would like to be able to track the speed stat without it reflecting on the dino level. I enter the correct speed stat and it pumps the dino level way up

**Comment by VolatilePulse** [comment]
With the export feature, the creature stats are all automatically calculated. There wouldn't be a need for any adjustment afterwards. This is the most ideal way to use ASB.

In regards to your concern, since oxygen is no longer displayed (the value is still available in the export file though), ASB can't correctly identify the levels in oxygen, and in turn, can't figure out the speed levels either. This is why after extracting a water based creature, both oxygen and speed will display as question marks. Depending on how you go about it, you can adjust these levels by editing the creature. Before touching any of the levels, everything is right. Once you begin changing the wild or domestic levels, however, the torpor and/or creature levels will change to reflect those changes you made. You can't have 101 stat levels but the creature is only level 100 for example.

If you have some before and after screenshots, I'll be glad to help you further.

**Comment by kungfufishstick** [comment]
Oh I will give that a shot tonight. I never noticed the export option from within game (play on steam). 

Thanks for the help. Will report back.

**Comment by VolatilePulse** [comment]
I should make a clarification to that first comment. Extracting any creature, exported or otherwise, may still require some adjustments during the extraction process. If any stats display as yellow or red, you would need to verify the entered information, locked stats, and stat possibilities are all correct before just adding it to your library.

A side note for importing this way, you can export all of your tames in Ark while you're playing. Once you're done playing (or whenever you want) you can bulk import your creatures. ASB will automatically add all creatures that have only one possibility. Anything left over would require, at the very least, that you verify the chosen stat possibilities.

**Comment by kungfufishstick** [comment]
Figured it out. I didn't have an updated version of ASB. I got it working. Thank you very much for the help! This is good to go on closing. 

Just one last thing in case someone else comes looking for this same issue:

1. Ensure that you are using the most recent version of Ark Smart Breeder.
2. In Ark, you can open the radial in menu or by pressing and holding the button you use to ride the dino. For me I have that set the R so I press and hold to open the radial. What you want is under Options in the radial and it will be export dino. 
3. In Ark Smart Breeder, click the cog for settings. 
4. Go to the last tab for import exported. 
5. Navigate to the folder where Ark exports your dinos. For me that is under Program Files/Steam/steamapps/common/Ark/ShooterGame/Saved/DinoExports/76561198059695253
6. After you click OK to set the exported dino folder, exit the settings and click the button Import Exported Data. 
7. Import all exported dinos at once or you can go one by one to ensure that data is correct. 


Again, huge thank you to VolatilePulse for the guidance!
