### ISSUE TITLE
Tek Parasaur listed as Aberrant Paraceratherium

### ISSUE THREAD

**Issue by b-morgan** [cadon/ARKStatsExtractor#782]
I know its only been a couple of days but I'm opening this issue to keep track.

I tamed one yesterday and did an ARK-Tools default extraction and import this morning.

**Comment by b-morgan** [comment]
Here is the ARK-Tools extract if that helps.

[BionicPara_Character_BP_C.zip](https://github.com/cadon/ARKStatsExtractor/files/2401488/BionicPara_Character_BP_C.zip)

**Comment by Flachdachs** [comment]
The reason is that the values.json is not yet updated. Until a new version comes out you can use this version: [values.zip](https://github.com/cadon/ARKStatsExtractor/files/2401778/values.zip)

This zip archive contains the values.json including the Tek Parasaur. Copy and override this values.json into the json folder of your installation folder. Then the Tek Parasaur will be recognized.

**Comment by b-morgan** [comment]
Thanks! Didn't expect such a quick turnaround!

**Comment by cadon** [comment]
Thanks for the file Flachdachs! I updated the values.json in the repository, the new version can be downloaded by clicking on ? -> Check for Updates.
