### ISSUE TITLE
Light Pets require smaller OCR label

### ISSUE THREAD

**Issue by FireCulex** [cadon/ARKStatsExtractor#783]
![image](https://user-images.githubusercontent.com/9983630/45858002-33bdc000-bd10-11e8-88b2-368116c4802f.png)

**Comment by kohonac** [comment]
are you playing on steam or some other platform?

**Comment by FireCulex** [comment]
I'm playing through steam on PC, screenshot was taken after I exited the game.

**Comment by kohonac** [comment]
dont know if you have tried using the export feature or not but its much more accurate and imports the colors also

https://github.com/cadon/ARKStatsExtractor/issues/775#issuecomment-419262719 is a brief description on how to set it up toward the bottom. if you need more help setting it up you could join discord for quicker help or a more in depth FAQ on the export set up

**Comment by FireCulex** [comment]
When your dealing with 20 or 30 of them it's a hell of a lot faster to use OCR  then export them one by one.

**Comment by dustinpianalto** [comment]
All of us go by points. That is the proper way to breed. 

The export feature is much faster to use than OCR as long as you don't care about the Ancestry and Mutations, if you do care about those then it is about the same. I can export 30 dinos in about 90 seconds and then the import takes a lot less time than using the OCR feature as you don't have to constantly fix mistakes that the OCR makes.

And yes imprinted dinos are always a problem due to floating point math. Especially if they don't have 100% imprint. But that has no correlation to using OCR vs Exporting the dino.

**Comment by cadon** [comment]
Import exported is much faster now and often doesn't even require to tab out the game. No plans to further improve the OCR for now.
