### ISSUE TITLE
Cannot open the app

### ISSUE THREAD

**Issue by dstarr9** [cadon/ARKStatsExtractor#792]
How do I open the ArkBreedingStats SLN file? It just says I have no app to open it with. I don't see any .exe file to open for the window to pop up.

**Comment by VolatilePulse** [comment]
Am SLN file is a Visual Studio project file. It appears you downloaded the source zip file instead of the actual program. This has been a confusion for a long time and there is no way to change it unfortunately.

With a couple of issues the latest 2 releases, I would recommend downloading this version until the next release addresses the issues. https://github.com/cadon/ARKStatsExtractor/releases/download/v0.28.8/ARK.Smart.Breeding_0.28.8.zip

Unfortunately, you'll be asked to update occasionally due to a new version already being out but recommend only downloading v0.29.2 once it's released. In the future, be sure to download the file that **_DOES NOT_ ** say Source Code.

Hopefully this helps.

**Comment by dstarr9** [comment]
Thank you! I was so lost, downloading github and reading through all these txt files searching for where to find this hidden .exe file that was never there haha. Appreciate it :)
