### ISSUE TITLE
Problem entering Pterandon stats being saved as impossible level Dinos

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#81]
Since the other ticket was closed.

First picture is what this tool extracts and saves it as and the second picture is what I enetered.
![capture](https://cloud.githubusercontent.com/assets/1366816/16894072/329e4b30-4b8f-11e6-937c-7c3e8f9b488b.PNG)
![capture1](https://cloud.githubusercontent.com/assets/1366816/16894079/52822d18-4b8f-11e6-8bbf-d98689d7e96a.PNG)

**Comment by cadon** [comment]
Hi, apparently I guessed that issue was resolved. Did you check the answer in #77? That seems to fit.
In general, check the "Since Taming no Server-Restart" checkbox if the torpor-level is way too high, and uncheck it, if the level seems to fit.

**Comment by cyberangel67** [comment]
That is why I created this ticket, because that one was closed. And if you notice I made the same information post in there.

If I try unchecking the Since taming, which btw should not be ticked as the server has been restarted 3 times since then it will not extract.

**Comment by VolatilePulse** [comment]
I'm not sure if you were aware, but once you start adding levels to a
Dino,  there becomes many different legitimate possibilities for what level
each stat is. If you take a look at picture 2 of the extractor, many of the
stats are highlighted in yellow. Yellow means there are a few different
options available, damage is almost always yellow since it determines TE as
well as helps narrow down the LW. Why is this important? If the extractor
thinks it is right, you end up with a dino that validates but has all of
the incorrect values. When you select the damage stat, you need to make
sure you select the correct stat distribution on the right. Cadon even
added in the wild levels to make it a lot easier to find legit
possibilities. If you're confused, I can take another screenshot later.

**Comment by cyberangel67** [comment]
Yes I am aware and none of them will bring the DMG Wild stat from its incredibly high number.

**Comment by cyberangel67** [comment]
Ooops I mean Speed

**Comment by cyberangel67** [comment]
If I turn no server reset off, then the values are more realistic. But the yellow options can't be resolved as the only option I have is to remove the 5 from stamina and have it Zero. The other Yellow is zero and should remain zero.

There is a definite  calculation problem here.

![capture2](https://cloud.githubusercontent.com/assets/1366816/16895896/a8534aba-4bc6-11e6-9e9f-57363731a50f.PNG)

And VolatilePulse, I have been using this program since the very beginning and very well aware of how it works.

**Comment by VolatilePulse** [comment]
Didn't mean to insult your intelligence. I have learned to always check the obvious first. Something else I noticed is that the successful extraction that I got had a taming effectiveness of 85.9% but you have your taming effectiveness restricted to 90-100%. As long as it was the same bird I extracted, that would be your issue. It also successfully extracted a wild level of 120. I'm curious as to what you think is wrong though. Do you think the calculations are wrong or the numbers used in the calculations? I'm not trying to undermind you, just trying to help.

**Comment by cyberangel67** [comment]
Look at the speed, tell me that is not abnormal. I have never ever seen a wild 120 Dino with 69 points in any stats.

**Comment by cyberangel67** [comment]
Also the second image is probably the correct way to extract here, but as you can see there is nothing I can do to rectify this.

**Comment by cyberangel67** [comment]
And if you look at first image for extraction I have 80-100 with no difference.

**Comment by VolatilePulse** [comment]
Ok, I think I see where the problems lie. I feel you're having difficulty replicating the extraction I completed in #77 where all of the stats were in the 20-30 range. While you state that oxygen was never increased, I have my doubts. The reason being is that this tool has never failed me. However, I only messed with the stats just enough to get out a 120 perfect tame ptera using kibble on an official server, hence the 85.9% TE. Once I return to my workstation, I can do some further number crunching, but please take a look at the other image posted and let me know what you feel to be an error aside from the oxygen stat. I will gladly take a second look for you and see if we can agree on conclusion to this. If you have a screenshot that is more up to date that what I've seen so far, we can even start fresh with that one. Also, the obvious, make sure your values file and the app is up to date to help eliminate any other potential problems.

**Comment by cyberangel67** [comment]
SMH

I never said I messed with anything, the yellow ones have no options to resolve it. If I switch on the check box for no server reset then it really messes up. I have never had those sort of issues before.

Look I know you're trying to help but there is a 100% calculation issue going on here, secondly all the boxes are unlocked so it doesn't matter what stats have had manual increases on.

This is a claim that I want to add to my breeding library and I can't, as you can see the Dom level is 1 higher than it should be and to remove that I have to adjust the yellow options. Problem is those options have nothing to allow me to resolve it.

While I appreciate you trying to help, you jumping at straws that are not even there and putting words into my mouth saying I said something that I didn't.

Cardon can you please look at this and see what can be done to get this working.

VolatilePulse, I am no longer reading anything you write here.

**Comment by cyberangel67** [comment]
closing this as per my other issues when I levelled it up and tried it now works

**Comment by cadon** [comment]
Hi, glad it was resolved, haven't had time to check here for the weekend. Thanks VolatilePulse for helping out!

Sometimes it's just the game that shows wrong numbers, and it seems for me that's the case here. The Pteranodon got nerfed some time ago, and the game often doesn't update the values of some creatures. Often it works if a stat is leveled up, but for others it doesn't work. E.g. Scorpion and Procoptodon have been nerfed/buffed months ago and are still bugged in many cases because the game partly uses old and partly new values, it's very confusing. One solution would be to offer multiple versions of these creatures, one with the old values and one with the new values, but that would complicate the whole process further and in some cases it doens't work either.

So currently the only solution for non-working stats for these species (Ptera, Scorpion, Roo) is to level up stats and wait for the server to show the correct values. And of course it always can be that the values are changed again and that the tool is outdated, so I'm glad for these reports!

Can #77 be closed as well then? I guess/hope the OP there got his issue resolved as well as they didn't post for a week.
