### ISSUE TITLE
Gallimimus weight and health

### ISSUE THREAD

**Issue by dedlfix** [cadon/ARKStatsExtractor#84]
According to Devkit the Weight of Gallimimus is 270, not 230. I have a just now tamed Gallimimus with a value of 415.8, but ARKStatsExtractor says invalid. Changed to 270 and it can now calculate w/o red color. (checkboxes were checked the right way.)

The "Amount Max Gained Per Level Up Value Tamed" for Health is 0.2, but values.json says 0.27.

Can you please create values.json beautified, so human can read the file w/o using a JSON decoder?

Also Pulmonoscorpius' devkit data are different. The other day it also gave me a red color as I entered  creature data from the game. But I don't remember which values was affected.

**Comment by cadon** [comment]
Hi, thanks for the report. I've updated the Gallimimus weight.

The HP gains 27% for most species, there's another multiplier of 1.35, it's called something like "Extra tamed health levelup", making the 0.2 to 0.27.

For easier reading the json-file you can use a json-editor like http://www.jsoneditoronline.org/, it's also an extension for chrome.

The scorpions are f*** up ;), I've given up on them. Since they got nerfed/buffed, their stats are gone crazy and not reproducable. Sometimes the values work and sometimes not. I hope the game decides someday to only use one value-set for them. Until then you only can try to alter the scorpion-values in the json until they match the current scorpion.

**Comment by dedlfix** [comment]
Currently if the program choses to deny some values you can't save the creature to the library. Can you please consider to allow this nevertheless? In this case of course w/o calculated levels, so I have at least a documentation of the creature in the program and don't have to write it down somewhere else.

**Comment by cadon** [comment]
That's an idea, then tagged with "uncertain stats" or similar, I'll think about how to add that. Until then you can always manually add creatures with the stat-tester, just set any amount of levels and click on "Add to library".
