### ISSUE TITLE
Enhancement - Import Save game, read data from cryopods

### ISSUE THREAD

**Issue by Wulf2k** [cadon/ARKStatsExtractor#882]
Reading pet data from cryopods would make things much smoother.

Here's some Powershell to dump the data from Cryopods as a byte array.

https://pastebin.com/2mhxXCvf

This was scripted against the TheIsland.ark file from a Nitrado Xbox One server, after hex editing the reported version number from 10 to 9.

**Comment by cadon** [comment]
Thanks, I'll have a look

**Comment by DodoCooker** [comment]
Maybe it helps: Attached a rude implementation to extract the cryo-dinos. I didn't want to provide them as pull request cause its a very "unclean" implementation. But it might help you on the tracks to get those dinos extracted.

[ARK.zip](https://github.com/cadon/ARKStatsExtractor/files/2899237/ARK.zip)
Changes in toolkit:
- Added a IsCryo to Objects to "quick and dirty" keep the information that a dino was in a cryopod.
- made the addObject method public so i could access it from the breeding program
- made a copy of CharacterStatusComponent with a Fallback if the property is set but still results in null it will try to get the component with the alternative method
Changes in breeder:
- removed the object filter (could probably be refined somehow so only croyopods get read in addition to dinos)
- always use the "combinedObjects" no matter if hibernationentries or not so i can add in the cryodinos
- within a dirty try-catch try to read the byte-array from cryopods (if its an empty cryopod it goes to the exception) :) -> this probably would need some rewrite to make it more cleaner
- the bytearray seems to be similar to a savefile itself so i used the arkarchive-method. First 4 bytes are eighter some version info or something - just dirty read them. After there a 2 GameObjects - first is the dino, 2nd is the statusobject of the dino. After i used the addObject from the arkSavegame so that the relation between the 2 is set (parent-component). In addition i made it so the dinos from the cryopods are set to the CreatureStatus.Cryopod by setting a flag on those dinos that can be evaluated further down the lines.

**Comment by cadon** [comment]
Feature was added. Thanks for all contributions!
