### ISSUE TITLE
Pelagornis health

### ISSUE THREAD

**Issue by dasbeiler** [cadon/ARKStatsExtractor#89]
I have 4 high level Pelagornis tames and on all four of them I can not get a valid health stat on the extractor, nor can I seem to match the numbers in any way in the stat tester. 

Health values are 
1248.1
1472.1
1216.1
896.1

I would like to add that I have had 0 issues with the rest of my 40+ tames getting all the values accurate...

**Comment by cadon** [comment]
Hi, the pelagornis' stats were changed recently, and the game always takes some time to adjust to the new values. Try to level up health, that sometimes resolves the issue by forcing the game to recalculate the stat-values with the correct values.

**Comment by Brybry** [comment]
From my testing (mag glass on wild pelicans) I'm seeing wild levels give 32 hp (0.2 mult) instead of 42 (0.2625) now. 

But more than that has changed for tamed health and I'm not exactly sure how to figure out the proper values.

Freshly tamed 167 pelican (base level 112) with (I believe) 99.6% effectiveness had pre-tame stats: HP 608.0, ST 800.0, O 360.0, F 3000.0, W 146.0, DMG 160.0, TORP 919.2  
Post tame w/ 4 kibble on an 8x taming mult server for 99.6% eff:  HP 860.1 ST 1010.0 O 465.0 F 4688.8 W 170.3 DMG 275.1 TORP 2114.9

**Comment by cadon** [comment]
Thanks for the report, with the updated values-file it should work now.
