### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by slash36** [cadon/ARKStatsExtractor#891]
Will this be updated 2560 x 1440p resolution for the overlay? It seems it won't work at this resolution.

**Comment by cadon** [comment]
Hi, what issues do you have?

**Comment by VolatilePulse** [comment]
The current OCR library is limited in its resolution support. Larger resolutions than 1080p appear to have very spotty accuracy due to the lack of font sizes. The recommendation is to instead use the [Dino Export feature](https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports).

Closing due to no response.
