### ISSUE TITLE
Impossible Taming Effectiveness saved/loaded

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#896]
When I tried to edit a creature to set it to 'neutered', I got a warning about '100,00005186918900' not being a proper value for 'Value', and that it needs to be between 'Minimum' and 'Maximum.' When opening the .xml in a different way, I found out it is Taming Effectiveness that had this value. I had to manually edit the file for it to work.

**Comment by coldino** [comment]
Could we have a copy of the original export file please?

**Comment by cadon** [comment]
Hi, some time ago (a year or so), the taming-effectiveness of creatureValues was saved as percentage instead of the non-percentage way. This issue was not present in library-creatures, though.
I'll include a check for valid values in the next release, so it shouldn't cause an exception anymore. I'm unsure why this issue is happening with a creature you edit from the library though. When did you extract the creature and are there other creatures that have this kind of TE?
