### ISSUE TITLE
Wooly Rhino Tame

### ISSUE THREAD

**Issue by Gamersmack** [cadon/ARKStatsExtractor#91]
I put in the Extractor that I tamed a 224 Rhino (Kibble 150) and once I hit "Add new to Library", it put said Rhino in as a level 373. I have only experienced this with the Rhino so far. As you can see in the image below, I put in the extractor that it came out at 224 but once I hit add.. It adds it as a 373.

![d701495be25bc1d7bbe3453259cb4c3f](https://cloud.githubusercontent.com/assets/15797514/17610425/2352594e-6081-11e6-9992-dcb91d00f1c2.png)
![c80a547675da9fb0466407bede4188ce](https://cloud.githubusercontent.com/assets/15797514/17610424/23496ae6-6081-11e6-9352-95f431278e31.png)

**Comment by cadon** [comment]
Hi, for most of the creatures you forgot to check the "Since Taming no Server-Restart"-checkbox. There's a bug in the game, that shows too high torpor-values after taming, this causes too high wild-levels. If the value for the wild-level is too high, that's an indication that this checkbox has to be checked.
