### ISSUE TITLE
Adding Atlas creatures to be used with Ark Smart Breeding

### ISSUE THREAD

**Issue by twistedx** [cadon/ARKStatsExtractor#911]
Hello Cadon,

I would like to work with you to add the Atlas creatures to the smart breeder so we can utilize this wonderful program in that game.  The breeding mechanics work the exact same as ark, just the level distribution works differently.  I will gladly do the work to get you anything you need to do it even if you need me to add it to a json or whatever.

Smart Breeder works not on the game it's just the creatures are not in the system so it doesn't calculate the numbers properly.

**Comment by cadon** [comment]
Hi, thanks for the offer. I don't own Atlas, so I can't be much of a help here. Have a look this page that describes how to create a file for mods ( https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values ), maybe Atlas-species can be supported just by an extra file. If you can create a file with one species and test it, it would be a first step. Then we have to see if the application itself has to be adjusted to support the species.

**Comment by meza** [comment]
I'd love this too!

**Comment by VolatilePulse** [comment]
I looked at this previously with another user and the verdict is that the logic in ASB should work fine with Atlas. The issue is that our system to gather the data for ASB cannot extract the data for Atlas. Officially, we won't be supporting Atlas. Unofficially, you're more than welcome to generate your own mod file for Atlas and use it based on the link that was posted in Cad's reply.
