### ISSUE TITLE
Damage Points Dont Match Up

### ISSUE THREAD

**Issue by KamikazeeCat** [cadon/ARKStatsExtractor#912]
I have been trying for weeks for max lvl tames w high damage w no luck. so i decided to put the stats of my highest into dodo dex and it comes out w 10 more points into melee? Same w the ark companion app. Not sure what is going on, it seems to be off on all my breeds but just w the melee which then makes the speed higher.

**Comment by KamikazeeCat** [comment]
I have also already checked the settings for the stat changes and its all set to official and not checked in single player.

**Comment by VolatilePulse** [comment]
All of those tools specifically state they only work on wild creatures. ASB is one of the very few tools that is able to extract creatures post tame or even after being bred. While ASB has some faults, I'd feel confident in saying ASB is correct. Have you been experiencing any extraction issues otherwise?

**Comment by KamikazeeCat** [comment]
every once in a while i have to manually do it but not really unless i have already imprinted. just seems weird  that all the other stats match up on the other apps but just not the damage.

**Comment by KamikazeeCat** [comment]
i mean ive tamed over 50 perfect tamed thylas and the highest ive managed to get in melee is 43. Does that not seem off?

**Comment by VolatilePulse** [comment]
I'm not sure what you mean by manually doing it. And it's because melee has two post tame bonuses for most species. One is referred to as TameAdd, the other TameAffinity. Since these values are added, and those other tools don't apply them, a creatures actual number of Melee levels would appear lower in ASB than those other tools. If you'd like to very the quality of ASB, use either a mod like Super Spyglass or the Admin Rifle. The creature's levels are displayed in game.

But no, that doesn't seem off. I've been playing for years and while I have managed to get higher levels, I've also tamed tens of thousands of creatures. Level Distribution is solely based on RNG and it ultimately just comes down to how lucky you are.

**Comment by KamikazeeCat** [comment]
alright honestly i know nothing about the two melee tame bonuses so im just going to take your word on it lol

**Comment by VolatilePulse** [comment]
You can check out some of the official values that ASB uses on the [wiki page] (https://ark.gamepedia.com/Thylacoleo). You can find these values in a nice chart under the Basic Info section, right around the color regions. Things are still slightly more complicated than they appear, but it's the general idea of it.

**Comment by VolatilePulse** [comment]
But if you have any more questions about it, feel free to ask, or I can show you how to extract a creature by hand (forewarning, it's messy, time consuming, and the reason there is a program for that).

**Comment by KamikazeeCat** [comment]
yea i think ill pass on that for now, thanks for the help though.
