### ISSUE TITLE
Pulmonoscorpius Health Issue

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#92]
Currently the Pulmonoscorpius don't have recognized health, even if i level some of them up.  Playing on official pve server.  Going to see if i can tame a fresh scorpion and see if mine are just bugged or something.

**Comment by cadon** [comment]
Hi, Scorpions have issues in general. Their stats once got changed (at least half a year ago), and since then the game sometimes uses the old and sometimes the new values for increasing, or something completely different, I haven't figured it out yet. You can either add the scorpion manual with the stat-tester (and choose a level for health that has a close value to the one ingame), or change the values.json-file, maybe you find values that make an extraction for this scorpion possible.

**Comment by Worldgate** [comment]
Have you considered using two different variations for the scorpion?  I had same thing happen with gigas where ive never increased health and several gigas have slightly different health.  Not sure whats wrong with wildcard and their retarded nerfs causing dinos to have different amounts.

**Comment by cadon** [comment]
Yes, I tried. The issue is, there's the base-value and the amount it increases per level. The increase per level is a percentage of the base-value (usually 20%). The problem is, the scorpion sometimes uses the new base-level, but the percentage of the old value; for this I tried to adjust the percentage accordingly (to 21.4285714285714%). That worked for that very scorpion, but not for the next I tried. For one scorpion I once tried all 4 variations (old base, old increase; old base, new increase; new base, old increase; new base, new increase) and nothing worked. So I'm currently annoyed by the scorpion (and the other species with that issue) and waiting for Wildcard to fix the issue. You can also check #16 for more data on that issue. Maybe you find something useful.
