### ISSUE TITLE
Program wont grab all stats consistantly.

### ISSUE THREAD

**Issue by clericcraft** [cadon/ARKStatsExtractor#933]
Up until recently the Stats extractor has worked flawlessly. Lately however I have been getting a lot of partial extractions like this: [url](http://prntscr.com/oi44bq).
Stamina, Oxygen, Weight, Damage, Speed and Torpor all work fine, but Food and Health are both bugged out. 
I've had it do this with Giga, Argentavis and other long-time ark dino's as well as newer ones so I do not believe the issue rests in the newer dino's. It also doesn't happen ALL the time. Re-starting the program can sometimes fix it, or fix parts of it.

**Comment by cadon** [comment]
The values of HP and food look very low, are you sure the numbers are correct?

**Comment by clericcraft** [comment]
Those values are bugged out as the program refuses to read them. The stats as I recorded them on paper are as follows: 

Level 209 | Health 3168 | Stamina 1040 | Oxygen 765 | Food 945 | Weight 513 | Melee 361

I recorded these just after taming.

**Comment by Wulf2k** [comment]
https://snag.gy/iG9qkb.jpg

https://snag.gy/SVzKap.jpg

I can confirm issues with stat extraction.  The above was the latest, but I've seen it several times.

Also, had an issue with the below juvenile doed post-cuddle.  Stats extracted fine post-birth, but the imprint bonus to health failed.  

https://snag.gy/kYIr6x.jpg

Official PVP server.

**Comment by VolatilePulse** [comment]
@clericcraft the extractor for ASB requires the entire displayed value, not just the whole numbers in order to provide stat extraction. In the screenshot you provided originally, the health and food were well under the base values. The numbers you provided above also don't include any decimal places, but why are you not using the current stat values instead of the ones you wrote down? ASB supports extracting levels from creatures that have been leveled post tame/maturity.

@Wulf2k that sounds like an issue we are aware of, referred to as the Imprint Bug. This is an issue within how Ark calculates stat values when an imprint is applied, not with ASB itself. The typical recommendation is to use a cryopod, upload/download the creature from an obelisk, supply drop, transmitter, or attempt to leave render range for about 5 minutes. None of these are ideal, but there's nothing more we can do about it until Ark fixes it. A server restart can help too, but official servers rarely restart.

**Comment by Wulf2k** [comment]
I wasn't overly fussed about the imprint issue, but the first 2 links are a tamed scorp and separate from the imprint issue.

Any thoughts on why that one wouldn't work out?

**Comment by clericcraft** [comment]
@VolatilePulse Here is the screenshot of the actual dino: [http://prntscr.com/oia7sv](http://prntscr.com/oia7sv) It is wild tamed, not bred, so no imprint. I record the stats my self for other breeding purposes. I use the stat extractor to tell me where points have gone, and what the original stats were if the tame has been leveled. I did not enter the stats into the extractor manually. What you see is the stat extractor solely.

The issue I'm having with stat extraction is on both wild and bred. I am aware of the imprint bug and have the cryo pods to deal with that easily. This seems to be another issue.

**Comment by clericcraft** [comment]
Here is another SS of the stat extractor without my intervention. This is simply what it gives me on its own and was recorded just after the SS of the dino its self. [http://prntscr.com/oiaakz](http://prntscr.com/oiaakz)

**Comment by cadon** [comment]
@clericcraft I think some of the confusion comes from a different use of the word `extraction`. Extraction describes the process of extracting the level values when stat values are given. I think you are using the optical character recognition (OCR) for reading the values directly from the game. Using OCR will produce errors which have to be corrected manually, like in your case.
It is recommended to use the [creature export](https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports) as described in the wiki. This will always give you the exact stat-values and also the colors and ancestors (if the ancestors tab has been opened ingame prior to exporting).

**Comment by Wulf2k** [comment]
Here's the scorpion before cryopodding.  Stats wouldn't extract.
https://snag.gy/SVzKap.jpg

Here's the scorpion after cryopodding, HP updated, stats won't extact.
https://snag.gy/3CrgGK.jpg

Here's the stats failing to extract
https://snag.gy/dv9qnV.jpg

**Comment by kohonac** [comment]
open up the effective taming range and unlock the two locked stay and report back please since the program may not be able to come up with the correct information if one or any of those are outside of the range its currently using

**Comment by Wulf2k** [comment]
Interesting.

Are they functionally two different species with identical names then?

Would "guess the species" work if scorpions had two entries?

**Comment by VolatilePulse** [comment]
Unfortunately not as it's more of an internal calculation bug. The scorpion (and Aberrant scorpion) uses a base health stat of either 280 or 300, where 300 is the "correct" value. 280 is an old value they meant to buff to 300, but due to the way they implemented the buff, it doesn't always apply properly and occasionally you end up with a scorpion that uses the 280. 

These base values apparently "stick" with the creature through all of our known reset techniques. Playing on official, I'm not aware of anything that can be used to correct it either.

**Comment by coldino** [comment]
The health on your scorpion did change when you un-cryo'd it, which is odd. We would expect that if it were bred, due to the imprint bug, so perhaps we are seeing some change related to the "phantom" species stats.

Still no idea how to extract it if neither before cryo or after cryo worked!  You might have stumbled on one of the few cases where a manual adjustment of +/- 0.1 to the health is needed.

**Comment by clericcraft** [comment]
@kohonac here is the overlay with your suggested changes.

Also @VolatilePulse I know that the aberrant variants are supposed to have lower health and higher damage base values. Possibly treating the aberrant variants as a separate species? Just a side thought

**Comment by VolatilePulse** [comment]
My most recent comments were in response to @Wulf2k and the issue they were having.

@cadon answered your question already. We do not recommend the use of OCR or the overlay as it is rather inaccurate. Instead, we suggest using the creature export method he linked above. If you decide to continue to use OCR and overlay, you need to know that it will regularly require manual corrections of stat values as the numbers are rather hard for a computer to read and it makes errors fairly regularly.

**Comment by Wulf2k** [comment]
Had another issue with a tamed Parasaur that it couldn't extract.  Are parasaurs one of the known problem species?

**Comment by VolatilePulse** [comment]
@Wulf2k No, Parasaur are not known to have any stat issues. Can you provide any screenshots of what's going on?

**Comment by Wulf2k** [comment]
Sure, I'll get one in a few hours.  I believe it was the health again, and adjusting hp up or down by 0.1 didn't let it work.

**Comment by Wulf2k** [comment]
Disregard the parasaur.  Not sure if something reset/updated or i just was blind to a typo before, but it extracted fine now.
