### ISSUE TITLE
Not importing all dinos?

### ISSUE THREAD

**Issue by radicaled06** [cadon/ARKStatsExtractor#936]
For some reason, the app is not pulling all of my exported files into the app. I'm not sure why this would be happening? 

I have these export files in the target folder.
![image](https://user-images.githubusercontent.com/31147307/61911508-b6ea0c80-af05-11e9-896d-119b6804d249.png)

But the app does not recognize or does not import those files, seen here.
![image](https://user-images.githubusercontent.com/31147307/61911567-da14bc00-af05-11e9-8e3c-71038e3bec9a.png)

**Comment by VolatilePulse** [comment]
That would be because you don't have the same directory listed in ASB as the directory you took a screenshot of. If you click at the end of the address bar in the file explorer, you'll see the entire directory path and that it doesn't match the directory you have listed in ASB.

**Comment by coldino** [comment]
Alternatively, they would also not show up if they were modded creatures and you hadn't loaded the appropriate mod values file.

**Comment by radicaled06** [comment]
They are definitely the same folder path, and they are modded creatures through classic flyers. I guess I'm confused on how that works, do I need to load the classic flyers file every time I open the library? Or before I export the dinos?

**Comment by VolatilePulse** [comment]
For sanity reasons, can you copy paste the explorer path in your next reply?

If you have already loaded the classic flyers JSON and saved your library, that should be sufficient.

**Comment by radicaled06** [comment]
No problem!

![image](https://user-images.githubusercontent.com/31147307/61912874-4b09a300-af09-11e9-9106-7f1149f440d1.png)

![image](https://user-images.githubusercontent.com/31147307/61912909-72607000-af09-11e9-94a4-eb5ab7bfcfd0.png)

![image](https://user-images.githubusercontent.com/31147307/61912931-84daa980-af09-11e9-89ed-a75066ae5f62.png)

**Comment by radicaled06** [comment]
Okay, figured it out again. Seems to have been a conflict with one of our other mods, possibly also affecting the dino files. I removed that mod, and the files are importing correctly again. 

Thanks for your time. =]

**Comment by VolatilePulse** [comment]
The reason screen captures don't work is because File Explorer obscures longer path names. But either way, you're able to see export files in ASB now? That's one part of the issue. The next part is trying to figure out why it isn't being displayed for you. If you open the export file (text editor like notepad is fine), the Blueprint path will show which mod a creature is from. If you're unsure what to do, you can upload the export file here and I'll take a look.

**Comment by radicaled06** [comment]
To clarify, yes, I am able to export from ARK, I can see the files that are created in the folder. The problem comes in when I try to import those files into ASB. ASB simply does not show those dinos in the import list. 

When I open my fire wyvern file using Notepad++ it shows me this path "DinoClass=/Game/Mods/Wyvern_Mating/Wyvern_Character_BP_Fire.Wyvern_Character_BP_Fire_C"

This implies it is created through my wyvern mating mod, which to my knowledge, does not alter any stats on the wyverns, it simply allows them the functionality to breed. I will double check on steam to verify this.

**Comment by VolatilePulse** [comment]
Even thought the mod may not change the base stats of a Wyvern, ASB doesn't know about that mod or any creatures in it and refuses to load it purely because it doesn't know what it is. They can be added to a mod file, like the classic flyers one you already have, but it's not recommended as two mods that alter the same species cause some really chaotic affects behind the scenes and can't be properly handled by ASB yet.

The short of it is that you can attempt to add these Wyvern to your mod file and hope for the best, or wait until the feature is added in a future release. I'm sorry I don't have a better answer for you at the moment though.

**Comment by radicaled06** [comment]
Okay! No problem, I'm just glad to know what is causing the issue, that makes sense now. Should I submit the implementation of that as a feature request, or tag this issue as one, perhaps?

**Comment by VolatilePulse** [comment]
Most of the framework is in place with the upcoming release but I've added it to the project to make sure it is addressed before we begin beta testing.

One of the limitations of ASB is that it **must** know what a species is before it can do anything with it. This requires specific mod files to be loaded for creatures, even if the mod doesn't alter any of the stat values. While that mod isn't in our standard list for the next release, I believe we will be allowing users to request mods in the future. This is all theoretical at the moment, but for the latest information, I would encourage you, or anyone else that reads this, to join us on [Discord](https://discord.gg/qCYYbQK).

**Comment by radicaled06** [comment]
Okay perfect, thank you!
