### ISSUE TITLE
Cryopods

### ISSUE THREAD

**Issue by urb0123** [cadon/ARKStatsExtractor#948]
I'm kind of a new player. I hope it's ok to ask this question here. 

 I've been using the smart breeding application for quite awhile. I don't know all the ins and outs but it's been handy to read in our LAN server's "TheIsland.ark" file and see all the dinos as my kids can't be bothered to keep track of stats on dinos they tame. I'm using version 0.30.1.0, the current version as far as I know.

I've recently started using cryopods. It seems I'm unable to view dinos in a cryopod when I read in the server file. I know I have some Tapejera's but they don't show either. (Maybe they're in cryopods?)

On the GitHub page it claims this was fixed in a previous version. So I'm guessing I have a setting that's wrong.

I've made sure the "Show Cryopod Creatures" checkbox on the "View" tab in the bottom left of the Library page is checked. Also the top "View" menu has a checkbox for "Cryopod Creatures". I've checked that as well.

Any other things I should be doing?

Thanks!

**Comment by cadon** [comment]
Hi, soon there'll be a new release, I hope in the coming week. We're currently fixing the last issues in it. Maybe it'll work in this new version 0.33.

**Comment by urb0123** [comment]
Thank you cadon! 

Maybe I can be of some help one of these days.

**Comment by cadon** [comment]
Hi, apparently cryopods are not imported currently. We'll look into this later after the current version is somewhat stable without larger bugs.

**Comment by thFrgttn** [comment]
I don't know if this helps (or hinders) but I was playing around a bit with your code.
Cryopods aren't being loaded due to your object filter in readSavegameFile.

.WithObjectFilter(o => !o.IsItem && (o.Parent != null || o.Components.Any()))

commenting that line out and I was able to hack some code together and get data of a dino in a cryopod like so

 IEnumerable<GameObject> poddedCreatures = gameObjectContainer.Where(o => o.ClassString == "PrimalItem_WeaponEmptyCryopod_C" && o.HasAnyProperty("CustomItemDatas"));

GameObject firstPoddedCreature = poddedCreatures.First();
SavegameToolkit.Propertys.PropertyArray test = (SavegameToolkit.Propertys.PropertyArray)firstPoddedCreature.Properties[4];
ArkArrayStruct arra = (ArkArrayStruct)test.Value;

StructPropertyList l = (StructPropertyList)arra[0];
SavegameToolkit.Propertys.PropertyArray names = (SavegameToolkit.Propertys.PropertyArray)l.Properties[1];
SavegameToolkit.Propertys.PropertyArray values = (SavegameToolkit.Propertys.PropertyArray)l.Properties[2];
SavegameToolkit.Propertys.PropertyArray customclasses = (SavegameToolkit.Propertys.PropertyArray)l.Properties[4];

**Comment by cadon** [comment]
Hi, thanks for this code! It's on the todo list to implement this, it may take some time.

**Comment by urb0123** [comment]
I appreciate focusing on quality over new features. Thank you!

**Comment by thFrgttn** [comment]
With that code it's pretty easy to make a list of all the dinos in pods on a server (which is what I used it for), but I found it odd that the dino name was easy to get, but I couldn't get the dino ID

**Comment by EmkioA** [comment]
Hi thFrgttn,

 i just start from you code and with an hex editor into the save game i manage to get the Cryopoded Dinos structure as an bytearray you can take a look into my fork, under the Feature948 branch into file : ImportSaveGame.cs
https://github.com/EmkioA/ARKStatsExtractor/blob/Feature948/ARKBreedingStats/ImportSavegame.cs

Dont forget to comment out the filter : cause the cryopodes will not receive the customitemdata with this filter on :

// .WithObjectFilter(o => !o.IsItem && (o.Parent != null || o.Components.Any()))


This code is messie and was just a proof



`            IEnumerable<GameObject> CryopodObjects = gameObjectContainer.Where(o => o.ClassString == "PrimalItem_WeaponEmptyCryopod_C" && o.HasAnyProperty("CustomItemDatas"));


            foreach (GameObject go in CryopodObjects)
            {
                // go.Properties[5].Value[0].Properties[6].Value.properties[0].value[0].Value      <- Creature structure into the Cryopod.
                StructPropertyList cidValues = (StructPropertyList)((ArkArrayStruct)((PropertyArray)go.Properties.Where(p => p.NameString == "CustomItemDatas").FirstOrDefault()).Value)[0];
                StructPropertyList cdbValue = (StructPropertyList)((PropertyStruct)cidValues.Properties.Where(p => p.NameString == "CustomDataBytes").FirstOrDefault()).Value;
                StructPropertyList baValue = (StructPropertyList)((ArkArrayStruct)((PropertyArray)cdbValue.Properties.Where(p => p.NameString == "ByteArrays").FirstOrDefault()).Value)[0];
                var bValues = ((ArkArrayUInt8)((PropertyArray)baValue.Properties.Where(p => p.NameString == "Bytes").FirstOrDefault()).Value);
                // bValues I think contain the Creatrure bytes structure their must be a way to convert it back to a GameObject.

                // DinoID1 = byte : 1861-1864
                // DinoID2 = byte : 1904-1907

                // as a proof the IDs equal what i have into my DinoExport file for the cryopoded creature.
                var DinoID1 = BitConverter.ToInt32(bValues.ToArray(), 1861);
                var DinoID2 = BitConverter.ToInt32(bValues.ToArray(), 1904);
            }`

**Comment by cadon** [comment]
implemented in v0.38.0. Thanks for all the input!
