### ISSUE TITLE
OCR doesn't work sometimes

### ISSUE THREAD

**Issue by DaSlush** [cadon/ARKStatsExtractor#96]
Hello just wanted to say before I start that I LOVE this program!

It has been working great for me for a couple weeks until about 2 days ago. Usually when I have the ARK game up, a dinos "inventory"/Stats up, then I hit Read Ark Values the program blinks for a second and reads and inputs the values. Usually with no errors. However the last couple days it still blinks like it wants to do it, however it never pops back up or inputs any values. Anyone else having this problem? I've check to make sure it has the latest version and updates. I can manually enter the values in so it's not the end of the world, just wondering if there is a fix as I do a lot of breeding and would love to save a ton of time. Thanks again!

**Comment by cadon** [comment]
Hi, thanks and sorry for the late reply.

The OCR / text-recognition works well for 1920x1080, but not always. Other resolutions have more issues. It's a nice feature if working, but unfortunately the fonts are sometimes too small to be recognized well by this tool, especially if the resolution is smaller than 1920.

Did you change your resolution maybe when it started to work less good? What resolution do you use?

**Comment by Zhinjio** [comment]
Things I noticed, using this last night for around 50 tames.
- I am using 1920x1080, so at least in theory, OCR should work about as well it can?
- It usually takes 2 "refreshes" of switching to the ARK window, then clicking on "Test OCR" to get it to read in values. But it would read them in.
- If the tames inventory was full, the mouse hover would be on an item, and the tooltip would cover some of the values to be read, and cause them to be invalid/not read. Inputting them manually would work fine. Removing items from inventory so that the mouse was NOT forcing a tooltip would also work
- Numeric values that would misread were usually big numbers. > 10000. Smaller numbers, or numbers without a lot of repeating 0's would generally read fine.
- Font issue: aye's turn into ells almost every time ( i > l )
- Font issue: oh's turn into ewe's sometimes (Second > Secund)
- Font issue: kay's and aich's often switched (k > h or h > k, also in uppercase)
- Occasionally, it would not detect the type of beastie correctly, and so values would be really off/not validate. Selecting the right beastie manually would fix.
- It cannot detect gender at all. Though since this information is not present (that I can find) on the inventory panel, this really isn't a surprise. Oversight on the ARK devs part, not yours. I just usually glance at it before I open the inventory panel, and make sure to edit that part of the profile before I save it (or edit it after if I forget).

Thats it for now.

- Z

**Comment by Zhinjio** [comment]
Reading in values ALWAYS works when I have the game set to fullscreen windowed instead of fullscreen.

**Comment by cadon** [comment]
The import exported method is recommended over the OCR, it's more reliable and also imports colors. Improvements to the OCR are unlikely.
