### ISSUE TITLE
Managarmr Missing from Library

### ISSUE THREAD

**Issue by Kiety** [cadon/ARKStatsExtractor#968]
Since updating, my managarmr section in library is missing. I can add new ones, which are the only ones that show up in the breeding program. If I try to add old ones, the program thinks they are still in the library and will only let me update them, doing this does not make them appear again in the mana list.

Import List with 2 new, one existing (pre-update) mana.
![image](https://user-images.githubusercontent.com/18669289/66113049-996ca980-e5fe-11e9-9bfd-31e8d81a2637.png)

Mana Library
![image](https://user-images.githubusercontent.com/18669289/66112998-78a45400-e5fe-11e9-885d-811e99c5507b.png)

Trying to add the mana that was in library before updating.
![image](https://user-images.githubusercontent.com/18669289/66113135-c8831b00-e5fe-11e9-80d6-749a8b9446a8.png)

My mana library had over 50 manas in it. The file is shared and my friend, who is still on an old version of the program, can still see them. My view dropdown has everything ticked.

**Comment by cadon** [comment]
Hi, thanks for the report. In the next release when you import the Managarmrs again, they should reappear.
It's recommended to use the same version of ASB when sharing libraries.

**Comment by Kiety** [comment]
Is there any way to recover the data without re-importing? I have a lot of manas in cryos, or dead/traded etc for my records and it will be sad to see everything lost.

**Comment by VolatilePulse** [comment]
You can, but it is a bit tedious. You can open the library files (`.asb`) with any text editor. Once open, you can make any changes you'd like, but the one you're specifically looking for is the `speciesBlueprint` being an empty string (""). In order to fix this, you will need to copy the Managarmr's blueprint from one of your other Managarmr that have been added since the update.

Sorry if it sounds a bit complicated, but if you're having issues understanding, I'll get some screenshots later this evening for you. Also, not all empty species strings are for Managarmr. I did one the other day where 2 parents were missing the Gacha's blueprint instead.

**Comment by Kiety** [comment]
Thank you so much! Not complicated at all <3 This fixed the issue completely for me. Turns out I had 223 manas, not 50 hahaha.

![image](https://user-images.githubusercontent.com/18669289/66219418-b5a34000-e6fd-11e9-8a13-6d8f7d944996.png)
