### ISSUE TITLE
Spanish, French and Italian translations do not apply

### ISSUE THREAD

**Issue by KRIPT4** [cadon/ARKStatsExtractor#969]
When trying to change languages in Settings > Language (WIP) they do not apply. Only English and German works.

**Comment by VolatilePulse** [comment]
Everything appears to be working as expected. Some things to take note of is that the program is developed in English and the developer is also German so when new words or sentences are added, there is typically a German translation for that word or sentence. While translations have been provided by the community, they need to be updated manually every time a new section is created. I believe what you are seeing is that a lot of the content in the settings is still in English, or German, when you change languages, but that's only because no translations have been supplied for that new content yet. 

If you are interested in providing a translation, you can extend on an existing translation or create a new one if it doesn't exist yet. For more information, see [Translations](https://github.com/cadon/ARKStatsExtractor/wiki/Translations) for more information.

**Comment by KRIPT4** [comment]
Hi VolatilePulse, I did the translation into Spanish #959 I mean that when switching between language and language, they do not apply in any way to me.

Try to save and close and reopen but it doesn't work. Uninstall and reinstall v0.34.1, it didn't work either.

**Comment by VolatilePulse** [comment]
I'm sorry, I completely forgot about that. However, it does still appear to be working properly for me. Again, I see some strings that may not have been translated yet. It may be an issue of incomplete support of localization or using an outdated template. I believe @cadon will need to look into this as I'm not overly familiar with the language implementation.

As you can see in the screenshot, it is a mix of English and Spanish. Is this what you see as well?
![image](https://user-images.githubusercontent.com/6995232/66186108-5be43c80-e64f-11e9-98f9-f3ee9ca613de.png)

**Comment by KRIPT4** [comment]
It's very strange mine doesn't look like this. I only see in English when selecting Spanish, French or Italian.

![image](https://user-images.githubusercontent.com/28142138/66193073-3152ad80-e668-11e9-8ff0-95eaec3d769e.png)

The translation was done based on the file strings.resx (which is the defect in English)

**Comment by KRIPT4** [comment]
I found the problem! when downloading the exe from the program by mode "Check for Updates", this installs only the files:

![image](https://user-images.githubusercontent.com/28142138/66194476-e7b79200-e66a-11e9-92f6-10b650d00e54.png)

Download the version in ZIP:

![image](https://user-images.githubusercontent.com/28142138/66194549-146ba980-e66b-11e9-99ab-2d149940ebc7.png)

Replacing:

![image](https://user-images.githubusercontent.com/28142138/66194678-5694eb00-e66b-11e9-8ecc-83ab959a2831.png)

Working!

![image](https://user-images.githubusercontent.com/28142138/66194742-804e1200-e66b-11e9-8265-32006820b0ca.png)

**Comment by cadon** [comment]
Thanks, there was an issue with the installer-settings. I reuploaded it, it should work now.
