### ISSUE TITLE
Issue With Eel Import

### ISSUE THREAD

**Issue by MadMaxOfYore** [cadon/ARKStatsExtractor#987]
Hey - we're unable to get this eel to import into our library. Any ideas?

This is on an official server. I have not modified the multipliers in Smart Breeder.

https://imgur.com/a/ooDfnCy

**Comment by cadon** [comment]
That's strange. The value of the HP stat is approximately 2 times as high as expected.
Are you on any special server like `Small Tribes`, `Classic` or similar? When did you tame that eel? Where did you put the level up, is it HP? When did you level up the stat?
Can you attach the export file here?

**Comment by cadon** [comment]
Turns out it's a bug in ARK. You cannot extract the eel in ASB directly. The correct values are as follow. It could be the HP ingame will at some time show the correct value of 1631.4, but we don't know what it causes these values to switch. You can use the values below to add it to the library.
(Electrophorus, Lvl 216, TE: 97.9%): HP: 1631.4 (38, 1); St: 610.5 (27, 0); Ox: 4620 (34, 0); Fo: 4500 (20, 0); We: 240 (30, 0); Dm: 260.3% (32, 0); Sp: 100% (33, 0); To: 2422.5 (214);

**Comment by MadMaxOfYore** [comment]
I'm a little confused. Does this mean that the HP is not actually that high?

**Comment by VolatilePulse** [comment]
Technically, no. Wildcard nerfed the Eel health a while back but the code in Ark doesn't always acknowledge the Nerf properly. Effectively, the Eel you have there is using an old value for health. It may never revert to the correct, lower health, or it may randomly convert to the correct health.

We currently aren't aware of a way to force a creature to use the proper value and we haven't found a way to handle both values properly yet as the algorithms for the extractor are fairly complex with just one health value.
